apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: blocky
  namespace: blocky
spec:
  interval: 15m
  chart:
    spec:
      chart: blocky
      version: 16.6.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:

    TZ: America/Chicago

    credentials:
      cloudflare:
        type: s3
        url: "${S3URL}"
        bucket: "${S3PREFIX}"
        accessKey: "${S3ID}"
        secretKey: "${S3SECRET}"
        encrKey: "${S3ENCR}"

    service:
      dns:
        type: LoadBalancer
        loadBalancerIP: ${BLOCKY_IP}

    blocking:
      # -- Sets the blocktype
      blockType: ${NULLSERV_IP}
      # -- Sets the block ttl
      blockTTL: 10s
      # -- Sets the block refreshPeriod
      refreshPeriod: 4h
      # -- Sets the block download timeout
      downloadTimeout: 60s
      # -- Sets the block download attempt count
      downloadAttempts: 3
      # -- Sets the block download cooldown
      downloadCooldown: 5s
      # -- Set the start strategy (blocking | failOnError | fast)
      startStrategy: fast
      # -- Sets how many list-groups can be processed at the same time
      processingConcurrency: 8
      # --  Add blocky whitelists
      whitelist:
        - name: ads
          lists:
          - https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/optional-list.txt
          - https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt
          - https://raw.githubusercontent.com/rahilpathan/pihole-whitelist/main/1.LowWL.txt
      # -- Blocky blacklists
      blacklist:
        - name: ads
          lists:
            - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
            - https://raw.githubusercontent.com/kboghdady/youTube_ads_4_pi-hole/master/youtubelist.txt
        - name: porn
          lists:
            - https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/porn-only/hosts
        - name: gambling
          lists:
            - https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/gambling-only/hosts
        - name: fakenews
          lists:
            - https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-only/hosts
        - name: social
          lists:
            - https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/social-only/hosts
      # -- Blocky clientGroupsBlock
      clientGroupsBlock:
        - name: default
          groups:
            - default
        - name: ${ADMIN_NET}
          groups:
            - ads
        - name: ${LAN_NET}
          groups:
            - ads
            - porn
            - fakenews
            - gambling
        - name: ${GUEST_NET}
          groups:
            - ads
            
    k8sgateway:
      # -- list of processed domains
      domains:
          # -- Delegated domain
          - domain: ${DOMAIN_0}
            # -- Optional configuration option for DNS01 challenge that will redirect all acme
            # challenge requests to external cloud domain (e.g. managed by cert-manager)
            # See: https://cert-manager.io/docs/configuration/acme/dns01/
            dnsChallenge:
              enabled: true
              domain: dns01.clouddns.com

      forward:
        enabled: false
        primary: tls://1.1.1.1
        secondary: tls://1.0.0.1
        options:
          - name: tls_servername
            value: cloudflare-dns.com
                
    cnpg:
      main:
        enabled: true
        user: blocky
        database: blocky
        mode: recovery
        backups:
          enabled: true
          revision: 1
          credentials: cloudflare
        recovery:
          method: object_store
          credentials: cloudflare
