apiVersion: v1
kind: PersistentVolume
metadata:
  name: recyclarr-nfs-pv
  namespace: media
spec:
  storageClassName: recyclarr-nfs
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.1.0.63
    path: "/Heimdall/Downloads/recyclarr/"
  mountOptions:
    - nfsvers=4
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - nolock
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: recyclarr-nfs-pvc
  namespace: media
spec:
  storageClassName: recyclarr-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi