kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-claim-iscsi
spec:
  storageClassName: heimdall-iscsi-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
