apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: clusterissuer
    namespace: clusterissuer
spec:
    interval: 15m
    chart:
        spec:
            chart: clusterissuer
            version: 9.2.2
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
            interval: 15m
    timeout: 20m
    maxHistory: 3
    driftDetection:
        mode: warn
    install:
        createNamespace: true
        remediation:
            retries: 3
    upgrade:
        cleanupOnFail: true
        remediation:
            retries: 3
    uninstall:
        keepHistory: false
    values:
        manifestManager:
            enabled: true
        workload:
            main:
                enabled: false
                podSpec:
                    containers:
                        main:
                            enabled: false
                            probes:
                                liveness:
                                    enabled: false
                                readiness:
                                    enabled: false
                                startup:
                                    enabled: false
        service:
            main:
                enabled: false
                ports:
                    main:
                        enabled: false
                        port: 9999
        portal:
            open:
                enabled: false
        operator:
            cert-manager:
                namespace: cert-manager
        clusterIssuer:
            selfSigned:
                enabled: false
                name: selfsigned
            CA: []
            #   - name: myca
            #     selfSigned: true
            #     selfSignedCommonName: "my-selfsigned-ca"
            #     # Used to manually define a CA-crt not used when selfSigned is enabled
            #     crt: ""
            #     key: ""
            #     # TODO: Add option to use SCALE CA certs
            ACME:
                - name: cloudflare
                  # Used for both logging in to the DNS provider AND ACME registration
                  email: admin@tinoco.casa
                  server: https://acme-v02.api.letsencrypt.org/directory
                  # Used primarily for the SCALE GUI
                  #     customServer: 'https://acme-staging-v02.api.letsencrypt.org/directory'
                  # Options: HTTP01, cloudflare, route53, akamai, digitalocean, rfc2136, acmedns
                  type: cloudflare
                  # for cloudflare
                  cfapikey: ""
                  cfapitoken: sRwCU6bVB57fZ01dLVGVDp-TM-Pf6o94zqiUbZaI
        #     # for route53
        #     region: ""
        #     accessKeyID: ""
        #     route53SecretAccessKey: ""
        #     # optional for route53
        #     role: ""
        #     # for akamai
        #     serviceConsumerDomain: ""
        #     akclientToken: ""
        #     akclientSecret: ""
        #     akaccessToken: ""
        #     # for digitalocean
        #     doaccessToken: ""
        #     # for rfc2136
        #     nameserver: ""
        #     tsigKeyName: ""
        #     tsigAlgorithm: ""
        #     rfctsigSecret: ""
        #     # for acmedns
        #     name: sd
        #     acmednsHost: asdf
        #     # Pick one of the bellow acmednsConfig
        #     acmednsConfigJson:
        #     acmednsConfig:
        #       - domain: ""
        #         username: ""
        #         password: ""
        #         fulldomain: ""
        #         subdomain: ""
        #         allowFrom: []
        clusterCertificates:
            # Namespaces in which the certificates must be available
            # Accepts comma-separated regex expressions
            # replicationNamespaces: 'ix-.*'
            certificates: []
            # - name: mycert
            #   enabled: true
            #   certificateIssuer: selfsigned
            #   hosts:
            #     - my.domain.com
            #     - '*.my.domain.com'
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1agltukf6ellg2guets9gq4th2nmunc965uflry7fdahtj7ea8uxq8q54ae
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3UEplTlQ3UktPd3hhbnpK
            VVYvWUVXaHRBVXdKWk9XdUdNelRjb1dwOHlvCjF2ZUNTQkFVR3h1Yi9IZUJrbkdI
            ak1KakxjV3N1NWxkRkVqQTgxOHdpVncKLS0tIHVGSGoyclJEZUdad3Y0L3JJYzdz
            YnhZRDdTRGFHNzNYRFR6WGs0RlNpbHMKhG19uSv9NtgFfkMDmhvWrkB923ZcKisk
            3DmSES+j7ifWmh6f5L6kdxEddFh61XQkjT07Imrv+NYd89iQHvDoZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-08T18:59:04Z"
    mac: ENC[AES256_GCM,data:BHN2qs9RPNtMJ5N8R7rW6mTc92GPgED+vq6/57LIvZmlPLKXYrXkp0gQB0VH6enY7kw+VMjGv8UzIrGoB78/LxluZ0bZ2Dnj6vOScYLPn1h3iKcbDNijfodZsSLJjXEgPRwHMQrqdUox0awsrmB2VYejcRD3OnExr5o1t6j/ZaA=,iv:+UcIN7nX87zhMo330MQsLJb0mUqNS+IUZ6VSbYiIric=,tag:k87DoABlJgIIaKkvLfTc0Q==,type:str]
    pgp: []
    encrypted_regex: ((?i)(password))
    version: 3.9.1
