apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: qbittorrent
      version: 22.5.5
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  postRenderers:
  - kustomize:
      patches:
        - target:
            version: v1
            kind: Deployment
            name: qbittorrent
          patch: |
            - op: add
              path: /spec/template/spec/containers/1/resources/limits/truecharts.org~1tun
              value: 1
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:

    TZ: America/Chicago

    credentials:
      cloudflare:
        type: s3
        url: "${S3URL}"
        bucket: "${S3PREFIX}"
        accessKey: "${S3ID}"
        secretKey: "${S3SECRET}"
        encrKey: "${S3ENCR}"

    qbitportforward:
      enabled: true
      QBT_USERNAME: "${QBIT_USER}"
      QBT_PASSWORD: "${QBIT_PASS}"

    addons:
      vpn:
        type: gluetun
        killSwitch: true
        excludedNetworks_IPv4:
          - "10.1.0.0/23"
        env:
          VPN_SERVICE_PROVIDER: "protonvpn"
          VPN_TYPE: "openvpn"
          OPENVPN_USER: "${VPN_USER}+pmp"
          OPENVPN_USER: "${VPN_USER}+pmp"
          SERVER_COUNTRIES: United States
          PORT_FORWARD_ONLY: true
          VPN_PORT_FORWARDING: true
          FIREWALL_INPUT_PORTS: 10095,8000

    ingress:
      main:
        enabled: true
        ingressClassName: internal
        integrations:
          traefik:
            enabled: false
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
        hosts:
          - host: qbittorrent.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix

    persistence:
      config:
        volsync:
          - name: config
            type: restic
            credentials: cloudflare
            dest:
              enabled: true
            src:
              enabled: true
      downloads:
        enabled: true
        existingClaim: downloads-nfs-pvc
        mountPath: "/downloads"

    workload:
      main:
        podSpec:
          containers:
            main:
              securityContext:
                privileged: true
                capabilities:
                  add:
                    - NET_ADMIN
