apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: qbittorrent
      version: 22.5.3
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  postRenderers:
  - kustomize:
      patches:
        - target:
            version: v1
            kind: Deployment
            name: qbittorrent
          patch: |
            - op: add
              path: /spec/template/spec/containers/1/resources/limits/truecharts.org~1tun
              value: 1
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:

    image:
      tag: 5.0@sha256:25ec4934fd35d5cbfc97a9829806b002253565320b39cec2925d9fa0c70dca9e 

    TZ: America/Chicago

    credentials:
      cloudflare:
        type: s3
        url: "${S3URL}"
        bucket: "${S3PREFIX}"
        accessKey: "${S3ID}"
        secretKey: "${S3SECRET}"
        encrKey: "${S3ENCR}"

    addons:
      vpn:
        killSwitch: true
        type: gluetun
        env:
          VPN_SERVICE_PROVIDER: protonvpn
          OPENVPN_USER: zHlRL5gr5LmlqvyA+pmp
          OPENVPN_PASSWORD: jTlI2HG1CRkUpkN7si8saL8NsLp2xewP
          SERVER_COUNTRIES: United States
          PORT_FORWARD_ONLY: true
          VPN_PORT_FORWARDING: true

    ingress:
      main:
        required: true
        enabled: true
        ingressClassName: internal
        hosts:
          - host: qbittorrent.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          certManager:
            enabled: true
            certificateIssuer: tinoco-le-prod

    persistence:
      config:
        volsync:
          - name: config
            type: restic
            credentials: cloudflare
            dest:
              enabled: true
            src:
              enabled: true
      downloads:
        enabled: true
        existingClaim: downloads-nfs-pvc
        mountPath: "/downloads"

    workload:
      main:
        podSpec:
          containers:
            main:
              securityContext:
                privileged: true
                capabilities:
                  add:
                    - NET_ADMIN
