apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: radarr
      version: 24.0.8
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:

    TZ: America/Chicago

    credentials:
      cloudflare:
        type: s3
        url: "${S3URL}"
        bucket: "${S3PREFIX}"
        accessKey: "${S3ID}"
        secretKey: "${S3SECRET}"
        encrKey: "${S3ENCR}"

    persistence:
      config:
        volsync:
          - name: config
            type: restic
            credentials: cloudflare
            dest:
              enabled: true
            src:
              enabled: true
      movies:
        enabled: true
        existingClaim: media-movies-nfs-pvc
        mountPath: "/media/movies"

      downloads:
        enabled: true
        existingClaim: downloads-nfs-pvc
        mountPath: "/downloads"

    ingress:
      main:
        enabled: true
        ingressClassName: internal
        integrations:
          traefik:
            enabled: false
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
        hosts:
          - host: radarr.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix