apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:7XcBrvRV5EmGrYzywSjXaDL8EQlSE+igqaiVAwHmFZwuuyBJBkdrDY9PaUmwL3oyCQODOU7Pgl2og6wJmt19dxI=,iv:3Ws6+EeUgtJ/Jlv2L/TKNn70Pv8KP806RiGC8dA4ZoE=,tag:uK7DxRZdioqU+CP9KNAGcw==,type:comment]
    #ENC[AES256_GCM,data:Q8Tc3f4Dh/Vepjgd4xv5GANX3hbpIefw7YgmD8cXQqtDbwz/MFCEy6gbcwc=,iv:hhUSX0tFoe45BtaZUXSqT4OBY5zo9tN82C3fS0yIe8k=,tag:XINNLFZp9tEvWnM5zNxohA==,type:comment]
    VIP: ENC[AES256_GCM,data:t5I2r8POhrcL,iv:BydKSeNNI6RVs4dzXjHcfcqQGAQ+ilXi7WqS0Ny8fvg=,tag:VeLCNhyea5ozKfUEgEHsoA==,type:str]
    #ENC[AES256_GCM,data:M90gVAQ/RSDwjpmB6wHJ1ixTM3xajye2ii8=,iv:lYmMceQenTprbnfNdVqfHaKn9b2wqSIba/UViFVzIWs=,tag:hLIn3kA5I9W5jvQHmpdgZA==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:UzrERKkM59KW,iv:/SiqFNr7E1cT1izwLCCAKow2LgPUzDMRMZS9naFnIdk=,tag:ZvdR30PsTq5ubPH252CUGQ==,type:str]
    #ENC[AES256_GCM,data:gu9K0ETZegGkSSwCrunj1yKamS5oIdCKcy2DE+I4OUenSg==,iv:lEAACoxuT6cKs7aZW7VPfbVbtqvuroRDnWT0pQDjE7k=,tag:1J/OXuSXNU5Sk/L4ndBnyQ==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:5ccN/205f9A=,iv:lj3Xy2JRPWZ0f2p/xUH2TPdzGw1I0y55xtXfXkwFpHE=,tag:B9mQCs2B4pwLPIhwxi9Fag==,type:str]
    #ENC[AES256_GCM,data:Xg7rHNZJGnSFARmai0aOW2oPe4Uw702XAl3tAP/6yULODMEjeLjG9a1l7iRY9EY=,iv:m8N/47LRNqKS/noeziVtzAvSYUDOSSmtp5Vj0SSZtYA=,tag:BUlQmqSJwayEbRfIT/k0pg==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:ekCkmZyRd/w+Gv5Y+92pHk6K2ACK,iv:6qRTGwCEinoMUPDmABrYWI99zdrRl0eeOmwRGetqnCw=,tag:H9di3uaOyzPQor92IEhSWA==,type:str]
    #ENC[AES256_GCM,data:do4/Eb3L9DQvnRyPwO0gkVy/tYt3HI+eCc/IJSvmYJw9vGBlqROIHGVIIPFeQbsmuaNX94MnhGtu5MaAK9ge+yYVVPkxnZ70ETZ2FINdQIE=,iv:DdTXk6OpcU4IKl7mkBtSoM667u2mOVxybga33Cw7fOU=,tag:P4Uxx77vXw/c6/qI94Jlwg==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:DtLPi6mv3zC3qA==,iv:6t9nOEbEo8mpxlsJgQlcvAJbR1zLhEuFVB8v1s8r5yA=,tag:r2PVj4FIV2LQuHNHhRuJtA==,type:str]
    #ENC[AES256_GCM,data:VRax8qG9YJJETPMb1ZGdZicLH0EX+W18TyAiU8btelrSlFlV7ZtNo9o/ag0aeXkh+2M3zYDX1w5/fQ2Fowd52d1ipxaVAgW2X7qNnk8c8Fwi8gj5GWSc,iv:txibUfAypIjYDodNT/mt/xPubmc8BSz9dyw8J1DNNwg=,tag:04fKkQDnhniHDt6kjHYJjg==,type:comment]
    #ENC[AES256_GCM,data:I4qxp8pi+mEpxypeV5hFKQeoqNHiok2H1u0QWXc9KRAaCnaoMaZ1vuwz8R6a9aun4N9reN1QRaNr4cn4YYA5onStwerTsIx4ppH/JxOOHvqA3r96AoLJAwL+DTfXNm10qfebUwLzXV/A1h3TCzFL/NuJjoaG9mR5NEYpOw==,iv:lv83QoJDZqg9tQywW3A1vjf3Hb6SMns6xECdVdfWhhQ=,tag:hMM6DagrQTBfBWzBfB/ATw==,type:comment]
    #ENC[AES256_GCM,data:D1fdAh1w+m/w+YEcrSUedhuuMvMX5uCgKwnDFtilIW/EEGehgHV0g5o5Ox/v/Iphvm0goOXVUat4hbk/HPFZuezS7hNju0PcIEtN69IJXzQ=,iv:GN4ecUlozaGQ5kbbKyJY2W8meoaImXUbmGCFL+NkrQ0=,tag:IMaeUISWh2+EGfqDnDIYUg==,type:comment]
    #ENC[AES256_GCM,data:ozDne75v3YCc+N88UEEG2BII33pevlXSw4xrTk45yvba67SAPmLa996I5lBNMov/u45uGgtT,iv:UIEOhVpHkcMDHQug4AP1tFI0uQHPD6j0k7q0N++FTZY=,tag:DskjSjgL+Dvv7rGGp3UINw==,type:comment]
    DOMAIN_0: ENC[AES256_GCM,data:jfRG+Evt4CEe8FPC,iv:KaHqjJe7PeOkK0OQPuZepv+WjZ0RbqMUJqu2cXukDZI=,tag:XLJfcV5Suv5sRlxsjbKZYw==,type:str]
    DOMAIN_0_EMAIL: ENC[AES256_GCM,data:d35wPLcDN19Cz7WLwKmFSIg=,iv:ElXLb8F51QYiI7W2GVeWc/N/juw/eMF1kvgsnUbe8wA=,tag:9+rzNqUoAi1UWsKLAgeFQQ==,type:str]
    DOMAIN_0_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:ivE4t2BpSzQLb0w+tC+c1aIMgq06ujpdhgCSdW5+Hrr1wYBt2YNcwg==,iv:5QLXa9DYwrUkdvVK7idDCZ/1Qsq6khGy+LEZM7eJhnY=,tag:akZ6Mf0bRGLCFOX/LP9NSQ==,type:str]
    #ENC[AES256_GCM,data:dp4pw6GQjMdMRAmjCqgowFlryvyOdLDTADhden6Ro3NeD2IY0u9cQUXErYZOwDkLRW5LIhrXJU4=,iv:5KB214TyqZiHfbZC41boOUe0mlyypgaGIMGmQmjbRQw=,tag:D2tPWrncw6LmZ6r8eXzHVA==,type:comment]
    #ENC[AES256_GCM,data:Zc1YXc5gt34uT4RuXJBCY+7DCzwZgXz2kw==,iv:Bo7ZZvGWchXvTLtdg8g7rWfaDtrT/Yqq7l++UiFV1EY=,tag:dj7exau2WvjUEoCEHhgWFA==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:0OC2YMPBCG9JIlJDjDmpMdm/lAeQReqDmBOixphNe6jCZW7jEx98uRRd3ggJeZRQSNNjzH2qbGRI+g==,iv:Is6LzDc21hGLESVQ2IyZm1jG1eZsTh8G0usH+a/OkUs=,tag:q9s0s0rDbKSevIAwEG5VjA==,type:str]
    #ENC[AES256_GCM,data:RluA5c7w66W9nz2oOU9W2XvXsGgZVNSeAvfJjx4sQWCFhJOiswRkP4aVYdOSQuMBEZezy4lg28vrb3rsPIRsHyiXrqHksZY=,iv:bRnRcPzoniCGuDciwpGBKPvrqIEHPBGGGD6bM3urAtE=,tag:eSexKC2asi6+c21V+DOOmA==,type:comment]
    #ENC[AES256_GCM,data:GuZ9NcmAk30SgezkGt6twKr3penxgFR65W4Ek9gXc1zJPZlxf+O0++Tmk+TPrsEwrCA4qA72,iv:smXXssPflIhCbIMx8NzpeE2S80+ibyCAdyjZJpWKCzs=,tag:eQyRhx63rPj5RcK71xITYQ==,type:comment]
    DOCKERHUB_USER: ENC[AES256_GCM,data:l1vPdNsZKVD6gpAF1BE=,iv:vAks9WWwWtcEQoWZyGYmh9krunmDAdzci5U3tC3hmEw=,tag:l1s9udC8+qmn6jNxlF9nMQ==,type:str]
    DOCKERHUB_PASSWORD: ENC[AES256_GCM,data:t6X74PG0u2MQkS31jhfvofuiFwNu859dZ/Cn1ZOd6p4=,iv:O2W/3UYfPsDPeLGGA52lhqzBgKWl5dXPxoHeE1JJLQY=,tag:rOT9kyjz3g6rNmDpYU7N6w==,type:str]
    #ENC[AES256_GCM,data:4jenE26NjWGkubwgzP0=,iv:F6AbXTd2qL9AFbVMu0S5zG7ylO5Iq8O6FetFVPb0uzU=,tag:cskbMmsK+HIwL1NEnwW14Q==,type:comment]
    PODNET: ENC[AES256_GCM,data:sRf6FVjreecW+d6CSQ==,iv:rGHTDNwqApRU1h1ok47SLEpXtqNbnmsU6bfQNQsaJFE=,tag:V2MqbSJXzvodmPJ6vIATXw==,type:str]
    SVCNET: ENC[AES256_GCM,data:tLEwNLK4nef4Tf867A==,iv:vmyb0OMlU1bVOkRYBndkI0ehjoCVZk1cyr20f6l0BEs=,tag:PMZWIibAz518217ASH64oA==,type:str]
    #ENC[AES256_GCM,data:ed744j0TBd8=,iv:Xw0GEVI1q/ntpzi5C4RwbN3Z8PsdUKtlOMHag9BGZMo=,tag:nRikxQpGRdEKvyPilrH0mA==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:LKwwgg27+lwtAg==,iv:BSlgS/plK3HXafKcjNpd4Ky610f18BoBBv8raoL6fVA=,tag:CNELaBnxCVnoJJkXZWsY4Q==,type:str]
    #ENC[AES256_GCM,data:6KeAPEvOcg==,iv:y3sQqhv2AHctw6iH9SgZqDzoVmZ4upV/q+bZ6ToS9P4=,tag:ERGbsIH7MapneuzZzplXvA==,type:comment]
    BLOCKY_IP: ENC[AES256_GCM,data:rT5LB/ubOV26yQ==,iv:8Onx8aZARcSm6HPotIDB0vK+gQklnKYpveBmkVfU4Hc=,tag:4aQtHpAoDiTuPOmlhaycsw==,type:str]
    #ENC[AES256_GCM,data:RmcEIc09GsMllQJmBGtC03w=,iv:j8HH94g+qijuFispo2XtnY3d34nFLhIspQG5Z1AO990=,tag:n55XEopNox9y7V6KaFtmpw==,type:comment]
    S3_access: ENC[AES256_GCM,data:MnhKpqDxcGmKq+Vc9ZPqNzeyqvoxvOVOThHEaYl9JDw=,iv:XqQmi2xaCh2pEgbXzE+lw84LADAoFzp7jn+ZKtu4DI8=,tag:yiNikeSVB98sYUTgPvGc9A==,type:str]
    S3_encr: ENC[AES256_GCM,data:c0Sd6VPCZJx9cHdNALTm46mZrJq79ukTKbv4E8a5S2E=,iv:iQlI1rZIS3OnqSb4+m+qa9ZpYHa0Uo5i5cZ49Haaxug=,tag:blapxlfmQlfLI2bLG4BlJQ==,type:str]
    S3_secret: ENC[AES256_GCM,data:+UEeGzRVuQNPFKylzwO0I1LywEYnMFP97efhSLoG4Z3MINARBK8igwDn89eXova8HuoXzN7fhZ8K/AtFQcx80g==,iv:gZEVtwA/A8wmJ/ZKrv/oX14en0mWRrBvCdLl3TIWMT8=,tag:2N54GMivAmNFFpt7DRI1mw==,type:str]
    S3_url: ENC[AES256_GCM,data:Tc1iQFO3JhjHfwg2cvdODIi5XT+C2r8f8kihDcS55sKAxtEiOrDofoEbzeSoMUdYVUvPrsKhQfIVZjr9SPV+L3g=,iv:ciJwgGnz2pKfD5K/EPT5W8OaedacBPDeYwg7EKWRGlI=,tag:jHjwenZh+nbxCibPkaM9AA==,type:str]
    default_password: ENC[AES256_GCM,data:kNe1PQd4Veel1fM=,iv:Y9Gct1jxG2blWClOetbGrhw7wBn47h97TdPsMX/bJeg=,tag:7QPoqj0Zgcy8/H9zBuDRBg==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:tFVQOA==,iv:NfMnYjeWXpJIaAcVc2qP92MDK3XzWsVYM2dil98rff4=,tag:1XHxUl/0FshmSkB9AGQXvA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1agltukf6ellg2guets9gq4th2nmunc965uflry7fdahtj7ea8uxq8q54ae
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4TzR3M0l6a2xDaGNqeUFX
            bjYrMWhZQmFjbDlxMzhQb0JnTTAxZ25vVUhrClpSR2lXdkd1MWdwa0xEcmRMUWkx
            eWZrWWU4emt4MTJac1VuREdseGZHL1kKLS0tIFJiRDg3cmNUSnJ5ZCtqNzVVN0FC
            WlNncHpxLzM2d3liMjNTd012V3JtZ2cKqqmFXBcnqMNKnEK4LUrS/DnxcJvgV+6D
            0ba3x4Zceg2BVh6CphjdWDyNdL+nwQc3kqqKDa3BHejDkNITzgZt5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-08T19:40:07Z"
    mac: ENC[AES256_GCM,data:hntn7gSFqTreaDWD0k8c1U1UOe2Mp84vxXKp+b99inoZHv5oehOMP2MuBz0Z29x4TZP0z+muucbAxXEUlkmBFT3ZMhCGCkMcT3HfXWbDItZFIb5b7sVBJAh7GV97S3d00nzD+3c2hjOctEM3Yah2BMA6tK1Nss7b4OaeNlwxVSc=,iv:h/SyjfU8gAljBQTnRXSibOZrC/27Bm9uuP5n+SHs7H4=,tag:FZEI1P+jYHJ5W3S1ygoMZg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
