apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:KDT0zE1XuT10EayNEcqX6+5udvRXsp2Oxqqax2GyD/eqm2fD22evmgZOuCvf4BBVGzTJfpilChyd4RfGqhtSDyw=,iv:e8RH+jYb1P3DvB8n4IHfv1T/scmaFpkXDifpFC5Fn/0=,tag:P6rbTsQ9Yp16AKzINi6/kQ==,type:comment]
    #ENC[AES256_GCM,data:oWt33RsgvnyqghO3GTYvvc69zy/agMc1qFitN8Cd6SK7eiqVOu6elrNtAJc=,iv:5QAOSiYvq31iApPRLmWxISuCR/4IE8Gvb3eKBZAJWpI=,tag:5bM9vfd1Ak/1UZWGTaPpXw==,type:comment]
    VIP: ENC[AES256_GCM,data:XRTUGcC68Yfy,iv:EXch5Q98Cpz8/UitVNtZ1Jmy6n9mfi2FAQLrLyKDjF0=,tag:bGFnW2KdYHDhfjKrKikALA==,type:str]
    #ENC[AES256_GCM,data:c1cavuX98rtVYn2OlPEoWnFiH4ey3HjZkJ8=,iv:2SXrOQtz69Va6W5obr+imUIzTegbeYXCRwWPiVOhTgk=,tag:ClJhsWwMKGrHFLEN/q4waw==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:M0GWUNPd0ikm,iv:rqqjFD0psZzOCijjYk5vXMdIAsrZ6eei8Q7MjeQg7Pc=,tag:Tu74w9wWQ2/EyNoBhpHCDw==,type:str]
    #ENC[AES256_GCM,data:aLtj/FXiMdIxgnZlZVY60nNe6AOez92yBh89/4pxH3B1aQ==,iv:94hrOP+QYHrN+Awfgpwbp4yfBXryfHGnEgEjar3ekDc=,tag:Q0GOrcIYeRW4x9JUgU6WMA==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:TYIfGhiLP4A=,iv:PNz8pLlvF0MYHSnr5hzG1wqQ44C26hTufYsoMN3t3G0=,tag:AeTvbzMwRrmywfzebiIp3Q==,type:str]
    #ENC[AES256_GCM,data:bjzKgsJKo5cA9IkVEFz9OQLo7li+cTfGsY8wfb6ZGaXs0NPilc6mf4oHE3ADWm8=,iv:UNGYNmmNR3laX5IqxpLw8eY/VDZc/cutUFBalzL8fFw=,tag:GIAuBjttoqc1Ml6yuKkU1g==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:lbFo39QmwRnlwfVnfH+Y75Vmqhqp,iv:337GWXjtv7SnHhNFM6k2HA3viX9M4k4FM8Q08AYCFnk=,tag:BUhBzzROFIVN111ahcsCKA==,type:str]
    #ENC[AES256_GCM,data:y97J/KAnlR9JEIfNmNe6u2tUDGNtu8JMvO0dhvxm+1oDrGRC6as0lMirWv81i0pwJQdz54IACMFcvib/WA5WEy7Zd7Qqr4jWPeZPz9K74qU=,iv:f/9H/rLru1tTc+bag7ppmqyjGPWVFSSrZvyMPrma2lg=,tag:nwUyjCfLSxDI9D4TF/fJtQ==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:X4Jj4O6q5y4jww==,iv:o7fVDPK/U1uIpec1tOLVwp4tCADC9Vvui6H9UVb336I=,tag:7MG1f3RTnbhGg4raVD58Yg==,type:str]
    #ENC[AES256_GCM,data:ZQjy2VDslCAQd9CPrHhUQAxqTngqyNvaPBpbajO/Mcu/P5HQwi5qS9HgNoM/gdG37quICqdFq3k=,iv:CT57HE8o6z3OowQtZQvGWaeSVrtWWhLOswXrDfUGWTc=,tag:pC1Ff7cuwzc1qCDJp3lQ1w==,type:comment]
    #ENC[AES256_GCM,data:6td2HZAMOcX+oqTQqrmB8t9LtrmodRg1Yw==,iv:/N1eqblUd/7QrJe87GQRVxoeNrEm9Gh9lPliEwTmCws=,tag:aYHpRRcX/rv4NgsVZ3K2Cw==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:APYLV4isvmte9AZFMrkkRWPP8I8RYnLqmcA5wppOP9AlMvjwsKnKkyBWsBJxepccc0Ap4ZbsHxuNtQ==,iv:OlwCbR1+5NImquEXLiPOiK5wwtAHow34eh9ahC9KA0Q=,tag:56ejuX/9oFUOTPVhiOEWBg==,type:str]
    #ENC[AES256_GCM,data:icChm1PVf3bACSGAQ+9fAGz3ZDpBuszeSctaS04FNhp//VDyzGSJBvAqgQaO1ehuc26S7dUpvfplUdv0Y+Wk70MZIFHT7Z8=,iv:rv7ZjH4YkEkNICvQ2WAmkRZvWsZmfmNXw34Jn8DLmAY=,tag:uIm1X8omQkqtirLINJ1R7Q==,type:comment]
    #ENC[AES256_GCM,data:CoZdLfb7sPbsfSw4zf9BbxDiZeT7FS1eoSFkOXOtY08qIaMWCTF8/wWaVgzsl0tp3XqEPT6w,iv:h5SBKH4smQNDjpybBto0X87YPMb8SOuQWWcMl7/xEyg=,tag:FYgR3t8SSepM+GD6t3hnfw==,type:comment]
    DOCKERHUB_USER: ENC[AES256_GCM,data:krUuIu0fOIuRVVtXxWE=,iv:EjQzW4jhGN/O938XQTt/deHqAf6DF6FL0Q/h1M3Oo7Q=,tag:p8X7/L0NJhlUPwpdW5j4ZQ==,type:str]
    DOCKERHUB_PASSWORD: ENC[AES256_GCM,data:etODBSpSGQoV4UJhkloG+TDanAlTRRSkgWyIEFC3kpk=,iv:Wcb844Z1K308ZzcrW6ldo31Zc/7tjYUNBuohg/k0NCc=,tag:Afnu7Z2GEsbBCHKthOshuA==,type:str]
    #ENC[AES256_GCM,data:k44MERVWgNXX5UJUBfw=,iv:ty0VpSJzsf8v9QfgCdETt+i9qz2qaPU+vsmBrH40kj4=,tag:P8d2Zhj4qw+E46g7uIQoKQ==,type:comment]
    PODNET: ENC[AES256_GCM,data:Qpz2oXxmA9P8SVdmwA==,iv:FdLZlqEjHOFxBZqlvEVtSmCtM6bCD3nqZDaE3OiD/sc=,tag:MlMUBytzF/2mqDSYB/BEFg==,type:str]
    SVCNET: ENC[AES256_GCM,data:NLNmuaG2jtNe93M/Yg==,iv:ROTDFq2I9v9dTGgP0REA43eStEXbrde9NUAJfxSjLlI=,tag:EkMTftJR0RYCWECJTFXfpg==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:dUEoBw==,iv:OX3obr3hk4pb3Hss71JvqZ6/Qc7yQ/b7uZ1AdreVXsQ=,tag:YV3W0QSRVTjhgZuW6Vhb0Q==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1agltukf6ellg2guets9gq4th2nmunc965uflry7fdahtj7ea8uxq8q54ae
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5MDc5cGtvTjN0dFBiOFFz
            cnowTWdUZWlqRUpHZ1VUcUlReWdONGxCZHo0CjA3ZEowZHo5MVY2ci83WHlLcGt0
            TkVnaWIwb3E1OFlvcXJyZFRSRVlKaG8KLS0tIGxzc0M1SHpQd1NmNlREQkhFbGUv
            N3JVWFc1Ty9McEM3NUVmUFZZKzNPdmsKaX1Y/BwF4hUQGh3qVAp7l4Cc7pn1nPJE
            4PrzK190vBk3gTEfT9jF4Djbma5IDnR3LYO0DKEhLoTZ0+cRYnQpQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-03T02:06:57Z"
    mac: ENC[AES256_GCM,data:6UaNusK8wYAqP7kwmWN9OURmMcIGE5BVuDuiwNv/65YmfqbfY+gmajD2Z4yNCjpZYuceU3apCoXchWFC912QPzWD35IHJGXS1xLwXHLmNPPlLPPGKHabWn4P/jJXv1Qods9aeKVszpwIfBz/tJDfu9kHEBobJleRA27osUroi64=,iv:raNpv2iTkT1tyfCCXGi0WASZQreuzJ1DxpxtlXd5BBo=,tag:6Emq53Ds8EbHq92Cs1l9LA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
