apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:bedCQEcC/WxDiNiRyuy7yC/fssYEOgJqh6P0nLk4PhexceWXvs9J9csi0rmThdZjiBItcpbXr37sSiS1JNvBXxA=,iv:RTERoXR4sZyebShozkuy4/TTSls2WhQsdagPGs7YDR0=,tag:euszAyrisEr+BUDmRFR5bA==,type:comment]
    #ENC[AES256_GCM,data:NVVF991RBi4GfbK3wVninP174vB09DlgKvWSn5LdVjfvQgdGbEuyv6Pz+dM=,iv:SedBLLc3GCz8zJh9VGWp6wMWKCAfgpfGi+80ypArumE=,tag:1R/18coDM0R+Le5Kg+PJ2g==,type:comment]
    VIP: ENC[AES256_GCM,data:l0mjgWX7ZkjpyfVKUBw=,iv:yzF3j4qGudFcKMq5ey51RLwMQQNs0CZETuaMIgs218k=,tag:gqb++s0LizGITNKXlFQ5qA==,type:str]
    #ENC[AES256_GCM,data:We7bYlEcw5gccylM1acnTSN9oq6gH0Z45Kg=,iv:PEGt1txIaWwWn3zPO3TvzcE8oskfkjIvQrkMQcOyYRI=,tag:fB3iLC9qJc4MOHSOUsBKGQ==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:DHG/Oa/jNFeVO+Tvt0Q=,iv:Mypt8x9f0ywjlnha+JxdENMJ20UD4k0JjXK9zOMvJjQ=,tag:P0NjkzxadPev3Vgi7NkGQQ==,type:str]
    #ENC[AES256_GCM,data:D1T4Xsqb0heGhTn6Sw1tWnexTXpktbJx+OjWpQ8JNya1ng==,iv:JYPvbwj7XikhX7vKKcrBZcBj0vwTomZ8UVJP7Mx/E4U=,tag:T+yqYjlXaOEdbFqFOSLAyQ==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:13WDL8R0ao5MnOgq,iv:KSf00Z791aZCmKrP4nXcWAG9K1ZxM4JGzwWOFrvjqGU=,tag:6m5zppj5QsqBkMA9uXOWLQ==,type:str]
    #ENC[AES256_GCM,data:en/jGsGHv7y1l1yuzBZ1NklhWaLJY7ZyXSuF7b4aSHA8Al+7Rz+H99VYuPgIutg=,iv:67IBL4DYNROqcCcUusb24AlDgnBXN1y5IsqfKh45/KI=,tag:6zT4rf+e/BkBSHWYZ7BRVw==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:zCsTokHyduY3rSlMBEFGT8h7jf6aRrhuNVEw6zc=,iv:HYD1bmJU5tLqyLkup5/BTbka2TnXWgtTZ0ILQGGEhAk=,tag:6rFiSgBErVAqEt+S//Z8WQ==,type:str]
    #ENC[AES256_GCM,data:GY0LW48CLYYpwxa/Pb1mVtOCrWewO6m0+5D1ZK/znL37smQX1N+XVyfdEUh+kOSImrEenbCZsenPul0VrAOOy9bP/7R3HJ9KEeTZZZshIIE=,iv:vvuYPQKmtIlyPxnJ9G4z7IVBV8cC+yBCZKxtYluCx60=,tag:/ZfbEFkjVr8Xesvj6k3RUw==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:5UeuEzxNb4JO20FiSgw=,iv:vS7Jl0Yk7bJ0ngp3C4sIPQjGVw6kuCYXLoSbKuT1MVw=,tag:PEPiHrExLTlPmLGnLhCmTg==,type:str]
    #ENC[AES256_GCM,data:xrNM+lVyDXL9HIOHziUMa5LxFkU4qTmc9fSBa2QrTmTJDT9dzYI0UKStEuZIgK7Gh+3bx+f/6MU=,iv:cxTTp8Eh7ljOP57GyHeyShy0iTqLZFI1qrMQzK5yyrE=,tag:c2Hr8GEYKvmJ5Lx6dzoLOw==,type:comment]
    #ENC[AES256_GCM,data:8dIW7j1Ou3yYhTs02eUJg8QVzPM6HRAl6w==,iv:89f2AQlR7LTnF3Jy2Bl7tVtX3POOSEQoR8UJtSEgOdM=,tag:gkcx0dppNtnRhVYAci++lw==,type:comment]
    GITHUB_REPOSITORY: ""
    #ENC[AES256_GCM,data:KmlfD5ZzE/uj5TWAvN3nMjyXb71zfZKrUg0pVx2rMAz8Lq6goKdRxADoijIAhFjXTZOtnIQUHdNyMoHfMdmpKEquGhPEVzg=,iv:RCW+xl+inAdMMiMXimWLYdWsmGxVDeiqA6+ip01yYEQ=,tag:c4yhtjcVow34TMQdlVccGQ==,type:comment]
    #ENC[AES256_GCM,data:9kBKAcez/iH56/c87u/gYskfXHAl9mr4ZyyCmRIypsxaI0gZ2cSF31v8FBGfHPQ4va9V80Qi,iv:H32NcTPo/uVgOirzrBekR0fp9Q3jJQm7bu2mAJ8MZU8=,tag:1pMeaU18ZfB6mFJAn6OY5Q==,type:comment]
    #ENC[AES256_GCM,data:3X8qODlueWbdQI/gid6RgnFSxu2q5Qq+W0y5PZ0rWZGaNDw=,iv:ocNqpQ9JEXsHP9YNT7f59JHKVcnBcru8e/qPxC60kFw=,tag:KabBzcKvthW5nRiIvwc+VQ==,type:comment]
    #ENC[AES256_GCM,data:zHwAQAbhQgTaP2rqHhzYIe7q9ZCmCgRtEPJzFf3t0oUplhaviWR6,iv:FXE7gjp+DCLi/6MjawcH2uSqi/LbtnwB/f/7VtVaWtY=,tag:xVckNbX+E/XebsvaA8GxdQ==,type:comment]
    #ENC[AES256_GCM,data:1TLNzb1gcgAvJFz4XKk=,iv:5a/ZThxYk5+jDNjCP/oklrLBKfLcaArGPiaBxrXNBOI=,tag:yIVb16zz/32mQoPIezJq4Q==,type:comment]
    PODNET: ENC[AES256_GCM,data:yGuiTEJORQ+B1O0Zow==,iv:/mTGnk87RO6y/DMc9v1uB9CHfRp9ivydtxZvMxZQxXo=,tag:Vum1kicr7JSkHGgrM4xwdA==,type:str]
    SVCNET: ENC[AES256_GCM,data:+8OZHYQocg0Z9A2+6g==,iv:XYpxQFICkvxCHKBzXBGJ+RCai3s/k3cdjKLNpYLMjNo=,tag:83I73KSs9rpeRSZL/l4aHg==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:3ztfOg==,iv:uUHdFO6oPwLQaqX4xUlK4TXQHCvSC2p+/CGHKeU3FeM=,tag:e7zK1VQa3KVQ4f8f2iB+pQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1agltukf6ellg2guets9gq4th2nmunc965uflry7fdahtj7ea8uxq8q54ae
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyNjBJYXBvclIyL2NxVysx
            QTNLQzB6L0g4bHFERWtWS1ZFaThKdWNZWFV3CjhQbDBjZG5GTlZXbUxNNEttdFpM
            R3c3QU9FTTFvYnJQVmwzZjdzSkJqV0EKLS0tIFJvS052M05SNXJMZVcrbTRxRFJ4
            MENZUkVYeVRwM0R4dTNhN3hkYk1oTzgKCRzoKrCV/aVgXre8JZZ8XbHn3ZGuK6Wp
            mZc3j7FNlpq7MmP3iFdDWigvpoi9+WQFkkiPOgHslywNyDTnOmplkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-01T22:43:27Z"
    mac: ENC[AES256_GCM,data:bMFcqaNeNAT3UX6VYPxE2D2bTU7J2MEqyD4Una/vF5Fu7sPmYrblM2pp/DGoObAf+YW6Onc4tiEv3QUzU5JK1LmHifzyEoDPpt3F4zENud4y/1V8lEHvSCkgFpeplJ+iuAbBHtOtrTJCa7rUfHQsqv4+gJof5ohlbppwwxl4sfg=,iv:IJjgmINl/e+EfqAYwBl5TRVFTkkU0neEPBTy3djxu3U=,tag:kHEd6Mej/OL8UAiDItV8pg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
