apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:Baqe0bKOB6ZtRJ/Xk+KClBWAqmxrbTxyju9T4Z7HwGcSCgKA6lc6Lsfse/b1mohunvHAR9VE9GasRmrdVgJqlYA=,iv:sAaBlBcNmYEsFWjFgSNteRhFcqoE2LCxlHyCiJA3nWo=,tag:Vcp0Zziq0YRX/3VpW/j5Ww==,type:comment]
    #ENC[AES256_GCM,data:FgU7M68Ig0qHY7U0Ooz8PHqJHtyEfb2e3v7+28yiRVbGU3UX74tOEI6ftTk=,iv:ihH5XTFycnesDEou4naGTboO00iWM8ii3HnyKhm9w10=,tag:UXf2X7zmddV243isVWo7Dw==,type:comment]
    VIP: ENC[AES256_GCM,data:9p61ftgsbceC,iv:IouNnh66lu3L27zbO95S4TKph0kmwjqxzGAf+i2H1fw=,tag:WXxjsCJ4BgkVMPVPucNGHg==,type:str]
    #ENC[AES256_GCM,data:mG/4u8o4ff2V0ecEVQUtvpozj2q/XAiIzoY=,iv:B5GkFyOkPft5OkizlzrD34yu0qsDTNwBR4rYVBPCl24=,tag:gKwrDPInwNaH+YJyUoInJA==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:aNruphMQm9Vg,iv:5xTti8DidbnKVFcGnCLWwrXyF4VJJx/e5V4Mcf+VOWc=,tag:wHB5Bt8pu2c43ipdfrA55A==,type:str]
    #ENC[AES256_GCM,data:PRDU6H401fdL4QEjf9tDZpttqSumY6u3DGu57WtRLvSRuw==,iv:YBNQuqIhflHe1g7+dfaGFKK6837Cp2r4AL5NwAwV5bs=,tag:5B1bjSJUd0OS49eNxzOnog==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:rqBG7ijBhqg=,iv:uukfGRQprHArz5e489v1QAhaYzxMTUHtZg1Vm/f2wF4=,tag:lEwcGmihSds3DYDuoBnN4A==,type:str]
    #ENC[AES256_GCM,data:pXPpzM1arIQgEQTZESfoe0aSGUrs5x7CRvOV1kn4IK+z2QBVQ5H/4wBjGbtEXAw=,iv:QNo6GENdvdGCHU8zSdZPioFBQu3GRws8MaTI7VcFgjI=,tag:J4/yoQBSxGHn0Z3DWH3lYg==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:5hXKkdG3QxzWI+sVBegNLrCJBDFE,iv:tLc782wLTN/jFBXu/jYoyt6tBCVvrizHyNPvJg9kyyU=,tag:GxwYdU5lg+CU2lQzqRQ+Cg==,type:str]
    #ENC[AES256_GCM,data:8/Fmfl8Sifbgb/X2+f8CEPMx82bNG+EbuNh+EvE6WlGI3s8PHpfqhVebbs1lb04ZB/0Txj0L+eVeNHazMAyeeaNI06Cpzjsy9dW1/+DptJg=,iv:gqcOuuMZrppt8cTrrPQeKc+wi5W9cBa5WWQxCPFsDqo=,tag:eIMS0O6bYanPtOrR+dtheQ==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:TkSaf72ufgpY9g==,iv:jOw74+eDIMfLv3RIf9dpf77MXKzsgmvRDS8YWXCngPg=,tag:yQz95aUDcLMEZ4oEV6uoVQ==,type:str]
    #ENC[AES256_GCM,data:pgJZ44k9vg6PFJENayzQqoO4V+V67GsrYep9bLq41qh8kcDnKYbuLWUNR+GjbeREAemt3+vnW5w=,iv:Zsczx6uq2vmTrxv7xaABd9nrJU8kvB2gmeeXEDKtlaE=,tag:BD/TQuLRuPqYOf9BNQn0Tw==,type:comment]
    #ENC[AES256_GCM,data:LmnE13cJJuiRUUqEwt6xccJiD750I3tW0A==,iv:CWl84wHeKcff0tnlenn4ou7fEzp9sjUqOtZbN5/kYi0=,tag:DX+D7OL26HXpaX23CQKnGg==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:0kjHKjPJu0KwZrFTQjeZLpDv3UuxulEsKqvlAeLCy4/J87dqUX8TiL7UPd9D5wHVrUZgJGH3t1ujOg==,iv:4riqfK3jehNCG5zJmyVNbywS69uzSfuSI9YmVF927SU=,tag:GQ2k0T6fU5FPUAtqmdMXQQ==,type:str]
    #ENC[AES256_GCM,data:vWoUr4i0AkwOh1eKjrIop04g91RE96/J5p5zAamrbMNKbInoIYU7cR/PxoWE3CO2ZuUTrna8WUmeQCzJ+5B1vR1fc8pqzjg=,iv:V3jV7HliXTfBqhlQSjIfDhnv0E04wxaI4dWQsNH3VFQ=,tag:iAJuUaEEQSxOf/AGa7WuBg==,type:comment]
    #ENC[AES256_GCM,data:TX6gdrrC92lkO1dVRCu3MJ4Mkw2JW60Pvsh/Ms92Knt7qunvoeV6zLDhmJTs9I04zaeUOb2W,iv:96vcgGtPktWYII6fKKzqNIOf9IL94MTiOntv9515srA=,tag:b7s2/9PfxNLD1UPG6pQutw==,type:comment]
    DOCKERHUB_USER: ENC[AES256_GCM,data:Dq58P+GRWj+lLzh4tx0=,iv:bKEm+20RkHjzLjwEjBoM9iXEV1QqcR3TrLUdbWnlGsQ=,tag:PAUVg5ryQ4yQa7k1Ak2QcQ==,type:str]
    DOCKERHUB_PASSWORD: ENC[AES256_GCM,data:DpvXgq9dFQKWxutV3TJWl8bxMH2mSJGaK3yJ6sVfcE8=,iv:Nh1bNGgvtyKu9EY4EX8BfkwEPfLe4u6WmEeDX1rwB70=,tag:bEc/GzLlYGEBcWAKzw6Aew==,type:str]
    #ENC[AES256_GCM,data:Qz9ZRfw5kkOQIbZ1Y18=,iv:Xz4xL0Xd3OEHDtWkOR0gD1bvzZs6AcaKg/IRtA0rZ5g=,tag:xB2rm1JzDmwNG7saFe6Zbg==,type:comment]
    PODNET: ENC[AES256_GCM,data:uKaVBVcslUfCDhE6Iw==,iv:ZAi+94y6/NukYafdiUQ/A9FtcKqRwCTHKXPRlq5172Q=,tag:iTm9l/HTSM2GHuU/jEnUwA==,type:str]
    SVCNET: ENC[AES256_GCM,data:LGlqPfdi7TxeZw4/7A==,iv:k5g5s5BH+ZdvZCQyJhKILdV69hxt3aHIrJaAdCZoHgo=,tag:x7diQ6nvqU2kimtd0J+5rQ==,type:str]
    #ENC[AES256_GCM,data:LfFBmzHIZ2vuZOan4+0tup8=,iv:d9MnXu0lIcwMqsD7PHn2q845OoR9OaecW2Jyh/yQpWo=,tag:a2t+GZuq16NQTIRqxGUsCw==,type:comment]
    S3_access: ENC[AES256_GCM,data:lovf7CF1v6RgxDtxmg7yVqJ0uI8THeY0RevSgLyppq8=,iv:DaTaryGzIpGvbTqCbbB0x1c6dNelHCRDxnXw3/3Tz9g=,tag:t2VcLuQGuYGTNacL6/uOSg==,type:str]
    S3_encr: ENC[AES256_GCM,data:Q7r2j8hLmVTz8k4cXnLFz+CGOyeU/d1E46Ep+56iA6U=,iv:xvXWHsHb3yQCQzGGzk/YzYJUShdYNiBr15/GZgsjzT4=,tag:fiprd1ARCQHDv0clgoCTlQ==,type:str]
    S3_secret: ENC[AES256_GCM,data:Kyt6DEfjyOknuwwEhDy7oi8CUMLWzDFjnJQUuYRxkQfDMi8Gp57K2ebH47UUJCNr94gWH9RCT91YO77yEjyiqQ==,iv:F3q/5lSXmv/1VB9HHNzUKAdSdJExkwOCyVGdbQ+bAFI=,tag:SKqupCVFpp2GpzZjdN2JKg==,type:str]
    S3_url: ENC[AES256_GCM,data:UWCxiYZNhVXoPCdWoyJ8CIs68euOcO/d1WCVdZ+2TM71ZNRkN+JvF+xkgnqcBme1zwFRcL/6c5FD3oj13myZSvE=,iv:hHfljzPRwGM3KbLxEtfzgPo0nr8CaJYrO1Z8M6igXrk=,tag:OP5aj2NiRHK55xpVTG4/BQ==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:C7YqOQ==,iv:ZxqXgCfPXcLw0PCiH3gOWgkCThBKS4UexJycVQ8S8kY=,tag:OdtHmOhRTCLotqMokJwMWA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1agltukf6ellg2guets9gq4th2nmunc965uflry7fdahtj7ea8uxq8q54ae
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZS01rdkFnQkIwZ3FObWEz
            Ujh0TXk0Q1d5MzdZN2VpeE1LNG56MVg5RVdRCnRiMkJ5UUV3OGZXdGlMajBITkVS
            M29hbmFzUlU5V05DSDVCZWt2dGlFMEUKLS0tIFdRbGltQXZONHZQS3RwOHp4VytR
            RFQyZDlZVjJwN1J2WVZPZVF5N2FGRmMKFGaXntsWllHk5h8yQJwusgiAxtXoAA62
            C/36J/a3OpJxowujtF4sdsxnmakePup2pv8RFrfHOOfI/7+3F56ZLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-03T22:38:15Z"
    mac: ENC[AES256_GCM,data:S0jStY7ByYEEqkN407wY2V/QTWjUNkO7tmh9vyT4QvBNiFye2W8HKZmLnF4bqleRs28iu6nxAGo/rsBBOkcQLkD5dbpT5JMtCN77nBghwm0rJH2HekUurzjHoSNmR7h77nIi2aSwssRSCi7e2KPz2uvDH3nXBEnV5Vh9TiIOM8s=,iv:VL7EQXAXLM2E1uFLLJA1FFBt2QkrvL9LhTvZr/XMso4=,tag:S90JNMegTeHv8QNmEbB5/A==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
