apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:xjdpuMwJfYWbRPN0Ux1/5o+yek+el8hcIlAtWWV2H969I1FucrChBW4YhWvF3WURvhtAcf22zZEbq374KNeygHA=,iv:DVAq9tw/DiJcJFkZP/sXFleh/ZSO7ok+TdCli+maN00=,tag:CVkSb5GQIIhsnbXDZn7jmA==,type:comment]
    #ENC[AES256_GCM,data:VJ6AK4h9czp573QNYOroMNowoeolBuPcuFnoWx7CHvnQ0W8VTUGfZAUNP3U=,iv:kN5bMQgiVBZhA1OSLdmHNZy4qI6mxQ+K7qvwQhjY7T4=,tag:idXRWdrn5HIYwBZQXMbjnA==,type:comment]
    VIP: ENC[AES256_GCM,data:YfF1/+ZcUCfK,iv:SpR/lLkSquowREiscgETLs2kxl5bV/eY9J7R7VdtI28=,tag:yYnIKiJfT3s91NZSbnoy8g==,type:str]
    #ENC[AES256_GCM,data:m+Ux9FKqg6J6tY4Jm0YxTHxLUW/E/7jWor8=,iv:PnodsuzVj6clSDPrCOmS3pRi3GLgQK+Xce6BB8IPHHQ=,tag:QQxAA1VQKnQc4R7xK/r14A==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:sp7WZSAQ1187,iv:y+bELx800WATJY9og6B2uNAEIKN4Yr49OxatNVsCqrc=,tag:byjKYs787QCT4BdGrB0CNA==,type:str]
    #ENC[AES256_GCM,data:g54Tv347/i4BwrB+/YfRw1KZt4Ywmfb5EheWIWvwqeA6hw==,iv:7Uy+Of4yEtDqVz9jai96ANxb3S6EvnjJecGcAcba+EE=,tag:74Sx5cLQvLqFxejwiYFlxA==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:6mM3NaBwyJQ=,iv:ZTlnGq9mtmQOdFPoEUr/G3vsFnC/A7DEKRGRdWq1sa0=,tag:cO1wM7hF2E15dMue20ZAxw==,type:str]
    #ENC[AES256_GCM,data:iQsb5oZHAEouWr5pLv18rxuHzo44P2GetCXwyTqtk7J2C3QxgxWkqsnjOSLAoyw=,iv:7MFSzXgcJ/LWJV0CCyZQ6ZdVZYrXXCYAM2Nzno4BCGE=,tag:ReSP8zZNJQKDRYL2HH/WVQ==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:vpx/IfAiU0vJWQyVlm2unY/LYBOp,iv:t/lmitTBB9nypgB0ncEPZjXrhx0zXzVz3sOxNn2NpGQ=,tag:z08mq/doSRazLAk7F736yg==,type:str]
    #ENC[AES256_GCM,data:m7q7eyxDHqH0DLYS46zYH6Wg/DHxfrnK9G4LfA2T/ZrLn0I48wGsNG0+KlBegfQ6PUKotNx8PovAc0sfj4ZwScBBr+A5RHCAqB9P0lOvwxM=,iv:0D4wLac+12JV/26hFljfRJvBfbbRaA4c+4+0h/ULfxE=,tag:v+JNqISoXv4gX/DEkk8hUw==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:JkhH7wmcD2CM/A==,iv:5gpLPj4x9K0fDHhLa5df07ZC1C8ew3G5FkUMyzjni0A=,tag:a2U1s3+oYRzsD8T4G8Rbfw==,type:str]
    #ENC[AES256_GCM,data:PE5wqxFZheo6ZIAgIBGPzgLjH5CGAGmkRuSnzzCth3GVft7bS3JK4A87OHTkXyaC9qMyVmNLEvEwQyvV7srpbvOi/Zekwicvl/DvRhUt7PZx4CmJQYoC,iv:oV5v4+nagOYl8geDPVgunw9GrQxbVqDNQrrLg5MFSZI=,tag:UEUHGc93POB+4NX4hnpP8A==,type:comment]
    #ENC[AES256_GCM,data:yWD3oLRv8g3kgks5HRU7FHF4jlrOjKPJUAjpp80tHesWE5VEtF9AD0Bdw52O9O99sgMhnBqNEk0con/QomrJOs8ZvP0DBayxJh0IArvIDnwEFKAhBtxgICMJ6LyNCsXQCJ0YEmOJLGoxN78Qia3QxxX86c8i2kfzMT+WXQ==,iv:DFEiIic71gW+BKlzAfLKIxplpSs5yGgGd8xh2/hOtjA=,tag:9wlBEE/rpVCTsy6xn+qYnw==,type:comment]
    #ENC[AES256_GCM,data:AKu68inNgQQDv1Q4mKgwr+KtkYS+Nzxu72rUtXxGaQ5osqpE+B0q29ITcsqtE/LQxoobNmbPLLdj1ExYbinmIvCdBniye0Q7N191akKDeiw=,iv:5cQVvyGRk8qfTqErymWpb2s1Xk2WgNNPnFzc7uxwcM0=,tag:iorpZ6OF0VW9VaAZXFow5w==,type:comment]
    #ENC[AES256_GCM,data:slitovuOchiabM1IIPe5UQCkMtv4Fv+WIMBc4zQKQgMDoA3Z3asRrRWr/kzNwFAlb67GQVST,iv:XHEsb+KSEgCFBz3eNyHYoy8ujKYM6ArMWZhgoVJwA0Y=,tag:eWZSbUSyMSw5pVTD2vHICw==,type:comment]
    DOMAIN_0: ENC[AES256_GCM,data:u2LAh02J9jWVF08v,iv:n2Do2KOLk8FpMtFJvaHvKSazExdjBF9UY6vR5kzu+2A=,tag:JM6LquR4wd1D3BtXmrgdOA==,type:str]
    DOMAIN_0_EMAIL: ENC[AES256_GCM,data:PVqOYHPVSyVjr8mTfN8avgo=,iv:MBw5XgOuZYQ+8Sl101kJvKj/ybB6xd68coVLmIdGf+o=,tag:IsJx9k0Yea2K2vvZUe2SxA==,type:str]
    DOMAIN_0_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:LGliTkZe+aLVg2Ike5kTMhRssVHpD0GORINhUrgZTbTi5wNeJ9bYKA==,iv:9crAd15EOC11r6Bj/3lJRv/SaptWJrUa7gW3MP8czDQ=,tag:tazvK/o7TSGxyq42nKMiog==,type:str]
    #ENC[AES256_GCM,data:dpwShktdQDQp8BwtMe/asXtnyp/lZQdpeZDjj/VYmD5WGnDgR0FXsMEA6jsjqlYGrhrXb6meNes=,iv:HM8uSf8Zhe+7DYA38P/7x09t/ESQEFwYXdZktnJNY44=,tag:g5r3AmwhwEeOFnkap4JXiw==,type:comment]
    #ENC[AES256_GCM,data:v4Te0z5SdSNibocikFN9rULUUOjbNJhs9A==,iv:2KD/r1sOkXJKzwDpkRV9WCUwxSL5By6zD4G/Mx1B3hs=,tag:p8xWRSh31CkMHjH5Gqxv1w==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:3zGY0ZrQAo4SxX/io/vdtisZunbpRQHBk0FE5lgLpPZfatse3HqYH4xLgArDMy9q9DJn3ggX/p+CPQ==,iv:8SkE0TWqVO2bYkrt6urZP0fi45H5UlR6p5lmuIs2Luo=,tag:5TXYgP+In15aIpWDx3Z+sg==,type:str]
    #ENC[AES256_GCM,data:CnhfbY4Zs0P+pqHMcDzKbriAKECzPeVHM901yov72H2ENy9+AGA4k9dVGWR4Mfv33DCxqcuQsA7PP3gPySDwn2nZHTwVO9Y=,iv:9YtGjWymRdCMxJFXeSvC5CgESlTu4C/yoZUKnHpBELA=,tag:jRYAEG+JUVq6UDmwiUviow==,type:comment]
    #ENC[AES256_GCM,data:NilEIEklJ5i54y6TSjdEjSNIpcGDOqB0cSy9m47JDu50Mi7O7fHQFqkH1eejjKwFPc0QouVL,iv:yKJ+BkqG3LfhIGUAzDqKzgHGDQ0L7HCSkcvrEPnUlh8=,tag:KHnoYCHsI8PfYaRevGzQEg==,type:comment]
    DOCKERHUB_USER: ENC[AES256_GCM,data:rt88W5onqVqKauKZIsQ=,iv:R8NU27cfByrR6Mt7aTCrdQbO/pw/dgaj+i/AXooiR4A=,tag:hQ8+aKJ0I4ovTftuFM+Wkg==,type:str]
    DOCKERHUB_PASSWORD: ENC[AES256_GCM,data:SWSe7a60cr22invngN2lR4vWGXShaXNht+LEhPvt8Ds=,iv:/KIRV+gA4Qwfpr0Nh33tOmHFJhpT7dQ/7llW4GqQ3Xw=,tag:/h/XzlLyK7AoUhGDb8h1jw==,type:str]
    #ENC[AES256_GCM,data:nniSBntNp2HmCb1XkEE=,iv:4BVvkumMeEsa4uYa6r7REHo3HsUTCDWjcPfCNjHCKfE=,tag:qlT5lPUv1EOgBsXxS9do3Q==,type:comment]
    PODNET: ENC[AES256_GCM,data:YdbrMG385xhnA2k8ew==,iv:RVwlrt5LuB6U6yKZCnrHtk5S04Y4y83yn0khrqx1snw=,tag:XubXbEQo7LIEFzJkdZHXMQ==,type:str]
    SVCNET: ENC[AES256_GCM,data:oMvumDNF/RMtubldlA==,iv:2I93Og2fCiJRsLVzSwYAJlSBsydsOQcZw4uVQYEvIRI=,tag:IAzrvT9SQhK1H9T5cJ03HQ==,type:str]
    #ENC[AES256_GCM,data:sX+bfPHQyHA=,iv:iSb2cacJIetk/fRWmxtv106e7KC+RlJRwwx7ereBzqk=,tag:pPDZXsxlDszcG53s/byKgw==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:9yXPbN/x6HkDpQ==,iv:/jifLx01eqLd/EO/RZaH06G2Nx95rqSzyvnukGrroIw=,tag:IMPN+PKZS7DWhmPp8jZqFA==,type:str]
    #ENC[AES256_GCM,data:vbzmINaQjA==,iv:blNgFocPn2df97V+TlyaVQ+c6EV7st8AyL5nnhJSWKg=,tag:1GlmXf8Bk2W6AQBHtQfH1Q==,type:comment]
    BLOCKY_IP: ENC[AES256_GCM,data:0SYBU3vlDus08Q==,iv:6aTvvx5NVavSi/tISQSoJLH9sCWRIzB2fIrDYNK+uYQ=,tag:HVNGgDLIrmMiBcJSypNzZA==,type:str]
    #ENC[AES256_GCM,data:k9FBEpfeEkU12HbyMITyJBw=,iv:md3sWN3t3GKXw7UZXaaE8e/mmr5WHkludPDaORW1UIw=,tag:yvLBES2uHaNgKS4osflAYA==,type:comment]
    S3_access: ENC[AES256_GCM,data:KGGCTzOlfsR/GJ+2pN0XtcZ31yPDct1j74+JtBv5R8Q=,iv:zEIgLc0HtvEkdbQd0OqoeezTptQL3NfL8NpgoiSzmlQ=,tag:MLR9IOnhS2l6nLxhbT2ccw==,type:str]
    S3_encr: ENC[AES256_GCM,data:WDUZTpKQ86eXjKMNfeCKYVPlRXyI1P0WDuzd2PpoQGs=,iv:db540LPOj6SVqv74qpGmIEVbDAAb6663hAkvHpRcqco=,tag:eRrutvRWPB7CcaWudVn9Bg==,type:str]
    S3_secret: ENC[AES256_GCM,data:7evlXvzme54SZ0X83326jZ2SEiGVvuyBJ8NJlteLHEJe5oD6OUusRrahHOBNIBw5Om9HcL8Cf2W+EQ8o22ySGQ==,iv:sqsKK9BQwLb79npmFXEMUNMhRBYm7Ivf4cHokHQfL9M=,tag:i8aJt7RLLryTiV/Yl9AdzQ==,type:str]
    S3_url: ENC[AES256_GCM,data:iYa4ZfkWwtSwXiw+MxNt3bv/cVgoNaE6Y30WTsWRupaMYpFnyYBGw8BZ0WLy5rcQh6GN/4SO1i1vh5Y5GT4GiEM=,iv:QcUnZCHYkbtcLOW+UNlQOLrpcfFc2Q0qTJzZpoYcm8w=,tag:gSxAZ9bM6JoRARBA4rBDZw==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:FNcnsg==,iv:VHUL8mZl1EcbgdxUu8pBBjC2WtkQnOULWFT4UL4/RIk=,tag:7LJ13EOw5PUB2o4InuX9Cw==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1agltukf6ellg2guets9gq4th2nmunc965uflry7fdahtj7ea8uxq8q54ae
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuY3o2c3BrY0FnTDM1QjEv
            akUyNy9kUExYaXdtcE05Z09aU3ZHVGNuQ2lVCjVJaU9HeVBablk5NmlnRU1qSmwx
            V3lxQkRuQVRHbGtmT3N3SGJlOXVPdnMKLS0tIFJzMUhDWnYwRXZ0bEVkRnhDMS83
            RTBrU3VtM3hNWjZNQUl4K1lrRTlsbHcKjVgp8l8H5UL1LO7kMmDwMD3jUUexDqWA
            wAnf/LzzFJGITey0oqb9Mfe5U13Y4pushId+5JIrtYaAC1PNNz3fGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-08T19:34:52Z"
    mac: ENC[AES256_GCM,data:XfMf9/eqiOT3/5FZFR7VdxdcTOUSN4dP6hc+qPUm33OMleVZPLEhL3xD/utCRO6TQJmk6SsaGTlcMYF9P0hAB/o8ef/R0m1HbCuDJEv27pC57gv3Ugk+mA28hzq0DH7NN2eZ33YpgvaFI8MnY4fUSO2B9rrGYNOPw9eoAfYoaXg=,iv:5HsEExsxNHazcL6iqlU6nJTMm1dAi7S6bxKQgsHEubo=,tag:/OR3SEe+67T0AUB8OERiKw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
