apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:LTS5Ek+TJ3nXRLuTe4RXoD6La9Qlhx0r7681b2pumV9UnAuoKbGMy6A20cK/+B3MDXGIvLW2YwD6ybySHJ/iapw=,iv:tHBMYeEGfpV6aRZrZ2ZiFqgTioNwwrdLfSvmsVWqiOc=,tag:qJlj9DkRJAMEERxNbvc6Dw==,type:comment]
    #ENC[AES256_GCM,data:P+gKThNgFMoNGV+vvkfpifCGmb6EBY0eaqmZTB5meToLPlHAhdwmP1CrkNE=,iv:hQC394YzrYGsHYJRmBIDwu1jI323r2Dw5X2IRkwM+v8=,tag:auKGVbTDvgnAuykgzVBKJg==,type:comment]
    VIP: ENC[AES256_GCM,data:iDSmA+PVol0C,iv:+06PRO1aIf8SEurUz9fA+ynqtqZCEAgsnN0qeHKv/lo=,tag:qbIfnxFvQ6WmNmzpzRiJHg==,type:str]
    #ENC[AES256_GCM,data:PTLQZx+YNd5rILl9sHijpY1knSnR9THTvRM=,iv:WtBHVPb6SRS5brl3MrucITQhTdFKJCTOIj2v0WFoh94=,tag:oiBhIUSk4Jk3gNze/JmjVA==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:7/pP8F/ZQnzC,iv:k/NXhu12VuRdGHwMgreVcnUlCmDHmFuc642dV9EDPwg=,tag:eDxJmCS2WAZfkg8Ru406BA==,type:str]
    #ENC[AES256_GCM,data:Stjxf7nTLLzFGAN/1o+Ny/BzgFo9WTtCwlrnf/qD/fu4pA==,iv:kXfOCg4b9wORyYI6TmyMjDFmKO8x2p1Am5I4AHy7ZH4=,tag:SKYGCBoJf7o5w4NfYsOeMg==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:u1YLCR0Oilc=,iv:0bKwzvUKlJgP/8Ebnf62ndHxDS6RiqqG+LNnPowLpbU=,tag:PVSCFOPlo2jRVnG1SurMzg==,type:str]
    #ENC[AES256_GCM,data:3faujY9H7lwKaUSV85foWPL+Zmq95F3PrCFVWxksp73BVEiztgE5cOcHzhgPoPg=,iv:U7PgPqGZw9pDME+KAUi9XvJu/hJ/xPz6g5JIfw6Mh/Q=,tag:aq0GPM6TcjWiQ1mN9I5Cng==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:rFtAVwm3Nb5MosbmVVYU3+uDLM9A,iv:2/V2pmuFKuZDTovzRZiAla0qd70pdwyHFbTpJ6vuvNo=,tag:6TIgXdaAIrt+IUnSL3M5aQ==,type:str]
    #ENC[AES256_GCM,data:w+Dp+ikBU6T6jVbQud/XiiOF2476zwCLmQzKEQCAtKSdAX68Qv8C51nyzpRZLDTGLhT80yxY6NYazh+I6OWGPMoJw1d8pX+HTWtJRkgMcVo=,iv:U0n6GqYnjQDJn59cu89XjnnrUm31Hd+Hr6k/fFB2d5Q=,tag:d4Btqb1knJ8MsmVyzEhEag==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:vsV3s9vzAmho8w==,iv:zpm8d1flqyz7LCVPZIz/zZsm9JCMYg9rK1TsdaoO6n4=,tag:+LAsG3vVs/1xpLgHMEk+4Q==,type:str]
    #ENC[AES256_GCM,data:aD9z2wuvC8WWAhXgztQLmLVRbzCt7MN4CeDmZ2DfVkVNECUDR/Fz26MoOVSU4LzWsGV7GMwSmy0=,iv:VlsHwUxHLISZW9gU5d10idfB/wa++Qsh65+6JyMMtKI=,tag:ZlziCgDJkp6nd//SuquNcw==,type:comment]
    #ENC[AES256_GCM,data:nEV8NdCqqG1AiJICqpcXq//fSpwhISXwKw==,iv:BIz+LNnG2sUndiqVtCGOS76UBpXAnVzoVpvICGLXXkk=,tag:8TfCviwoObMibBEhQa5G0g==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:4p9OZdCvP/4l5iM5EEvpC/jg+BDnFvVbjGzEOa1Ed34MkJPhaWbK7Gck6DswTzlMt5qrILvZGwJcmA==,iv:ThQGNXBais8HjsbAnGtzzT6ftgfqRsFjoGEKtoAQoZA=,tag:VusnS1MBhHNdKBf1sId/ww==,type:str]
    #ENC[AES256_GCM,data:R396Zr+J0zbc7NUdaiuyI736UeFsjhkXBIqFt8TNq4GQz3u5styYc0QGIC7ZOtAfFKjwgH4Sc15QnneyBmjqQSe1L3u15n8=,iv:7aAfpVhSC4+cXE8D1e0KQnM8rSkNDNKqyDSaXGu/Q+U=,tag:yozc/UxbbeRzs6SxnLmXkw==,type:comment]
    #ENC[AES256_GCM,data:+OY6cMfrj5OMTvGysQx9TKtKOiuYU/AGPXcQWR9eqHW2XDlu0QVHm1yh/DmVGf+/9Hkabuz2,iv:9EN5YAfd2yqsOAjXQR9L7S3JVffOq8M0BWHSmEFyuoE=,tag:GS//NbBOzqJELWSPGv7omQ==,type:comment]
    DOCKERHUB_USER: ENC[AES256_GCM,data:hgg8PwYz7aMgTMhX0gQ=,iv:3SDEjfYF37CSOCqnwI97ajePX+S4kcUaYnrk+27kGLc=,tag:ZDWWQpYH7F3JnW5dvNpUtA==,type:str]
    DOCKERHUB_PASSWORD: ENC[AES256_GCM,data:BzoO6KNQ28X04iY4PUN67ecXXX7LyKwKBqjX7Gvsc4E=,iv:BDafjU7uzwUh8Ak8o1LQJlGgpCRuthiYLeD0y53aZqI=,tag:Crf33Yt/QAtL2xEQPuwibg==,type:str]
    #ENC[AES256_GCM,data:4gnbVNUACKB4wD/NCEQ=,iv:ta155s45/OrFYLVYvfh22mS2qeGcOPgcXgFoyTkF8ro=,tag:fnxBKLjWl4b6Ry+7Apxf/g==,type:comment]
    PODNET: ENC[AES256_GCM,data:HTiajyWq4In2n2OKNQ==,iv:LlkxyQkPgLo5LNORbgvHIlT0nSZt3dUBH9zwYPESvcA=,tag:k4QejcfYlTkhpuZ4C31ztQ==,type:str]
    SVCNET: ENC[AES256_GCM,data:GKNCa4lT3ll4Mn4XOw==,iv:Ku4U15dBYlRNveXiUrYVBiAa6Q7WhblKihboqEKIMp8=,tag:KRJzGU3dqkb5k278SwXJng==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:yTHvSg==,iv:exMJtIm4H7C8k8RwteWmc4qujsLq6zJ6OKrNC7oDJC8=,tag:hFZ9iGpxFy+Cb8j4FdQsrQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1agltukf6ellg2guets9gq4th2nmunc965uflry7fdahtj7ea8uxq8q54ae
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqWDVoOXpsTHlsdTB4VFQ4
            YWxod241a0MrOXkvODhOMi9OcnFwTVNoMUFVCkVJWTdkYnVwVDFWWFJiYmRCakI1
            YUVSVThLS2FQQi9nZXJBcWpJQllxNWcKLS0tIHpHWFhQQU13ZjlJaStSTXIwbFdR
            OHJyNzdDOHVUbFVXc09OZzNLR1hMZlkKMUpnOkqmH6Lgd4b+QJ9vSDGH/QMmr4Ic
            12vn4XZVu5lkONQeyDtIrs0tDQsW4NbOR/+CeZka7hg6rithiFsOqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-02T21:46:15Z"
    mac: ENC[AES256_GCM,data:wQGd1tZ4RaqxvD/6kFnmmtlNzeOmFTT7EcxQ78+ENsUZhHndYxv+klsIMyHL5uRJ8VO9snoixix1AQf43KmsogCBwRzxWeKAJ8WvCxON6isquWsBooGkDxJ7ETtQX57Fomn+W58VDKsldlMygN3Vtp2Me9rqb6tMyi3unNc7Ie8=,iv:tNQNVWeZkSL+qsx1a+Ysvvdr09B+E0FFfZAFbcsEQms=,tag:odTaEmDcilbdUfT1Q5o2vA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
