apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:coxUq0/E8GF71v375fwTiqimpA5DXYjjxd9GHyrI0wYRGGjzgv4vYq1PGOhjG8fVX9vxXPX+twJqxK3pWGJqOjTvifxIwNryum5qOeCwY+5cyYz2V+zWYO3zNOtiNVRbh5Qcal5EMQzuNgPlLp/5Opuqb9HWGb0vXlkC0Jw1+WDHcxQHocWoY8gx/WhS2zLYhjC7oyfPTAjRaGb4Yg755nQTZnB1LcOemBpw9RrxZJq3uwUIK39SpKZgUmY3v0SUuIp1rPHlJWzYtpq23tVG9BwMqbKNmdEI5CJURcYz+rsBJek/7m+35Q9B8PrX3U0lPsDYODNXWJDKSkx+k2F3VRKMwNSWF1rCC4TbdVjQlGyghf/rVLT1YsaOb3HENeuV,iv:E/q0dMf4pDsyQjojUoWrJWeKlNQ8vNf4g/MGEOhCKEo=,tag:dZGRBn0pzqOsY2Msf98KVA==,type:str]
    identity.pub: ENC[AES256_GCM,data:7aJt/4RAkBIllXSKIcVNw2xwss7npgLq4B/GcPTrqM+oiILvdE4SWdfa2WrFR9CXiee+BZqCaMXjuUbBHuRib4qRlluTECVO3FBKhmMJnnuYosfLb2oyzaOoRkCDfiA+2W2y85HZtaYPQbiD5FRSymb7HVYKv1/iKctWfcdA1SHNDpaZZf1c9piQ6pTWGJWs7OtZHo1uuS2pjrbnV7RAZRZ1JyFJSKaGNj14qBBMZ1tHLj0QDQvbod32PGRvyHMe9N+pteF+y5bCQA/mYw==,iv:M6Om0JeZpTWHYoiRyuxQlkGyr4nPI94+PZXo8709XJA=,tag:fTkyCYYluOu7P1z7IBL6kA==,type:str]
    known_hosts: ENC[AES256_GCM,data:OeFLPybOXLFIcY6Iei8/b2eDdUiV8hRu4gZIcSdSvY9HkvBtNbF5NnILmkg2sedZt+xY5Xnf5XhH//vFJERpwVFxl+GiQs4HVf6dhxZIYmBBhNZH8y29PsIu8mNw3MhAcnyUBXCnnCu6wZKFxdU3XuEIX35S7U2A7OIp3wVFDCOpBfjxwCO6xSYU1Zcz0ngK/KrV2rP0MccDhKPffkhZrW+gy38r34WKdkg7,iv:xSyehxGKrGzmDnvuiFdpzqDKMJIF48cMEeyJKNU4ak4=,tag:xEf4/3CzJk8yWuZAampQeA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1agltukf6ellg2guets9gq4th2nmunc965uflry7fdahtj7ea8uxq8q54ae
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvaHJuVTY3eVBIL1R4Vmh1
            TWJRWTNMTWxaYlJrcXI2cngyS3JxK3ovNkRJClptSzQwKzZkbHpjSlpFWWJTOEt4
            WCsxeC9WeStnT2NSQllGRjRhOE96bEUKLS0tIHNmTTZXSkk3SXB4alc3cnE0YjZi
            OFdORGNIZ1ptVFlhTkZ3bythOTZJblkKPvm8qhtF6s/bZnG94D3OAdnGHpx0Idlq
            lJZRzEnUJpu3GwSBbd/B8EHpdYzb65ZBzipmD2TMt2h4SWgrCRaUzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-09T01:36:48Z"
    mac: ENC[AES256_GCM,data:acCHIwfOVTkUqqWQpM1w+Ul7EqmbysWwKkGyRnzRaw109pOD56ksuUj5y2IVoP0OmFkQ1sS4o1wcxt/vG2piAhuyMFrOh5pkOtHl3FnBzad+O0ytYQxOzOJ18+X782sc3y1SlZKUQN4KqCawaqFja8LEH6EDz++t3hQZID2EBls=,iv:8N5+MsZajg4I26eXGTQYxN8HgML4grejPNDI8tJXKt0=,tag:+rWyBvgdNv/gJRvlFnv7PQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
