apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ydyTCqEX7pg+sjjXQy0bHcmNV/Mk5DcBZWzK/migrWm3QYP6Yw7zUDEIX1jukQW4HoirI0SeK2jUbubTSsrOQ4AflfmJQrbt7ue4mA29F/VJS9jLIvAtp7TxmJgPPYJIYtWNySrDYw8e1kkjyuHorv6Us2TfS4hBmpVzhamTCYRkyRBD75BW5eKc/Hh+Xfcu6i969P1HJKs9WogwAahCs0/tzUMl555JYf1dwIRSQLELDNpfor2D/0KXygQfkQYHks9z+BtL/kdJByYysVTjtZsguQTxPgZDcU4lVwQoXtxKM9pIZ38KigPgiIuifk9h21x9u2T13V8l4SZ9e1DX/26Z82NlbG9h40aGnXINjCQ+z4sRXarhEppwjbfxlY90,iv:8RVjRG7TayIDGstdNe5ly7UyU9Njm+7LawtBIrc/bzU=,tag:JPgXk6haSsYphUy+MiB/UQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:uPyW3zB68i1romI0ohIJN8Rb6BksrCRNI4c2+WuBdzmT5c7iPOp0NbWqtJZripaDflLB3XFIswo4YfK/2ExEkhyxEYuwGg0FD7SraavGv7r/Gqc7iM34uVM+eDhC/XKVOl9xArnoTrXqqaj+4wCmnvJ1AL+mmBX5blWteb+p3NKR2069vKoRYSeEihsWxFdKonDp9forl3WoNhyxAic2+22gtRu/+itXiE3cGu8S03oY5eMazfB/RtzCRSPvpqHz/WTn0WJhap6LKDJRpA==,iv:AUbtm64hUjRz0aGtzYoAQ8eoMZe4crIIhN7VwYeTRxY=,tag:rYzJcllZSV2HDh4M0kKF4Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:69yU5xv+1VOP2ihWKI8uhv7G7WWMeVOSc2T/HWcJgnYQYRyxu6+uCDo6xYUIhQdJoW+Atrh0QxqfAhI8KIbcKd4gBhzuz9+mcUbnrLX0kleHA1Cb669iku7pJQLupqndPQuz/5sMPaLMo9J1tKUtopYBmEvF+lxiq0SXOg/0+Y86kvz8X+G8OcYjdaH+bnR++H2UFyW/fwWP4vnSvpPETxfWdLaMUSMOPJDE,iv:RtdpGvNQ6VyHPopC36Yf3fnjEkt5R8j0XUQnb0L9WqA=,tag:JKBFthUZZld92fYXoh4Kkg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1agltukf6ellg2guets9gq4th2nmunc965uflry7fdahtj7ea8uxq8q54ae
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzdldha3dPUEIzWTVkNFdm
            TnVPcGZrcHRpSENPaDBBRVJlWEU3WlJIaURJClJyMWRaRWxjaUJLWUp0RFNHY0w2
            ZXNDTkdKL2JBVjhuZjh5S044U3ZwbjQKLS0tIGFXNWdZSTJkOTdrYlhBVmlEWTVq
            akMzSEtCVWdyZHBmSVlmUE91V1NoUVEKAXZBWid0symPclkpxOihe5AEjV5geipc
            e71F3wtewpoKRgUMx75UqnNmjb+dUQhbr0Xd3vvuUqZaljwjbeJ1Kw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-29T20:15:08Z"
    mac: ENC[AES256_GCM,data:pbxs/Dedi/JWxGsT8dymv84akNVbrwJrG6DsYaTyylwmktyaFspSTkCY4hOfij0C1ZUBP88mkI51lvFljdNlHcuKqcJ0axgzjR6csDxRTBdPYkFX9zYDwrcQWS2p42iA5+3uH62lTg/08p2flU1lEVGs5GQUlOGVMlUGHeti4mU=,iv:62vZpXF1lvn0aSIDVo0ja+a71klO6mel+UAHpwefFy8=,tag:QPTFg7QeV8ZAtBtsI20TGQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
