apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:xlt04r1W7aq5LMoEHyLRsy4dHWeT4x5WXrginLYCaT5Il7cSzKEgejmKLLakuTqexJExNgha2VzNvwX8HFpnAiaNdfmj7qw2aNb54BZIU3cGTZYD6mLDcDwTuC/1if97gv9MXuLLZb3Yfnt//NVz8XoZ3Ytm3SySQwbYpd28O+nemdpjH+XoiShEmVbyxIcQ09HEzGYcthw5qcMkdRu+Gm8H5S+Q1qFY31is2m7EQOvslUNE+bjxKNWHaNsaLg/Yhp9sdc+jJcJDbSZASuqyhpEUoIBqEpR9fqyMROIBfeccl+4L/csoLTd7Q9CFaILbt5KN8DI8QjjfbA2KjmQicGgy+rf1RaKLdigtGapWZCXflhTgU189sl0/UGjazuSF,iv:UYEDg62/W/jFOdFppE0QxAdBlN/n0HkQCtYHG3pJ/I4=,tag:oStMAZ4mJSRGYYQ8LS4r1Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:ICDLg8qhuYyGAkg5EGP5uPqFhvmYqHZoxG2ryIlpNRTEQjamrHLWZ/F5ex+SEzIFOus27YdaeNgcaEOi40SVuqIVU2wSGtr/RorvVh15ZKQmTB4bhb0kHbZ5z/TCwvTHqoPa/PhkHlmzwLrSj6I0scCSHE/YqqNHC6O5bOUhVAl2A7RUn7QDBWXieJl72YaOQvSqPw041QLaZY7J6Vj7vmfwL1KGBHXy21cicqw8xphedKkXjJw2ikUL9rLMI3k8dX9zPKMk31RbAKlddQ==,iv:89hPy3CCz+LkE43AjyF/on5OrQJmcjmijx4aeQzhZBM=,tag:uG5ZkI0I6xnKU2QOa97V9g==,type:str]
    known_hosts: ENC[AES256_GCM,data:etMVqh/aXW6ZjXSatXNM/9mWWLaRuFAHtUTV+dT4kB20YVf7tiMQj6Rw1ByooqriNNLBahCWDVe05WWrZiFCe+w234/BGdxWV1tHqS1OQnVt+F9sbt9Zf1XTYVY5IfhS6QUrJBolbyoO4DBUkZOyDJxq3xF4qzPqj9K7MsSCURfyjpzy1VPFYtpJQYkvWcCuNjqnFivWl59IZWpGCCpXlxXqxj3+PMiWo8LL,iv:F/srmRm1FRPV/ojoptFmM5jO9KdpdSrsqAl2wbSq3i4=,tag:gD3nAPXTJgfWlLl7Mj14oA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1agltukf6ellg2guets9gq4th2nmunc965uflry7fdahtj7ea8uxq8q54ae
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhV1pNV0VFaWxSdHBqMDBR
            QTdxYXk1c0ZrM29jSXB5a0RudGNYZnFiUzBBClJVUk1FR3ZXTy9nZnQwUUFPWDQx
            SlhIQitObmhNblhaeG1kNjRjUzJvL0UKLS0tIG1ETXRwb2ljaFhiYzh5RDZ0UjR0
            MHF2KzdEUFRBQ09WZFEwVWRRYXhoSUkKYolMwifj7xSb4KjmK4++GMh0pzDDYvD5
            cYW4cEu8EXaiIpyoRgRwaMKVdE1hoftLFgFtIbAJmvozzkIM/+6qCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-26T01:56:13Z"
    mac: ENC[AES256_GCM,data:a+wbCIH7IaB+Uf/X0kTlhubOCFpjfYvQXnyIf4MAWRS0SNlKVlxoRqRmow4p4UiuFxwDiptHBUvoHt1m6vbRNJVQiD82iCWc6R+8eBxs5Z7WnZ3LRnCUrAQtrsslUCDv2pVt5ePNsp/Q+4EnkcPG8H1C0q0Ud1ULRU8A82tti0Y=,iv:5aSOGB4cIRjjACCFYP/hK+Mn/VSarnDaKfxjxaYn6ig=,tag:Ldh+28gOvS17YmzPgKS+pQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
