apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:GkBiJfSi0TgjAlgu6wxyrMZ3du1EuJeHZXMh/4rBCF3Cvs5c8XYpQqWLknmEUjqbptSyH9Y6eLWUdwk68LxbTL41Klw+xtI2eoXAu7A8RwzRq0pZHPyU98wfZVNYPNEIks4xVUQil5OpFe1CytM+Hs7l7zHQloMhKsuDpwT97TDmzmZvV5p+wcDGMQATpSEzT4GZEAq7Vv23OeCb29fvQFaDErdsJMqndFpFpeJnTe8jrg0RP7AO+DkHgOIU6iwh8kco6A/Ew9x11ToSKg2iG+6ICW8REckoWl2yHuZ3l8StNdUUz7vSAAyAAqtTauFsr+OX6J9SR/09gTx+wN29QDOgY9FNfAeWfBDI3y/s9dSUPinCdDXKhJfaitTS+XOm,iv:/CuWRNiy9mOrEPOD+AjiPbi9xF52RMsGgmfWIGjtPS4=,tag:maDoAqbyOqN8Kloe36Shbg==,type:str]
    identity.pub: ENC[AES256_GCM,data:TxmuRFd076bKi+nRUcTziIH55oD8yJ5q1txTK5BHenzKOGS+cWPa/bUo/44C347Wzkf3vyeX9Y5cV8a/HVPFjO7EJtBV6n0vVtpFWbFSaCNZcDbOA6nzI4KUlHonEQi5EC0v65P4nNbBDJKXxaqZQKOVJHg1bkJYBMAXgnoDA9frH8KXnNfXNxs5gcLE0TyxqPHcd5PSV1btaeNMeSM5hnfHJ4CusWkIR8gPmP4IA0QkI1Y+cHrVYiPcCdt533cLY+XTvZ2BKDAC3Nv6ew==,iv:4kLZf1QeOBWuZfS8QuIS7CV7i3/kDAdkH8lyWr6ojJM=,tag:SwE03QJ2FD9G81RXj5ns0w==,type:str]
    known_hosts: ENC[AES256_GCM,data:V5k/H1Kp1IOwQ7d29LrxbVVktZav07Xo9yv7FyGKD52pPr1n5NwPO8CTnOeKkKuNpcMW33LFTg3N2APgnYEg8la0Q2NZNcJ4UkmTKQFq/GHI5uFD1kHi4phsP3jLSt9ZaA4fHyT8iQycEqTJrozG/BFFygiBNp7FyIMeEUCE1U7HOIP6PK5oFzFQysmKDxCvDtSh2XSSd20BQ8LT0uyEIBmSkiA8jFJZAu1v,iv:8jr3i3XPWpcsbcfNWb3zSqTGNNmEPpZpP+1FBK41bCY=,tag:mUgPnX5qP+avfyLPyYELqw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1agltukf6ellg2guets9gq4th2nmunc965uflry7fdahtj7ea8uxq8q54ae
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBncUhlZ0ZJVEdhSnFBYWkz
            RlBIOHNheit4L3VkU0tIeEV5dWxUQXEwa3hJCjRMcmRabG91SnJhaXpkV1hiS2t2
            RDBaQTdNZ3hGMytrWlYraldZQWk3VEEKLS0tIE9OWUxOeWppRUtGV3ZuMFRRMWhO
            TGZlbm55NHBjcW5yQ2U5TWJsN0pEMzQKUGQ9Onsom8KG/0zYDoQ0vRsptYaVBKW/
            SLivVt0oHOmwRbDPovcrCMO/eC6Vx4A4SnYt8WQDUnk+F3++WQ/FtQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-29T21:34:37Z"
    mac: ENC[AES256_GCM,data:N44gg0JmL9g03izNv+3ejMm9Y8Nce/xADeBDqRFSOBdDhSQxv2Hq8EdnDYKMrUb/bpaT3fzXY2CIRYSjzSMJpkITmzwm44HHAzXmwToIl/ymYx2Xg1MLJjhCC7FTL2DKI4CWY+QNiR1n32PaAe++1xs5zgYcptsrWg0Mu5Dza8M=,iv:MLtvfeIloqd1RDjS7VHuhY69RFK/gprPzdnRKgOVNe0=,tag:FDo6xtIJvGuKOwUOPYLHzg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
