apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:XPJr8tYv57Dz3YUYzil+Xl8L4IO2urnM1QP1VHMTpg+T2vqqANvM19DKC/rmsWzKXbNDtRxYHFaB+T+zXJ+93m5IbNGi/VFUNpN4IN24jeAB0XdUohOp/IRUs88aaBMW1wL3qc4a39Kt96UtNAjHXsv6IWNwC64uc4LhiEFVRxJndCh6kpOboAClPsGHVOisAFtXtztGQA1Ia4WYiOppr6BjpyUOLG3jdboYfEdCYH+WMpo8oNlUtmUgQPDhSBedcIK9kWGFfGP39D/8p1HzfTUeOR0+l82ECsSLrigukbFKZQeQQ23FHZctTeQY8BOnZastrHWFBov4Fka1dhWYiJsN7pC9f/PaYt2Mk+/uRXYDgwQRAVxRaSXeeLZbIUqb,iv:PhMc3DZjWUy5/S1YDKrvI9uvLu5VD/lNRD9u6b8SPyU=,tag:WnIgtepsDS7sjgWld/Ukig==,type:str]
    identity.pub: ENC[AES256_GCM,data:3/LhSYt5rFhnBVhUS60y12A7dbCfldge9CRxd+0q/V9ggJkViTr+TGvOyy+Cd557ivPsHinC9ZL3aR4v++mp8TkxTp3UU+Xc5JrzPLzo+ObXllYyiIMaJIpLewNHJGXCswCIoDd0bIEI5iA2hcT/pMUCj28q2S1eaGdrXbviYEqxII+ld/BaT8fYCUWbwLHMt9dtgCJHBpAB2vk9ekRVNR5fbYN4b9w4nj6N3GohD6p7YGt9d5dYHxu9jPPoxA98YCqhAAtmzp0/mhFHLQ==,iv:9ZkNADhIsjDFQc+hEzHvhjXxdtoiKxqcSHH2YTAbhwA=,tag:+jL3rDsWXHeRXfHxJ1Ps2Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:JD1hkf7kmyrHthmF/AuaVHK7VRaxugy7HI9ozO+jqQVqmO9yJ5ivQpvP4rWxG6V6+OhureXjWJfuWZQhvVkmnYXEeh6ganYeayUUw0ULZpIUzmrUs7Fhga2FeI89icOYApSRd2NtiEOwuhCsGCgbJFDFuErZhkF7kLq7lYkq8z/9O5m3fLgQc9zEqubNO0ObICvemPdYooE5tMzoO7TFk9tJomlFr8I0dBn/,iv:WyrdBcJ24f1kqHEXMs0Go3zmugnOs3UnzXxJbmh+VOw=,tag:f9DYpvpP+Dq2nmBbmL8NBQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1agltukf6ellg2guets9gq4th2nmunc965uflry7fdahtj7ea8uxq8q54ae
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBRStrWkpaUi9YTWZlbDNK
            aUJLV2R6U0hXY3dSMW8zWHFwQzUyTWQyWWdnCkJxa3RiSHdybXlQQk9vNXFCTkc5
            RElsTmJRclZDWVQ0WjRNYi8xTEZOc00KLS0tIDFLeTgrbjNmSVNKQlE2WSsrMVho
            Zldhb1hxSENxTDB6N3ZVTDgzNmVzdWcKbvAedrQ9QNsK7+SaDjw9Tp6EW24CmDu/
            HvZHogI1G5fAM4dVxhFLz5hi6aNjymdrNCU6L2PW9wioKfGUq5qfOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-22T04:45:31Z"
    mac: ENC[AES256_GCM,data:ZDrdNxwaztlNlW740DZ3Dp91IGt3Ygqo/qX6LUOgUl3Dr3Elg+5N21Kag59B/i7S6bPwuXcnLGXiw6Vr6bxHkc01vl806UELvMEE3JGeA7/IQuN4y3SCO7xCqHwu3+WpnfoW0ywWRQIapuCtHU03JFgBVABgjxOgLs/DJ4540GM=,iv:ms6/Dfvaefm60L3ZLPkI0oTXS+pdHf0da0fVuYm6XuQ=,tag:/F6rtfVmxZ07WX1hO8ReZA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
