apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:67aOYjOio5lTOY+C8oXWmGezFBXWuJ0OecYi3GGQcvWRHSS3cSKK6ndTLBRYepMDHaUe1c96b6fd5oPXyMn6x0tdJeg7qoQGjLZpgsus2/ZPre9EgyyqoAAB7Yk5gjwB3l48pv6HDqtQGSWIktRTPHqTzmIHuUi3QNUyUJMb+he18vTPyMl3GxuZdamqvHyTY45mjwhJtdSeGK+AwTi6qIU5Fa+EDXgvWzXBX2CKjcNTbh+LGXEO9f4OJ+Vb98b1ZBJGfdkqQd/Cn0gsmRoQ9u1uJO9JBP9sQA6eqcolDno73TKUivLAE4yGnOJTE33HZ3sBS8uA6nlv8yZA6Z/QCDjY5k/cYFkuHN6P6dcYe1N1aNBgCGYk3Mp6UYYivzVo,iv:RdUk8AyAMsWfDHpiLqIb0vpuG83rDOFQYoFb5L4KC7k=,tag:vTMBCK9SzIsCUK3k9P5mpQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:A9BMM0891weADjEgmkD/4CVFMXPNCMfwuLvbGCIXO5zCLp6pLxcBbfIEQPLdn2JxZkSEfKD0Qd4gR7Op20cRaYZAJXoIYSH3fZ1RfZCXNMMi7toLJ00bhtC2U3l5KaZs4Ia80p7U0L/hOF/3ClE3CJjN7JuMfQuGqw/Pudgb1SQj8MY1h+8wTaSEBbKBMoDNDQabGlK5NdGdEAlF5qFc3u0W2WB8LAru8sukMbdwqIpi6J8OS8iIYRwhC1kkFjWwdCyFsX3gMpVeqQqz9A==,iv:fMkFoJ5NzIGRXNdeclSX7AYsgM5VAuFlr8nmwyxIjw8=,tag:2meGf7IwbAIjy1FKIFTobg==,type:str]
    known_hosts: ENC[AES256_GCM,data:gVmxqRvbHHuqNjWYV4+6xKvJIXulFzsxl+6AOMUB4D+gV4mrT0mvMO1/NyN0FFmRGeNqbvN3VGKGklY42gyVQyK7LGgJ++PmTTW4+bhOB0s+fEGrOWiE4/tVW/J25KyiS6beW9881sNbDMtpOOnbha+X92ubRYYlBmJ72BwX/L7wXmmsMNLha3jQzlf9gOChwzBbAM4wT8TYHWE+FZh6F5ev7IPV2xlQK5aY,iv:eq5Yn8l05Rrbf2GJyWFz+EuxQtpb0pFAmOw38bnRp0Y=,tag:1IyBRm+ecknsjg9zxBEYxQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1agltukf6ellg2guets9gq4th2nmunc965uflry7fdahtj7ea8uxq8q54ae
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQakw3OS9tUVRidFY0N2xU
            emlaUDFHMnhJWmVoVW11bDFmVUNuNWdqalhzCmNjaWM4d0hMbXp4U0hGTWl4dUVX
            M2I1OXk5eVJpYW1mMmhzSU80V2p1QlEKLS0tIFN3WHp4S0cwaVErdXVlWFVmb1dy
            QVZ1bHVOSWNicE9uU1pLTU5lU1pOZzgKqU9tasuoidyf9klgIt5Mi7pDcUlExqCc
            u4SYWSbgqGce8jCAjK2g99GSnA4ftrzO8ZOYovkXZw/dudlg+CvXYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-26T01:49:37Z"
    mac: ENC[AES256_GCM,data:h2aoEobAAnObBc6zlQ1Lr2omyrPQ+zrHxxyv5LjzL+ydBETkbftMQqC54YwTjnA9WpkUYbvjZLUKEX1ti2xpDTQz6m2ed5B16TAVT7Tj53/o4QlJZiEriVhrqq8Kj9sXulh5I9XDr2J86L7Kjw3e4m5nxXkEVOLh0dgSmQYFdS4=,iv:p8eAO4QUI1s0Hrv9uQLfc59W6cMcJAGccrXtb+Wh8OY=,tag:tkejDi0s+Fod+kN/eHKPWQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
