apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:5cjBmyVQfSZpsj1E1ytouw334HEQ4pGS1tI+kbwVbkBxHS9g2zl8Z+lnnZrDz3jSO3Q2KGcT83yaTDebWnuncfROB5Ern3coaY2wrlJSeFsuKf4Xnopxb0leWBz6BPNpsrHAcgCjQZY6o8c51MRwSCrP+JONIpZ7FIQvcZmGJ9nVbAmrBP4lQim11DTBmBn6Ycj/O1qzJcZ9oJp7G7Nhga6UXNe3jbbNAL275bo+MBT/Zxwgk3DSHvUBepIGUm5j03qq2+VSFhLMOEhRfQnp4E7Qld+PihcpJi4mS7JkoBxM4NWgbNxzLCDVH18GmDj/D/B29BAPY2MhcAHAN1jwuMMYlBcu88++ff04FM3QBeVnfAsNYzWinZ42q7WGA+rY,iv:Pz7GutVGvhrPwYa6eY1Cgy1PRjpujoIgATfVhl9/6II=,tag:rVGrszspAKb6G8yTXTROKw==,type:str]
    identity.pub: ENC[AES256_GCM,data:A6lLBQeKi1MfaWImHEM4XN9Nae+M9NU81yLd3NV+uoUzBgKETRAREHc57Y0Vdr0TX9WEpHedH1VFrLSu3himYb6+h/kdobx876T4lKoZ65uM2lE+F8WRx4IHz12ecJLA8zZr5zUfsooB/PsuWSyShbFZSSGtXsc8ZKmsXyn/WL++TSI56ptV3T9xqB8fFYlld/d6v48OvwhpSrgv1412Xi7tCm0Kags/HldXfEfsclBLQM4j8dd4bZP0s/fP24WyTnbHOkDCALSQ6pop2Q==,iv:oo0kS9LFjCmuNfmj0Bp4ZKfSNGhis286nk1a1yZlh3s=,tag:nPgsf90XcnJ9wOLX5UaqCA==,type:str]
    known_hosts: ENC[AES256_GCM,data:BxgNyKbSs7iuyTRlISFpD9QSGNZwsawh1BVLSOE1h93BQT6R80CzemrTuFasixhlbkxvXa091MRu6Thm+DnJ9+bmfYFAdCC9HMESdjdPq3xU/oj/SM2bXlYfdvoc0lnqvI5Skr/fo3SH3UUYCaEg6FK+2E71dnMZzxyof3JWZDKfH1RyRxNo06qjPgYIUYpgWezgBT8UBSg5paoGoRBAKHrNAIGE41NjGCGN,iv:DO1diL/c86BqUXlnqnlDsUH1gZ7m2pOcait9kvPP1gA=,tag:+aAruwl5mccyIGNn7GZKnA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1agltukf6ellg2guets9gq4th2nmunc965uflry7fdahtj7ea8uxq8q54ae
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkTHNSU3RiVzFSY0FlbzAx
            UmhYTjQ4WEkwcWg0T1EwOUNZNHpXY0xaaHlnCmpCWndNdXpkN1hBcW5WcDlnY3NF
            VUI0MXRhMENFSE10S0ZVZzdPSit2bmMKLS0tIHBmdWwvaXJTOXV0NVhaZ2hTVmZt
            Z1h0dFhLZXZJTWZZZXpsYTdpZ3N4b2MKkYf5noK54wB8/wRiYfqZKwvjrcnWmXtv
            9ia+f572tLXYO1dpyZ/0b+qbvuBFJie1QE/5SEAbKN4kTfvYqW0p/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-01T22:43:27Z"
    mac: ENC[AES256_GCM,data:5sz5vduz4OKRUTy9/3kXR3Eft5QjEI+fYY8nSsBadbzyO5EVfcuwwecpuJaRRs7td/SRuXRUTdtDeMO1kYTM8KsnWnEH0No7EoHRVgL9VxeJtkH1kVM9myl++ik5f+rwGJVHbSrAYjlJHp7fpBlGeO3JkxyXKBjdwEbwTyyn9Is=,iv:VpzomKlQQwTlU9qVIRB30PVk52KmrUuPFzvtE2l2qzo=,tag:K80hb3/B89kTTXfJWfCmOQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
