apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:67eX939oXq24kySdbkXm6bff2r2Yx+gCywBKlJjmCPt5T9FE4JyyNohes+w2lutaCtsu46eOfQ6wCjG+oB/j/QVE3q170Hsv8sOPwLENO8F07kkzClbEgv0KWIPoMKZ/V3WH6dFDY5V1hmlf6xiiD3eMaLF4oYwqp1VdEbfkNQ4V6IgmkRAlRD7EPDIJIYN6mcTJHISQeHsHoUIJUK0cxT+Spx8/yQKiYotMmqtd+o2CO5gabq24kvAZ1365R5YebwV9IUEcqIuUnRczFqf9gI05nbIqFSomwQncJTDNda/P3IDdjEini9kGfoEtlJHdrkKkR2pnJx4ZRRSufIX2gf6AWIcGzUxmPLiHvHzYgjxkcWJEZnh6ude9L8tu4UfY,iv:7QQDxiBnDjslpH2Bx54yGMSF8tI4gV5HyOlqGw40mRY=,tag:F0B0vg9m3P4+b5dDZESSmA==,type:str]
    identity.pub: ENC[AES256_GCM,data:8PA6a1IevH8wRPaaoJPzciMlpYExIlEe+bdFouVNbZXF5zTcg8/8rhn0/ECNCY8Jj7gfwoATYQJavtYsQjozP/HlFFGZ2biKM2a01JhQbCEKgtpCrNy0nGsS1Moch2kkoVzW2ZyYPeJi6uDx0Lpm2YJZgeParExLYtQyiUl7SaoxIOY84sNPnOuP148JJQFePLFmBDEFs/47BijcBZgd3SSck6/vBGngV70UCjw/RrVYprGNsO20JFiVlEQxavoBtqH7LYV0OPlUTsBB1w==,iv:FBT28BTSWAv3xhV2wR4nnHkTQtKTvHHlRWWBy+ELRoo=,tag:T1MJFIUpipV81YikGA2knw==,type:str]
    known_hosts: ENC[AES256_GCM,data:c26Oz9aRrKUqcS2FniuqokIq1djsQs5f835buHEATFPnYMNptz2TWyNqF/R6nSh/ZwmNnge0gGf7u3sOSeCLuXOk25uJDiP0oepuc9NzrjXeS6DWlj3ao1nEHuBfkHm2/4pZCF8vx30msBolKFD21+URijz9SXdqg61o+YTp8uXxOQWTAisKGdAwQeRkudIWu86JQPXgi3TC9869hknSek6YiPAnyM55HN9u,iv:hc2bne6ekDTTErwq4xaZYZDALhiarERqRUcTVQ7Um4I=,tag:mjmVLiWth49o2SldUy15cg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1agltukf6ellg2guets9gq4th2nmunc965uflry7fdahtj7ea8uxq8q54ae
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrd1hqa05mVTF5bGVTY0Jj
            MUM4dm1rK3BWNFd3b0MyWitKaE9KbkJYdmpZCmlubEVEMzFwVVBHWW5Zb05tcktl
            RXdBbVV2MXN2ZFdTdDNUL2crV1lxZnMKLS0tIGJWaFRkZyt2M0NseDVmcDRoQlBY
            WUZ0OENadHRLK05MYUpxdG9LM2dadTAKI3wDkOYL02gij6i1chJ6fw7AD7WBO0vv
            iBf9lbk/Oi6DbHP1i3XVpknF4qEwdaG8ReHubooUxeFLyOaBJGGzPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-11T20:46:31Z"
    mac: ENC[AES256_GCM,data:FnQN5vwWaQkLGCSP7zQVnQy6CKFGKqM8k0YpyTJtAspVC82asUU+bmzSydFPc00URlLn8ChVSbgjhLpCnrpgpaV20VhveQAgG8qb15xfqbeVk3mbHmnPE1yCNLNa7+cO46txiooU0UIBd9MMFv93tE74BH2jKDcUCfdmMYtkHPA=,iv:aBNiqJ8xddfMO201EjTONaMxb67eC/Zox0/UupOQUqw=,tag:YqIc+3FbSQUny+wvyDuRVQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
