apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:KolkqhyiNah+WFwi544OfGBqCub+C9IKdrXXNdJHLt1IArXdhy/OJWb2P32ETrMH56R0ylzYFK7vu0gSWPyJjk5M3zkhXbeBekzwsjB8d0AZyEsgVZj/WFSkm4/JMQZjn85GdGhGqzF3ohqHIvMkZRlXw93IFDp4etGMZsfUyGx9vhCCj9LUes8qbd2VX6MIUz9amvIeXNBQQizGWMhrzIBHFJ30Hvze6laMFwvMZc6qtblecXg6trvOTCTnCkMeJ99DgE7geSwdR5VklCB55LGXMvnY99pbiyON5jv23ZIFjEk62c9VUSB36NinsKQSSHI5SYA6TXflSaLBastPMYBxOcn/pWQ2FqqLNHq1xGkqWah8738nQvIsWmPFdqBf,iv:NHXy+ynRgLNF629TwoQLRu3RvVbw7i2tqIpO/SLSTNc=,tag:/gXB6Pc21MdzwEZVuy7wYA==,type:str]
    identity.pub: ENC[AES256_GCM,data:AhJnDikl74IeggF9jKvKJloD64V6xxPceoxVkWyPUUsVDDwlIRk6CuRGDW+C7aPaHa5rdt0UV8jW9guiy8rgKZ1SAA7W/O1X/k/5MLgPE91hnRYNzsWWdEngiMU2YmlLVzvE3KTyYL9SLSrWgf+VjTO5UoAo0s1lWW/WSZJXHlso/I3yeuLJByyYawAh5ARioUaw2O6cXFCUnE9Ym9L6az64+xZRqhOvTsfd3+X8QDzywKPlwwRVymVPVngfQOVqFfkDyTkNEAv8qf5ovg==,iv:FIjYM8SNU2bhggPG+B5+Ax243kOb1ejrqJDtsZ5Q9Ng=,tag:1ZEj6h6rCUMA7Y2YTguiew==,type:str]
    known_hosts: ENC[AES256_GCM,data:bPqq4x2KrgjpUOnUeB1uatyThZFztrqYbw57YW1ViGva0zgxx6CUzumCby+z1UZeLIAjh4YurXc3A+BVflbjKCyxB9iw0y7xBYjdrdaFPnFlNOq82Rju9viAn1fuohcGEe4/bBV+BL8r3QvnGfbjXBE5VII1gpuVb6qugZiCzfpbsuJw+LXG+l3E9T+47Go0bN50NjrHYxYHoD8hHCj2Wk0qxfqgRz/VSR5L,iv:IZ2qNw86Nm+Az2A4/c2MyoGBfi11bWx+TtB4hnXbStE=,tag:It5S4DMeYGZj1+EbXzrvZw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1agltukf6ellg2guets9gq4th2nmunc965uflry7fdahtj7ea8uxq8q54ae
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzMWVqUlAyM3MybkRhUkY2
            STNrZmFGTitpeU00UFNYMGJ0SklsakY3ZVdBCndPb2tnbE94K1pmaWpSdW1mTVpn
            UU94dkZKUEVycTY4QWx4L0orZ013K0UKLS0tIEpSUTBlbjlpL0lpdjlxdGFSYXdC
            a0pBMXVWR2xlOTRhZVF1U0svbGx2eVEK6t2wg5Icm/XbjXf1AvdBWfvnG3S86HRF
            /181uW0MJq0Td+sTPnZSQo5w8aAkf180r1LYZbj0kNQV3VMXCq9eHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-22T02:55:22Z"
    mac: ENC[AES256_GCM,data:DPgAzhIkWw9Y7TxI2x4T1qIy/Mkc5rLb1TCD92f3Yg+rt4E0mDHVTfUzko6QifG0sfPcyl/PHBsBxNEXYWl7LPkEcuZuoMCFVIU0rmIiwW0UABtIZqTl44NSDsOgK2agzB2HVA6vrvgMaKeAkdlO51ABOBvdeIm3XGjLFsj3Sq0=,iv:d2tlzVmItpahYfEQy2kHb3S7icpafeTZNtwZMWD6EjI=,tag:q6NVDH8G/bULHfQRKtaeow==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
