apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Hwtvc3xaAG+PbnwGtZVhzL7ehQ67XXz/2EWJVpAnZAO94WNWMDZef4uqbujrEcsk0Y755CSmFhIZ3hv2EdnHslrjY/JRH8Y8WhCfj2hWiMQ+S+Zd7bUOLhzDSaT4anAF1a9vbGCj2rm1PQDnjBphE6MQRHP3VxlejuBIrUTZ99ci/AUG8/VSvE/YVQH+U3Bh43EJ2PyD4hhcgcqTUkEaE8O/iuQpwHMobj55FNiozWlTQ+PiMzSal/FmTRWohp0lAaPjBziI9Xtm3JiQatYqxq20BKSnZJwFyYJCU56SWQMALSWR4gAsx1xZGhoQ+4aP8dmsqgWZT7Hcj5BpZrFEUFWZcbx4+CkZC8SUW8eVEPHPiJRffadGGdxB5nPpGXfM,iv:JaPbw5lGZUpOsgkFQ0WC/IniiSQKpOYz8hp2hZwUDE4=,tag:f8ik3asuSxvTmtK36Hbfbg==,type:str]
    identity.pub: ENC[AES256_GCM,data:7dXdWJGOxEYR8zmAJfHCbAdm0HTr0qoOrOYj1pK5f6OtJ4mLpRAiJxXWauW+TI36Bp7qGGozdhPJB3tCQT2c9K4tppNLvNPfxFKHXecBsYL4NePI0WEZLd1aPIunPlqnpwL20DRJ14oayB8jt6F7Z+HM+LISyvli92G775RUe4SxPLhIoHvn8kgFpGn0CzmNYEnQoAB2WszciAUemcQxf0TOiA0mDkZJwMhBOyRthK7+huY0uYqx83D8zash1hOYwDQVkhLCba1B/wGH+w==,iv:hSXE56SPVkyN8KffHq6EZSE1r3xct646PW2Mrc0tfvM=,tag:/BbHxH/0pt2A4x8xe2fdzQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:1S3n+qk3dJAoOiKvl4RwjEOrhTnxCe/iJlPgCUk48xpzCLAvaCYAYKZ33LwennTrKJTkyudwGvoitKG79/iezrv2mglSktbSQqHr856fXzZ1sSWk4PLlu1ynnR3bWu5aiIeiQG2Om+jM/VULafvdJOSbL4ntnn/TFn+eEg4fWIMVkOVOjUBXfbui/GnjmQu1PKCWshr63cYGqTU4DzEf3uc0PapexgJg3o3i,iv:IYWZq6IbzjKaPLpbxc4OcmasG9DpsCzusn5Nr5hICVI=,tag:5tUMGfipYYhxn0HRr1m/sw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1agltukf6ellg2guets9gq4th2nmunc965uflry7fdahtj7ea8uxq8q54ae
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBN0NuY2tqdWYraXg1Yng1
            bTZOMVd2RUd6THUrWm5PdXlWM2NyMWF6VDBRCnR4NFlPSHl4UXB1VjlneVFyc0ZD
            QmpPYU9IcHBXYUZxMUxBZjFqcHlFTlkKLS0tIGpkNGV0Z0lKeUl4QjJ1YVdZV1V0
            TVlYMFBrVENOOVcxdWk4UDBXaUZMaGMKUP8ZhhInw0oZyPt0w1fmw9hjB7bicEsa
            VhTUiY/8e2BJP6a1pNE+ADrSRVeYcJL0M5AtQL8w39TYQhJHKSMIeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-30T02:42:12Z"
    mac: ENC[AES256_GCM,data:tQmqHEII6DccN7d8AkzWmBrkvLAW8tYaRp98cILo80/RKuhL6cSgJnPNDYY8QkuWEVA8t6iK79XIGj4ysSzRtn2Wj1p62faJkEq2qbeGQky16lIDFQA8OKZQ1kTGtrTGbhqV0kdhRB7i6mhQdRGzyLfViBdhL7Ea6/45yz/EX4o=,iv:WUO3FxqW4Vh9vVbyjsB8P9IM81Lr3gn9a85QQZaNx3w=,tag:S4vWXBcKMUwVaRs9kqtwwA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
