apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:4ZQy14uOo9gTzIspOXLnbUuQsSVWIDq4Fz6P5JXTcdPuIkK5lFAY8MEpj2DagwvhiFC59xaOaD0+4mNx0E20FnUvXDk8bYEprYnkLsLDHPyyhq04+DcM2Vv9T7bVPfPmH6fbqHARV4NzqjGIxNyexADlawAMggaN3Q0L6bQZX6DwJbLq7H0Ly0CHwcpzEQWmtyDb9JYKsP3cR9CAQXZxrY7peST5lC+HriBvOAeCzjHqOCijhr4sBjf+klIaIFRStUz8Zl1juoX6ZRnxv6OakNVHnKZKnJkeHHAiivYuyMBPIdaHPS0W8p4VvvP3W4CGE1OOcQHyKtOSHTe8oFW1WHhBWL8l0kB7Qx4uQrhCcH/9CJmOyr5K+E+DXM7kZ0TY,iv:UbJsG8tEYOI/rUSxiZHxmIwZ/2SdKKeZgQowUfRUHkQ=,tag:EuXmOq6gMWKoqIh4fb1o3g==,type:str]
    identity.pub: ENC[AES256_GCM,data:E7eUqCN1o9dR+Zeepkm7ISnkfcyK6PaC1PSn3dcoTQmcSfj1ngCFRTSo1n0Uo9gJR/yDq3OWmTU/Dlg34W6BO+OMb4n/DvBdj6LiPZjo042//DM15XDSN2A20DkthvIbfkK1Feu8ObNAOkeSPV9s5PpIuQhywTa+gkHhUnrqrnnzXfbUIlFUlXf+Y/BwWFSGV4fm5wNIpRonpSIpA5iYkl3uJ1T8aQp9N50u+QFCEoLbUWMaEFc9YxrnW6wdhFEnBNBKqp9zo30gibQyPA==,iv:quj91jpJikjNC/yaU92mAdeWq/0gY6ENRh4S/WwWZSw=,tag:zAp2snAguBLG/vWdZnmy8w==,type:str]
    known_hosts: ENC[AES256_GCM,data:WEVJn0v+ZwJr8WnK6t39810mWJCAXp09UBxwSm2FIAqS8IiAyDctuCNeEGXQEMUEfNeigYI+lwBSuGa3oHj2vIrZrZIx5xdmaqjZbRj15B9HyY5FzLhQXtShLbf5+02koPy3uzXiFtPgRJWthBjB35MZAr4uso0WWM4JLQ9WFcFvtbklIbRWJ00grBYIBLdXgATO9wV8ljDEBuWStppEtwEQWKE0nOXmT94d,iv:Df2Z0Vf/Kpwkz1L0JQvLKBQufj1EHpxK3CzRVGc2xwA=,tag:D/jPTf3G7NeXTzspNy94SQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1agltukf6ellg2guets9gq4th2nmunc965uflry7fdahtj7ea8uxq8q54ae
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3UUhyME5sMWgxeitpNUVx
            L0hoUzBqbllLbHdUb1E2QmI5MnR2MlJSRVhRCmh3enIwYnRWVTVhdFJRb2NvaktY
            bEdxNklZSHo4WS93Mko5TmFBQzMrK2cKLS0tIHpGRWUzUHhpNzJtTkQvS3E4Z1Zv
            YmordkFVYW85ZU10L1JWTGNlTFQ3WmsKzdTgmUlbBPNlkgc5mWDd9vDhRo/dFUAi
            8BWloAScz/gxbDZ4yz7c6u+OoJedPoywMXSMgPyv42sWWyCbaxoRIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-01T23:50:10Z"
    mac: ENC[AES256_GCM,data:59+f+6st1Kio7r7hxfHI6q9wrH1fUtCbfSoeR9FETpM6InsS1ggprnpTXd+lQ9XlzYJ8KhSCjQusFg5o11ZOxvsMGPqhNgzocDtPUHCQVJVYtA/2BHC8y7heTfn/R9ratiAa5TBgUEiS7vh9xtMEnCSngw3wh6Tqr/NTGS2j+6Q=,iv:wPmwEeUAEszTJMMMUi+1IcdBEhRaWu8F7TCMUKsgAig=,tag:8xIOhix5Z2QYNUC4Wizgsw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
