apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:D0byA+HC1ExfwaF8DP8STPUjQJ4zQkA+7V4/qxmsoYB2wFfymJ1Vw/kEfrMmKUatAElD17Uxvd5oMfXEl7EiulcHhHKc+TFhkq0wxVzpzf+8+Ig8eSYkbH104D7RbC592kD2OTEXYnVONRWefPYMUB1Dm7nBvylQLEMwTskjQ7KpD6ztAQIfvW003WR04Yn5oSH0k4HjeuiNyrZYJtbsv4RDy2t4fMNAdLO8UeJKr71dnfm3I5tmYOHOAJ8JFuw8w94aba/jK2kl3z1HgDVh9R2gFBxBJ5nYqaUDki0RxSU5OaGuk+MAOnoL2A2t2F/EWwFKpFtjshsYytA6/2sJaoY8HnYjaUE6fNT9XIdSOJNWNP9XxdpfhbMMvAFqM3J6,iv:6MQeQmobJnl8H9yg59gA902zlzvSY8Rw00DZs6t8vMo=,tag:f/V5ys+uqNt0H7PlO2ogcw==,type:str]
    identity.pub: ENC[AES256_GCM,data:WcHjndeeicY1dgKAGD8eCfJFm/7tp9+vBQGDw2m6pTGe5pID/LGE5u7qK6k02JF8hOwASvPELNimU9MPILfDwflqRpSKUxKykSPHj2Jw+KnqufTK6pTlSRJo1lKw+ptbny+0Dpo5SQwFKMfTfD6+GkXc7upL8n0OB633AKplx1tO9TtJEEIGfJepq7KO/yzjbElJ4NJeZxAJgjopw+0dxPBy0HWoNFLUsLApR15C13dCj5vGYjfWjX+ZM7A7PthFPqmD8rnvp/gc+Jh4+g==,iv:JO2QKUmwrshUF+iRISKjMO8vVVDdlHdKSP0GZ69Oen4=,tag:zOrAl0+Y6kuOtPdXqDMp+Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:n1+H/0N1BiliwyxJzuYmzXkNy1AodVUUvRDmfCK6LcUAxJlYU0uKbktN4InudZbv6xzEr2QQoIWrblUZNzW9gTCxUpcUrHKPel+VlXFlFEYKfBGY/Nkfw5/yg3nv0tpSYNissiUf5LViCN6Hh+MoWDXIs1RVMMTZEnCAp3EzmfTvheJSKfcnX0LZlEfG6aJMDTQCBrJjpjs7qiQod9aXWD0k+aOa0l2fUoFp,iv:3SnT/hPha0TZHEoPoWPiSPWWrl/D1dA/qC5u61AzuNo=,tag:E0xOOLVSxPhH6XA8/Q1O8A==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1agltukf6ellg2guets9gq4th2nmunc965uflry7fdahtj7ea8uxq8q54ae
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0Rk1iN2F2bFgrNjM1S3Ar
            MmdhNzFSNkdKTUlJN1JmTkQ2bDdRdVdlakhBCm1LZjhUOVZsYWxnMHZ1eUlJTU5n
            aDRpd2s2cysxeWJ3b3dqZGgrQXZUMzQKLS0tIDdnMSt4aWVWamxtamYvcmhVUnlB
            ZER5Y0cvSEEwc3QvTU14cnJlYmFwZk0KzyG++T5zwA1wB+GSgnJkuGOUmXYg3a5X
            /iUp8o3y2xiL3dQI5EDBNV+4+xrVKYlETfIh1oFcqXGCGqB9BPz7WQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-15T04:53:44Z"
    mac: ENC[AES256_GCM,data:wirBGCh9ScE4s6L7FSgaoNgoHGjpvLICY8o06dTewr3sw4OQwtPgk5thTnd5GH+c2YManMlttWsohIN+u15Uy1OXPLdxGhUJc6ce90/eHwsULYSneR4MmhnmzMlgMEY0ntMVo7MxC7XcjRpw6ZE8/gs+dTSXIH8QlmosWdIPX5Q=,iv:wSqpfEkT21KOcjCh2cvq88Wph28n5Vfm4yDnzpdIVbQ=,tag:PxhQxCD1bg82wtzmKnzzyQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
