apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:0rZJqcIXeGThRQcyUUAG+9U4gYPsZJryt+XWsQ2KGqb/dVkWFXiIm+kEmf0xrAhcveewEMfTYn5Ji+vbHfIZAC4Gcd3bxkWfFFuyUVBHB1CnDtYd0pLm5iIlq4YbIDiqjUt/qJ+SpWwfpyT27z/D+w7xwIHmF8v+BtIggF+vaBmaNQqKm/Qp4Wtqh2F8ajvu63i5o1aiWj5OLvgSlKNJER/5ZyT30fMjKletq27+czWcMOoMmzXGJr5FX9/BjIF+1Dp09rORN/cca2RdHW+bzSfmGOMWtRtpUeSHcjvrJW1RHXThotsV4rs7nD8oTIOmDLAh+txnsTBL+KURFPrpqnlGy8T27mNE3twxZlgiiS8ljHtbhdb1kZ2BOGVE3XNb,iv:PAvbdtCEmRvKIPOKtbgvft3zZzOj7wU6RKSxQbrEuIQ=,tag:xk3LucwKfaWzRLCKFDjT1Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:2NKQpTL9uDwJi97WaFuWJ4UOAxzlHwLFIQGM+1aZOUa4d/0RjBCsDkNNX3GFw0Iw7FAxEORF7UyboO/xuRUgFvVsTIMiEBFBooRYxmqLp0jI+vd5xwupwCM93waeaezHqLTfp6nO8FDMB+nF5JkBcAE0KYWgDWCILOr4RZPjFAkURgLLmGVu+iscl1kbmoKkfiuNF6NQ8IbjB/N9QNwu2MlCl43zZrGU6Xd8O+vRoguZ5N4u2GVjsk1CPc4iQQlYfGmB+4oHK7f6Vi+h0w==,iv:EYggE4iaYMoI6N5/kGPHAlO7JhHiIHX2sGL1nc8ju3Y=,tag:llCHp9a8BR9GnIiLws34Gg==,type:str]
    known_hosts: ENC[AES256_GCM,data:lrqpqXYgEZOLP6hZ7NwrxK9LTnKCjyISdXGgIvJM6xMnxgKb9BqxDFvKb4Oic2dhSdFzsgq9WoQ5G0U76zIJMf4jEexMD65v6FnEZlzN9FARmTd1RacCeGO4cAClXpE7eOmB9Jf/XE882FFPFSXJ2dU3TdWaq3B3uBqg6scnwIFYWVGHVe6RuvQ52ww2WDGe10fZa+LTV93ooMmx3g0dZ7ueFNJqyEC48cMP,iv:EPhJ46/O53q4p02Oke7gfLyIM5wQ0LjXWSlrziWl9/4=,tag:1J6zwxcbwu1Bsu54pK256Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1agltukf6ellg2guets9gq4th2nmunc965uflry7fdahtj7ea8uxq8q54ae
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBMDZuWTVQd25pWXFqS0xD
            cTdVWkp1ei9rVTVoU212ZnVvUE1xSmlPQUFFCndjNEZVNitsMTUrMVM0bktrd1pt
            eThmTEoxZjRHSEhockN0cktBc0lVQW8KLS0tIEU3anM3aHgyRWVkNWpva0luMkw1
            cDcxaE40RDNDcnAwYXZRQmtjcWpiS00KFxOt32PNq6GdY/Hqbh9uQqulG+NZp0vj
            bnsuLi1v5ZTV4StQgOFamhsv6lZMLw6KgOfzHWsa4m/OV7GvOnMrJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-11T17:38:34Z"
    mac: ENC[AES256_GCM,data:HRmV8Lgn3pIm5HKNWRUS2NvuowHj7J6eB5P83z6ziNgriPcetoOVsEvkGzBPNa1+zlnh2AOQYmZVBmNDc5y18j5TszQ4dSYludohHTj1CV5pf6DaBfCzFEc4WbjfzmpChHFcEvYwWcc4XnB2CcpukbdnBSjVwMcElUJHONbM/q0=,iv:UyEgxH94uPBIFnL0DF8Q3UY4NP03HCkorUG/UlMsPoo=,tag:KN9Z4c48NlkFzX65w8wEsQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
