apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:5Z7AdVFp1FMSt+PFKM4ACOsLqh0cpQYTeDI3ZmG3vO2YL7c0Aljylw/yZIdGieYITPF5c1BWSTxJTkdZywpXyyzWi9JxOdCPlP9ZvTUifZpYr9+K8MeQkwH2J6mKwNHTsC40ZpR5dHK5qAx6IAU+cRsNQ6MlnF5/wLCBFBgD4btBR6ievvs7HnrBkQyOaZVdOs7SqYrwAehVh9SHRg4Jb/5yw7tSD6OPPwVR610GbHUKNZtzOt7SNi1x1AOxuCsi/gS+6E8UY+RSTHXTg9YLKoj06WMcvOy7Y5XxGUbr/0e8CCffF4RkrUvchIz0d5tmmiI7d2YI6zuEXXrBHrSNyD0kB35q/kOcItpuIcNeyXyxOrVRQXmj4Xj8lNqxJHYH,iv:aXjDW3I50W/K8VXFuwWceHez2y3y3EJ6CcBN5pKFWI4=,tag:5HCb7nCrtelJ2NlhVihu7A==,type:str]
    identity.pub: ENC[AES256_GCM,data:X59ThCeu9RXCH7wno7tG3A80nRK/HURhuy3dnF8nuPNj+5C/AkWd8qh9d44n4xPAqP1Iz2SXlVObC1B3daB5qBqeLBjxobB/KCqzzh9NQsi5ZMpAd78I6rKiqo4OWr02fZVgYWGicDOm9OXSGWrO1Q6+FHUR8xSetRDmDIEBpgwC2w4uTOSm1tQi8glsiNRYT91T5YeZgwAeJeAS897kbofZUj01bBQK7x6qkQ/coZqvfNXojACF/m8Oc/nPD9ACwu9bmZFVWHcU94cxRA==,iv:pdtwN4Fmn+rwiLYhKPOqVaVIZi9MYf99zQmFCtpRvik=,tag:0FbOOBDm7RDvftn/9Kcp/A==,type:str]
    known_hosts: ENC[AES256_GCM,data:tz3bwpC/oHWqwxwAhf6aHI1fCTurspUjkuUeb4YK8ad3G/jKj/y/Zkm/ZwrziIzWtdme1Am+zhjeaw6NAoaIen6N7uuQmsT7Ywjl7YUjqIPBHoLXRfKXlyYwByXgqxwxoxQPtmACGUVlaE0FYtJb8pcbPfxIC7IK419ZUC7YKnPPKz+5SeCeKqG/KsElmIQ5GA3PKJIvzCCtI6AHW6+F4+SmaxW6ENRlep3n,iv:GFG4l29Y/5uoM9qTe6tBhQnlBHovGzNVMxeE7ppRBFI=,tag:hFEe3wn7XRy6j51WXW6nQQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1agltukf6ellg2guets9gq4th2nmunc965uflry7fdahtj7ea8uxq8q54ae
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhVkYvdTdBNGpLeUZaUGdX
            SFI2R243eGt4WEhJOHhhcC8vWEJxSmVJR0g4ClBMS0YvSktMbTZPRysvUC91Z3NF
            YmxWR2VXb09FMk5VaFpKR1MwekFBVVUKLS0tIFpHdG0vcFRkVk1keEY4ZzFpSUcx
            WFdNWU1PM0Z1UjJWR01kUEFoWElHdGcK8C8tl1EpYXwtNSPzzs+MIMvS/FrnCvAn
            yfwjZECFuRR4oaPYHzHSOoqpz9OuKl1yx77OwMYb9vx2g59DT5uPxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-03T19:54:14Z"
    mac: ENC[AES256_GCM,data:n6DoxBuXZNDujec8ABRy0Er6ppTb5dOH51WodeSXWfB1iU8OfS3Q4990ztrlGZjve5R85LQLDLmgfIWRxc7pCElYT3iLbN9+JvQAxx8ZL0p11SZOGEt5oqmMmdpZnBOvVGsp+TIpBQ+8TjXsZvanuKRrn7GJ+jCNwZUBA1QcpXE=,iv:wf60ws+8vkqFi5Y2hxU9Ub4djp82S8jwTf21UJbhduU=,tag:bCQXimCSlG9Wj+BvtDT4nA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
