apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ut3OyiPazK8+hOZGy+4WZpe8FPudfH3wOfVIiMEwemgAPzu7Np6Th54iywVb17itWAATY/mRgj3sHzEKnLXAE0ESzL6BO1FX6zxaUfCsA15fZMpfnKBBRViOmZPkkDL81IW51eIcG3YF2H52LatVLEVzG8h5m5Lwphji7Ly7zw0e6OBOkfiuxugmN+O2+HLFACdz0ttRy5J9oRA7gMqkQ8WO8xRyd0uDpw07x1MpgQgxRSO62LYCaswqmeQa2FCVLqkRwwAhrgbEmtaZpQEsXUUWXWSDNVpk61rjADeFEUafjTcdIWdACgr0Tnd+fOnvp84KBSgrhQq1J6ALSsUNeJgkRoqm/54zY1IxRm+/3wGdyI8/V24AuXV8FwCwZdl6,iv:LEHxRLsLU0POack72/WNx37sqYjjSA1/R6MzCb1kCTI=,tag:ySAms/tUWmyp1Q26biAGMg==,type:str]
    identity.pub: ENC[AES256_GCM,data:5DmS0E3Wbj4xJxZoM8wKw6BMpLeUX1aRx2VWAYgeVG3udqX8U/IZOEUdgDWC58+ERHkCqpfOe/CCg9OKrnzNTnmgkbN1G9z5cZp7/98FO5Dc2iWPtkp3PAF/W+FJLjjq3tCCP38dVfLVx1V5/Ckaof86VnxwjvyOaUpRIjZShOtmh84qk8uNAq0qC3uUHy9lRKKTfwvqMZ1CDApraWXE2k34OkiB0S23muTlJm4DmjmX5mCioNtJ0t+eKOILPTqVN3ZFLfz721/bzfo/ww==,iv:xycZDASCq+9ByLZ6QjvXzwUW7yGu6N7qZonjJ2gvlKM=,tag:dt6eDbid/OXhLi/Tk/yP7A==,type:str]
    known_hosts: ENC[AES256_GCM,data:IRnYvPoY+pwLfvFDvGsICLchiUcOM0ZQ5Dv0KiAJD1rwiji4awuQAzNVdmqkYCEC09tNtdB7+952U2lVt9uFMfW9uwEh686x0/6EKemr6NpoWApn3pgzLsBlcmbnCSLzPepoBw/liZpja7s4eVctIpu39kZHkBrROodjcBqyKbHrY2knJTtJSzHS1HdJCP0PIKmXkkVR4BA/Tnr1HRuonaBkrv8o5dz5LaWJ,iv:hRUd3BiNcd+klctTEI6cvhJZbIchwsrU4U3lUe/Vlhw=,tag:/R1T0CkYawLnFQqMVV62+Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1agltukf6ellg2guets9gq4th2nmunc965uflry7fdahtj7ea8uxq8q54ae
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3cWNEWVpuSDBTWG9YS0oz
            bngzb2FFY3p1TllnZ3hZUzRUcSt1cGp4Z1J3CkdOeW5pSUxjNHpRbzViL0ozRXdj
            UFNTTThLa0V3VlNRSCtwaXlmbDlwSVEKLS0tIEc5T2RvNUxZeWh0OXFzaXowcG1z
            Y3hDaitoVk9XeVJFVVBXdUVzdkVEWjgKd62Brrl/wGbpv8mII31i+SiOk15qQUWz
            GoTuHonyOIbl3ZAvZtUYGh5+ymhgfE6RY/1BMBRp4q4X5vIFJEMEfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-05T02:54:09Z"
    mac: ENC[AES256_GCM,data:ulwJf2MAjYZXvaFdVli18eSjg4w4nBmSPYoCwsPMPvlDILHjeTuT6ysVaVeGclxfLVnt22dxKmclcNsinZBLFcHgjFm7R5G41kgHVnIvMe4xqYKICOyl+aRtZf16CXi5flnsltwhAJWeXRfe83njXkoWfVEi5Nh534eaTgUKyl4=,iv:ZfS0qHNDbAldsYnJKjr93wMua6o5cLjsO79uYwtqHlM=,tag:/SVLPi3ZSfbZG2SKsnHs6Q==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
