apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:IJcU8opvfrexcy2lk8qtSVZzkM/+J0YeVxHOjGCqL6Galdga0/g1xh1KBRgcKn/Ps/a7rVB9RV3dd1wbtLyQq3xpAhdc9mD7rFlToQVkx3GmPod/bczoA78lJjlK2iiV0UEYwL/24jB4hPc/Dl4AAZBo0ftLWKWnKwO40puaCHfW2Zs8OgjxQQ4WS1sSwX112/CFZHye0EgwppvJeTSyGSTjfAPyQer3rYto1YbrQEJ3ZJ8LFSDrdqO3kqdkIE5pMo453MOnEQq8vM7ineFhKUEcHTUj5U/g4ERb+KfpCfTOftDM/mqSVtMg6a8m4hNSG46uq1g7Qx8X6MKjVC+HDWMRs2dbMZ9uqFaSsQxQeMRDRd8qesO1Z/Zg7Dtrt7qZ,iv:U8vwf6qRUoRs1imvarjpfczh6V1PAvXY+ODXB5a+op0=,tag:UvToUI+NdVzGwf4NgwwgQQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:Rn4eUA8UXHlzPX2ZALUDFqawKnWHPH0zpM0aAgDsued9fThhuV2OVWlOhDt09P3emV8Vo7bN5prY832pqCsTknzW0I0obCr8nELkp6IiFlFJzzbZvkorYeD2ur7AkUF2IufKrp5pd/DRiagZQB3+M5wggPjAcqt8RMqLLthEIn404Z3NkB4qbHaoGwIkYIQXvvnuNnBdVgyGejVXObSZCxzAjq6L4JIUx5yu/2CXN6Ct8BQWZrir1Q9f5BEYmdUswrVnbxeQ9yxHyPkFPA==,iv:ESZecpaNI6DoAKTW8lY2Uf0EjwuTkfJZOJ8geCQfmXo=,tag:N5OVOsfy6+qrAdZq7Ys0GA==,type:str]
    known_hosts: ENC[AES256_GCM,data:wgAh5B0ECcO0Kty+BEWbED4Gdo0RMAy2mcmryvvitiEvTBI8Hzd7IRAwdu5/aApwd9s9EwASuphkQAwLtiDeOGSMiysVgIhsknxkM0EHT/xMMr3lNuA2lShMn5ZWANJ4TWMBX82BOITu+6BuvghVfNnACYclKElaWxhLnJIcRXzMnuuIu3sNiWW7aczWQPrmvigKLgI+KO3vR/xiBzkif2hfu+BUyTZOOCnj,iv:9CXCu8yIrLGm8AOXh5D8Pk63uxVl48DvXYTXqOpZ8ps=,tag:yBSO+b1PdnyFJuWlBNI2ag==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1agltukf6ellg2guets9gq4th2nmunc965uflry7fdahtj7ea8uxq8q54ae
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYM25GWEdEclJ2S2p4c2FK
            ME15Y2tscVFkVndTSGQ2TjZHbzF1QzhBbndrCkN4QWdpUU45VVUrZVVhcEFiNits
            QUZTTUFFTkRHSVgrK1JoZUtYZHFZejAKLS0tIE93R0RQdm1uVWgzNWJIdW1CVm5F
            aE9KQ0tRY1ZzUk4wdXlDK29wRTJCUzQKVy/EYeFTLzpaOn5bZNSTyAWSiz9lTVQF
            QZaP4/oDVOc0RUh2kOyYoqCTcTgGfXwWCCfj4UrdfRgTSnLOAKO5zA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-14T04:31:25Z"
    mac: ENC[AES256_GCM,data:eGdzlmehEVlUyaGBfMylIDmeqAMxIfwN0ihaRHSweDfhEirglcFHE2kf0MURCtj2GlrSz0wnNVDjJpwJPpN7D1yAI8yLO1pH8cCPiAEe6+pQcW34Vw0ujBSRwzvq+mFElSPhF+g7ZQ4tq+QsZkGJPWBzTZ8pfKyRCJr4iJd6bjc=,iv:SsNgw58f7Lqka9wbH3VZXrYHPkMwKo7pVxWvzg1VZeo=,tag:zu9JoUI+ST59MPv2M7eyeg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
