apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:csKhpvAEnrz/cakl6hU0r5p5VQNT5tu6ZZAxZuxtiIVLk4htptJ+ab4IJcXgxey5C/5iEDNz/DJr1SWlv4nOU798eI0TMbrj6gCSU/CwVNTxNMQlyGtIxJfxGdlN4ed4vUHWdilpm7nNIdj69lxSXcVCrhzhwYr7wUizpJI/fjuRLEkfQN5UlEb3gucfOvxrSWtCghNHLTol2WM9IttK75RcqGtdpZY1P5RJnU5x1hndaC44In0U9s0AVpMzJdqp0ais2gD7K0lUvIrPaHUowlhsPHNdzO55O0OTIS14AYTjUN75G4OYGUpYScVR8/k36Gk/l1GktSV/fLEYOIfkZkMCUp6wm4jOyzsL9uED5v+8mCC7kNYfsJJD1bjaLGkS,iv:KrZmCafCZRGFzdGkc2O5TptzCZCWP8a8+xG55HpIqNQ=,tag:lNNioZ7wKOOamwhzRlFdpg==,type:str]
    identity.pub: ENC[AES256_GCM,data:S9Aggg01jAjEjOjFwAMVlcWYMbonRDQsCtQuNYILmWpISx707zSe73viCqH5F/skOu3IYu7cvst9vz3H/POXuFOaQWK3sYpZNTQTbzrImxzK7YR6Er1QYEVvaX/VyP6Dzn2wXLxrzrkUvJKmZ0CkXvM2FyZLuEK6/+UoUxRWQV2+ASFO7srG1zBfmwYC4SZRqPi7XpmFdEaNP+Bhzr84ejmb6MZDfB/REQ1gu/2pJ7nIfHftV2p5PtW7mrgKqXzn1hGMI9l7RCwhTbuvXg==,iv:cc9+hnvGH3tyFC7LuiSAnprKJQHqwWP5A1L2sCKkhX0=,tag:/49pXz8dwN/hFfC1ApB9ww==,type:str]
    known_hosts: ENC[AES256_GCM,data:+n3gzAJtIlgpTuQQUUtx0iyioLMhvAIDZTe7MsWSkA4u/DPu1aFi/wUcSryWet1b5ypK7E/iDPFcBd8kCg2obW9R0WxIOUGq9qx8FS4en3GjDdqxXy9KzXcnMzc+gm5A7gfRdO4KNPNsM3EfOdD70kHkw2LXFwZqqeE97Q0aiH1ZJYxOClxJA+UhskHtNcROw+afMT9dYOMikUmf/79EataKJtvhxRHWUP+P,iv:hQyv1t5W7H7sOeMxkzd8m/g3zdGBH+89TbRH58B/tlE=,tag:QZ5IUVx9BYXmE/rWbQbIgA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1agltukf6ellg2guets9gq4th2nmunc965uflry7fdahtj7ea8uxq8q54ae
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2Tkk5R2psZ0FqaEZyazcy
            R0dsd20xVURzNFJwWXZHcURZRXo0SzN1ekdjCmN6WlJKSXVHSWZSTjNJUHdBbEpW
            eDJzQ2pWN21LZHAvWHZ0SjNyeitzL2sKLS0tIDh4RXdVNDdXTEYvTFZJNjdNOEcw
            WmpVRzFJZHhqQllSQkVxamtnUmszbncKg9/T4oUPLljEwoKD9nnuRqkerUt9pCKu
            6IpGMWBFvS/Qu9RRTgdr1zWvn3NHHFHTXZ6AtAbXFT7AISDWsiL8Mw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-06T04:24:46Z"
    mac: ENC[AES256_GCM,data:GZWLNmkp4Az4MJCdQX2HzmKrhAZQoPfWePtynrUfQqCQdXl0gSiOrbJYS92yD4KuTmxKlMlID9xx68ux9rjHy2qWhSt8KPuOlfxlFHaBOmaipaVjGL9wJWYttJi+oHd43X8Mifi3sDjyM//QSGNvpKgklbOZ9nGtIsCGVQo85F4=,iv:ZcMvA3z9b8e85PIRV7G40mAskxM8U2Lj0v6Tf8RO1m4=,tag:wvLvXG2QvfTg5OkhUjfF+g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
