apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:4HCgmLcpnWv432LZUj6guRszHLlt2r8FvzYHARcN91fdQqTor1VMncadfUOvQDDeOXIbb0VIl6Qupl2yOEWSaloXcnOT76xQB7Kp1VHirCdk6JigM6lGMzLV3Mah/J4A6qHyfi4wcogoJZrBHMqTig/CJIJdeLyGcUvXelokRq99mNdJeb+pkzZ7wcOSb2Yqsj7UMyPgES1InVhOVHxiE6vX3PWN1ZeDqXnR42tHNdGZQWcpeloY6btxFNvw5+tefe3qqctt3yEWe9m4Pz2No3DNJdllLb6KK5R7Ezk6zFm5b330/FwcWsO9OW98C2TnXNZmTUXAekOOTuZs6QXPwPhixpT+0AU27aAk4v+G24Ay0AajZAyh7lpaSu7zLJ/h,iv:7KFxHl+/8KbNrY+x3moZq4q231gkiDGfNsbngXjnL68=,tag:V9reXAgOlI142EXXCZPmwA==,type:str]
    identity.pub: ENC[AES256_GCM,data:PKh4efgv/rS0VAFwpDqAkg41gtRlJSfzPJ5E7NxwH7M1UFTkGcwowo18qqTBQPRv46plqXdkCOM2p7rI01l2EPLvIINN7YJeWt9ArO5EjxU3Fmkl72ASmZ0JqGoDx6Ri99saxOFkIBzFusK5OLXRf79YmnUDDUH+vI20hXgXEZchqF2CvXfApgSinQwhAKPr+xbCCQs8OC22hhPMqVvvHLIe9PRwvWvGhMfWsyck7cX2DFq4SWtd7AIZf8y+KZVtlQKEeQw7kycGkKO+gg==,iv:lkaaDYHwCyLH7o76aQMeOEzqLE/Cgol33uQWv9uJONE=,tag:zr+oWYwQOHAxrETL9AUoDg==,type:str]
    known_hosts: ENC[AES256_GCM,data:ChRBPcjF9DczbDdSdgREPit2jS5YmeTZms3dB8IG7QFnBMy6Ka8t/J29ENDBKTyQvYDprgwMupiDJkxsf+Usu3w3K1RITkAM6aK4Id5gv6LaF+65aNIOkFr55CT1JWREvBqeBb/3F63XNUX3rIgl8QMSl6sa+2++cKNkuZMdaSQCFwSfPVMYYKAkVniseufxnbxz+HY7e9IG7cw+Mqc5SzrLldQ/kXN347Tm,iv:M5byCTnjwrbtxcqvgdTFqP6deKOizOatZXh8voSSslE=,tag:fm9xB5XMRkABilvdESb4tw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1agltukf6ellg2guets9gq4th2nmunc965uflry7fdahtj7ea8uxq8q54ae
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3UkRicGV0WGRYamxhd01S
            bFRTc3llVnBFRG1pcWRrd1dOZjFZeWtFWFNvCk9WYmRKc2dMcGtWSzFwVGV5ekZt
            WGhKR0lnOEQxTzZWaFpUcDltWDdQYncKLS0tIGhibVlwV3RPY0JjYmlJRHhkSlhx
            Z1VqN1d6QXg5VS9TWGpVUU5xc09Ma2sKXcunVhEWG9jcG1Qa4RFmERFnwP4KRI8C
            RoM8oXKDiBX0YnpZdjOPFl1L3d8mcDz5d+Y7bfQatgLPu3iPXKF8Pw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-06T21:34:54Z"
    mac: ENC[AES256_GCM,data:Xc/6l/1VHV2hwurWgPd+QY2hIByuGiM2fTuQCqX3E1Y+Ku0JHU4qWlw+M+QC1csAydd6LU+OE31yB+HqRJeYghVyQfRVJMfwysbmNcDbqbddDPGCbFlVudtJj8VYStrpcEcgMt2yrZo185O/H5OCGqElUeWEFDbu0IYCnQRIiSc=,iv:m0sc48gfzWOhhj8mVmq6xdUOLhbxPu+0ansy+8eHh/U=,tag:wLnjmjZAf0AW7Gf/XtvBnA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
