apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:izpMZzLzgpsx3RkOUuNxvLbMaGN+XqV8vXBXxcwR9Ua243xAMDGJlQAMywli7KLuQ0XhHE0PMy0/LmJttMcQqd/Jf/syxti4Wf0C21IUU9TqtglHpBIDUdQzjpaCscM89nGJVX+RnFOwQVeaTYGNoZL9FfIKdt8GkijsDCVe0cHcQvnFkwdCSBILx5rjAAuNXwF2dJsA8TfRUUf6+Rp8Lclk7LqffLQYltqupGp9uOAhU1o5pKCuuV0K/y7nWMOxv87w3fwn9LlOM8/POQVm61+HW9ATyi1MS+URB2iE/jBL3qrkteuDrnVz3XojTA6g7kDhaWhvv2i+6uVPX6Fb58ar8oxpIo10kOba1IkC1Dn36Gi2Fb5rCRY8CLxX6fc1,iv:IHo/TqwU8kpNYvqjLy8cBn8YI4hLpkd++AG5ITxW6HE=,tag:KU8TtryJq/BwLs0oR9Nxmg==,type:str]
    identity.pub: ENC[AES256_GCM,data:JQKhTMGOMFri0d0byUMPM+47u8dVClc9IQrl3LWf/T1ejOFY1PTli/ZkxhS3Dbv/K4W71wu9KmcS0Ii6Q/PKkyrN9lczHK6wKhJT7vUK4N3fvceqM9MkG6X63Qmzb0x79k0czLvDKOpgGLtVPsHahu+skEnfWdGaRsce2dm56pDLqDwM0ALTipaW27ch1YjrLCy33TpbYQN2ExL+EIiJ70yKeGRQ/GMWv+Zb/1/fy+4QFprxuI9by3CN8tjYpVepOea70Qm4ALZ6w0hsKw==,iv:MjkcXPH5+jK8TwGTZxHF45pUrDlIXmTUA3AlhxrserY=,tag:bwk+wUXeZ20WOSpRpIOnpw==,type:str]
    known_hosts: ENC[AES256_GCM,data:JxQwG7HdE+jtHVYJx4fLK5b+tCDYl0srn/kQh9PhW92n3nYoR1u+ssOm6gqyH+F8IWwRfTabhpijXaEWVRoT0v0D4BDmvmPdGVtuwRrFMSw/GoaYUGeVdlz2GAZ78swjJ44bUGIHUDTTAwmdwAb99ffoGDx9OvhtDyadVuA4Zgshegmm8cplSyAxLM1aOi6G+zNjdZQULfmFHPT4fmSauJDjnTLGs+EajKcD,iv:inLD7gycZRPsClTQZLRAdPQYdzSmpdXAVlFfS27r434=,tag:XLITKEmY64ocRk1zB5/N7w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1agltukf6ellg2guets9gq4th2nmunc965uflry7fdahtj7ea8uxq8q54ae
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0cHloVlZEUmZISWh3MEtX
            RXJPRlhRcjdwcGt6ZC8vR01FY3AvcmExRkRZCk9JNnFqYXl4MURhSVYxTUN0ZmVR
            VlptbUlmdkYxczBTT1FqdDFjWnF6WUkKLS0tIEVET0ovdjQvTjd5M1ZwczBha3ZR
            b0E5YzNudEtCeVQ5ZVo5V0l3UjZKL2cK3l/nIDpW+rABwFw1V7Sc9z94GPg8MT6+
            Yzie+/JdrM7oxmZS/iERLpZ9Pws9/4HECbLZIVNr6Y2rT4T/uWIPcQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-22T02:50:42Z"
    mac: ENC[AES256_GCM,data:PTUbavFavsfRJu233lrUSFAchhsNjR05bkxn1QlWj0gDv0PlsnFwag6eKOp8USDmyD6cYcfLiI8lyOHthJC7yOSFy2fHMwrBoHqbpwSbk8hP2kMapNGIKnu4swQL1m7Yd+7MJkniC79kr4xmiGS4XiZmkfxn2l7LlGt214KosuE=,iv:UGUSiaerAQbav3Wta7gc29HJ8i5w9WcdxcB9GnogETY=,tag:QpNBSqDRtquHpUqSvMTk9A==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
