apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:VvcOshIYsfmuhfnkO++WWzRDsAPE9j0Y6KZrRYXHGMGzpvtloutFRKdRAmzWB7dRbiQrzXGbx4bORUbsYpZqTlN9jk1Tj1/M4bH2pujgVlJvmeI1CTzzjPWoTRsesIWY74U9zRAVvOhIz2ftsBEd9l2JiB4z0O4G67t/uPz2mx3qIJjvN1ucXpwTdjiX8Oa1qBdfTrS3LT4QD/ZVl9yYnB4FHbMhMzzGypd+XwlnxfYX4QSl6Vgie9ZkXfRtlQfwAB5T5y4FZ7MMZjINhvYten/HHRPvnqx9m/a+yXPf4vWmJhb2p6pGC063L4AZf/LU23QorQWB5yVYJj1XNyyLMM4o0o2qOpZEkEIB583IFXx0qvsTXsl4dUhrZpWoWryz,iv:CXJKB/4mIyVBIpFRDLW0kEbuta9GuFJrVPdq/uRQmac=,tag:sS4gq5Boun+rbgHgw7uzTA==,type:str]
    identity.pub: ENC[AES256_GCM,data:ZmE7IbWtdaW9t88/OHu95LNFmOXqPqW9DkZLIDLPajrKBc0sS0O75x3ANAh4qMKGga7WVFdZ4xhu6NodeX+yDGcrhp/kaAiqWPc+lw6IZTPWYR1AD+tTdjLt7R521uR0LrPtCocDX39l6xbEGlkvaJv82dPWrvUDUAqwelqp8AH36ETsbPYgPSrv+lAsWVWAE5npadeLggvNxoj698VhNy5r92N+2VC9HlVmUF95l5G4OxJyHTBwn+svVMjn30fBMbivD9mz/M6MNl3lLg==,iv:WOKrmKTyDBourCXZtULcdJnvAZoaPmtmb7IBjUFgRBo=,tag:dS5wZJpiFcYV9jw75VyhLw==,type:str]
    known_hosts: ENC[AES256_GCM,data:yx9JU5Luo/88r1cieB0dv3dgiNp9sHLg5FCD6JmW9IedR76SeAM9AtOcWdG7Gi+yanNn0jyKEkDMI6anCq0qpPW4D7jGBOiYqtGOR74804MxIU6XRxR9B3P9SW74cn9GCHWoLk27DsSiUvo/TzH1OlwDH1ASzBG9Wi4hA8vJvoWyePKM3K1ZpW6BgtS3VzD/qFMwH0/lOAVQNV8rSjXvPT1Uq2mfznko+25I,iv:2Tt4oUAwX0UnIPTPX2rpNDaecMSs6G2AmMqzlAAtt64=,tag:2eyAQOu3Sr1Ax0PJHJy/0A==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1agltukf6ellg2guets9gq4th2nmunc965uflry7fdahtj7ea8uxq8q54ae
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1QlBoNG44UnV0V0paaWtt
            aW1kQndmQzRPZWt2WnMzQlp4RFk5eFRXSURjCk5qUGdtY0gzWmd6dzgwVUh2VlI0
            NXFCUW1QQUc1R2x0TTVOYVJTbWhpR0EKLS0tIDBzTnVBbHNJdE9MZ1dETVFIem5T
            SVRWSlNDTHhWY1Q2aWtab2VlbXBpancKzhzmDoaK/YszbJke0ixO/j6cq8pEtiyu
            XhZWGvdMfzJ/oFXtpycGqvaEAI1FwpAFBi5+2Je4iGCEuzKLDuIOyQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-15T05:13:32Z"
    mac: ENC[AES256_GCM,data:k6xmqOnRqYA7k23U0+Yuj3SiZLpqHDAG2DJl+3jxL85bR0cI7+zrqkiWUn+aheF/qG0rvvr7q65IVkfSA6BZJOkX6GmugRFzR967IdItgVwWsk3u4AZHJ/DXQF4lSqP6sIF7zfzXm5uCZwpN1svw6P7tvxp5i8nt0qeqt6gHVmg=,iv:4Rw7KHLbFlx+tlTLHgp4+uRSD49bGRCVTECo6iZmwNw=,tag:Zu10nW3tyV5Lf3YFv2akQQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
