apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:so7XV9LH3aP5pLHwnd7C8nvxRVET3janFyzJuIlvUwU7UsuMZcw+gaoOBxqdO+q4aveIUqoj5b275YI2VqqHx79J1+45fYeppMemg5h5uW6xhgOgKtB/stGzksdgyzfaNXbYGj4V0pfuNrmCxEUxHcDdOeRIj9aZE+TaCtpIE8etnkq32/TrIC4KvSO1rdCY3qteLT9gWs+tQQKDD0K71IuD5j7fEGft6sdC/f5w+g/xF0In+vwO6pZ2Nw0D5IZ6nIlk2j9zxjM2H3BsPWtcLEg7VG7551ZxCAPz2t6T9ygQaljRTWHKuhtwjLWC0/U2duBckPDYdOc5By9e3YOEh8URTBYnTJRST6aj/tgF145LNuip0Oj5hkq/NZc4q6ke,iv:991oIVTqvVQzwhCyL0yRTCCAMn+jUX5eiYdtQ4dqRBM=,tag:FXY47E/ipVDjfZvynGoHqg==,type:str]
    identity.pub: ENC[AES256_GCM,data:Rfv0BhKwMAbHL6L4pR2Q32AxT1IN1k6y/JQYQbn1JwKZkdyQtq1AtwQSRc3E8/IvHPACVcQMwrsfJbR87Oaq8w0jv64kiEZD1PdSxWlHL8XhzvTWwBn5GNIMbh/XMOoQnVv8XrnxXdBvRevsiLDAiVZGVZ8d5HBl0pjlerPoHP2x3f9movmcpVfoe4nxFQNsCfDgmM2JUSaoo44B9lfYHHNNWNfW5nCakoV/lpFTOflDy+aG0NKVwmCEJYn57cItYnq5zG67n6bPxg5WfA==,iv:XUPINYYmtwHNVPPIXBlm3hSrfzjAfQS/vLDzw3nwPBI=,tag:9LoJgW6NgGGE7NmqxUxIiQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:odQcONuQCErr/V8mcLowf7bvPRVf1wMzXbXWGHTME5UuSHeZ4m3inYZ2ygxa9b//Ryk6aWT0LuQ4b4ht8xo36yl7/ZXeT1P97Nl3Z9HFuFMRMuIRyp1WygIWNP0L08B54nRrFLyd/34b6B8mNdqgijMQ3w/ZeJxJDPA7T1roQCbcTvjMZvbXqBWDh/FzaaBd054+ifPUsu5dmhvAJ9lMrAqsP4t5NIDLAq2I,iv:+b+Ka+J79I18Jczt0wJsfMjNK19M+JBRCuNnzxunhPQ=,tag:821oC/X6ZCCCZdEg8NcTqA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1agltukf6ellg2guets9gq4th2nmunc965uflry7fdahtj7ea8uxq8q54ae
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3eXA3cnpQM0xJeHR1Nm93
            WTRIV2pzNW4vS1UrOGtWYzdJZUwwTlZ1VEVrCjJkUkRRT0dpVW9hZ01UcGdScWZE
            b0dSRVNVbXpRVkU2Vk5VeUN1RFhTNUEKLS0tIENPUXd5ODZsSEVzM255dzk2WUxV
            akg2RGxyanA5MTdickpsL2N1RHBRV3MKfYsqzfoAC8WDXiuepk8ZR0APHZLP9UuX
            XMawXzqz/aYtga3WC1Lg/zbtM3oF+2pUYhMoUSuMognpiI7RL7FnXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-21T19:26:22Z"
    mac: ENC[AES256_GCM,data:k7HPyNyUO7qAKaKcRqMWbMexx8chPw1fs+qtvQ/IwoPUAnNcYGznkaRifp6qBR+6sGi+9K69WOq2qGhPv/2iQwoBqGNHpJD9uO2zv2GXD9ghkuWz53bpup8eDaOscp46aHjQrUHE7Ds6Zxz0Kpj+N1YrADJ6K9yYdVQnxQTMjRw=,iv:YuqNXGRCFyXA2IODRKYXmt2lx8KzxTdKgmNvvBqKD/w=,tag:RYAEJpukoVadwon9bYRKIQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
