apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ZHPOR14mNDsqleTnB9SIJFsFp4SxIkpHmVIAeqb1dXK4zWkAn1D/thdXvlpAnP+4DH9Ki2sKEa0/Ua/cm472YmmDI0QYwCsvuy0NJzIOGAhiYyI88NjaMKKMAvAMtH1Hx78b+sls8aFqLPmiqcfNNZJLX3LmuW0Ytwz5CdfRiIqiZ5W5z4p8TVTz0vX5YHhg1ppJD0wh5r18HcUEZP0QYSq5HOKv+ijht+ABPSJyW/GAgO/Y9cXJOTQZAKx5HQ2KqwLYhjECmUYGeGSzGDutC23T/6E5XiC9OS0a1wVmywl5MxhYrPxljwsXIF4kEVw0bk04imy+Totovh1vDFNx5j4BC/b+fnyzyZ4kmO8Qi5PE4aaY4ZxfP6wEXEOnGaPD,iv:4JaGh8V6RpdIQRc1OFyUU9edvA9Uskxjheync6ydEBY=,tag:9LmvG/PbD6NpLnvMLdvmIw==,type:str]
    identity.pub: ENC[AES256_GCM,data:X/fn9xTFT8mjTbQjVhPWRfnyXOBqYwg7HdQYZiXTEEpoeGRbDawv/CD/a6UX6s5sY9p/CpW9TYOcrELnaiJW9oDOejTQx49CwafQQFH+zUMddMUIIeB7Lu6+DwXFYGmlh0zObDxD2sLPjik25v9ecP8WFjROqnt2XAotC9i6O34DQT4xkGgBWSaliM91S5OLGtoTZDysGar55ZQc3g50x79Va/TTg4sNUfL8AaMOaI2DMFL+1OU4z+yQnCftLmy+mMymhMlQBxngMpulBg==,iv:IDC+bJ/mdRveGlm/1WwGZ+ThO56rJFRwciRRJkMVz3I=,tag:Bi3pxEAe3+fvfmSCfrPBdA==,type:str]
    known_hosts: ENC[AES256_GCM,data:tDxUL/dAtgKi9NU9gph2NLduHEMRzDPY/xfw3fWykHUTWdXNACxEQhTFwCiqtnhAbKOYCCy/LaNX+GB0mh6oB6MrhkRmwaNYRNgnj9JAPOqUs+Fj76o8s+s8kmWRgWOy19b6/a0MeEfQsWaowSHGHfGciNsqRhorQqm+zuSBvNla3EEjUCEh/kjXKL1V6mfNH1HyVsY5eveYZr96AKbsN7MQY0E6yDVDLgMT,iv:Mx9NCZFIjnAdq862mRCubBaCJHJmr4vd+Ye+6qnlP9Y=,tag:2eXsZNglERQvZ+7FGuAMxg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1agltukf6ellg2guets9gq4th2nmunc965uflry7fdahtj7ea8uxq8q54ae
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmaThoREt1clIvOC9Fc2tG
            SFlMSTA4eVBMWHZJRFZteFIvbkRDbUFtQ1RzCitINUFGaSs2L0lmYTVlTUpSVVk1
            S1dqM3RSSXo1anBkTGZDbDVGYlJIekEKLS0tIHpDNTNNWE8yZzZlc0FOZytudENn
            ZnlUU09mejBhL292L2d2U1FGY3hteUUKM7IC4f9+SuPzlm/rjjdykQd0/5uuvYKA
            PLGBaxsKGumdwDxDDj232bk2MI540n4gStpOeYyVSHCj2E80lULhjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-06T21:30:08Z"
    mac: ENC[AES256_GCM,data:cSS9gn3x2svVB+fl7QT6dV6SDbKNvBu29KypBeD/4s57eGd2Hm8s+My7Yn6hHYL/2fJ4j237rJPk8B6GfrUpgGn0f9wX2Ks4fpIHOMUWFeDu2iRyoB96COSJqk+NOdFNpGVs6idBqjq+V37+5yZobMliwJw+U1GxmjPr2raos/c=,iv:9dU6VsfkddA3h/70A6rVOwHGxWg7/RMPuIczSWqEypY=,tag:w6q6I4Qd+CDiWXEqgdCyAQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
