apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:vLtmba3i1igsgvCrIuoLQLkawUwjJjLAVuFgdCbdJDGjE7f9X9KDhBGSZA2QMga4skAwaGdQVsJ45M5w1fszUwvgf3RM5I2q4Bs+VJPvlFk9kFV8u6mObZgt06JLbkvHUcuBBsLLPpkzls9Djwz8Lo3xg6v2nLz39lLAMDDxrqj9rEeTRCc+KR3a46768BbyJaMEn5Y3RJHXORrltHVVWK87aUyxuPhcFq2RaZWZ1khANe4/+Bq7dPxrmNkCEZ29aYchtvRSxsaM8JpZweJqyoR0gcFiWv3wVthmXSdh3l6wUEwf/BLzLuAudeW84Rjd/KzzMfgv2hP2Yx7ZhzyxFUAPlE9QGGTXpIrtNgiFyOfSLnLrC2Jg7XtyHIQ2GfH2,iv:+GRFRJywrJErMuHoTJ2L/QhuhgjSCPh89EDg3H5SY9I=,tag:yyJK11W7CTnnD713raWjUA==,type:str]
    identity.pub: ENC[AES256_GCM,data:oCd6AyhtQvR67nAjBcohZFxto/XkYGE1jYjJFefPvhUNEVmE5Vf2zeBUDIhCb2WY5k0NqCKe22R6wimqf9HOEDufE0gIkUmG1EFtwIyxlX6PIlXd5jw/ZAxq59SPRVfMDCqMlza8rM0UHDIjGkekp6sZSA67KcuGmgsOD0XCiZek+ImNLhOMNJ79K9hV5RxoP04ZupgHp/QNS/0v0GUGdspB+MUZ/UyKea4Lx6SEXepAHE+DzzDMxRQ59M/JChJmnUxkpW6cXyPRYpOdQQ==,iv:KIqEdJylWbx3czqjS/mfPZ2veY8VeSzJfWJJFB3xDVc=,tag:zMfRhncrLTHagfLtUdV/nw==,type:str]
    known_hosts: ENC[AES256_GCM,data:IAWw9ix7W2ekBxW4WUrCKzLuqkM5wHEpyzTEi5TY8PiGdu9Pe9SZhCG4f9pOAXE4AhB4Ctzv9LKGq58ulBnXJdN9Ndq7tntrBO61bf+mOFfxopQz4xTvK482bTVd5xm9dcMRNu3FDGpohwjSuMgqGQXpSCN72dUw6EsBseVAiF55k6b1ijMWWcUU7Rr6WLn7WFtpPe3Bmkml9k6CT1z+ACewqwTINa6lHGzF,iv:zg04WsP/PzOEmUD4HLLt32ufKh+mi/Rzjwke/aGSsg0=,tag:QlSuHkrQGDTxsmrx2k83FQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1agltukf6ellg2guets9gq4th2nmunc965uflry7fdahtj7ea8uxq8q54ae
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrQThZN0lXWktaajJtanRF
            cjhUa3FKV2EyVWl6Q2p6WSs2NTA2c0tVYnhzCloxN0k1UlgxQU1uU092N0JFQy9O
            bmJZMlF2MnpkSkpoT2tZVWE1cThIZkEKLS0tIFUxRkp0bFFjTnA3NS9MaFVrVXBk
            bkx4ekdvS0lOY0h2eFNaRjBOeGpYZjgKAOklrR+tDNtbk8mvztdG+0hFS8p0Tr5C
            XJUY7YfKYyo0mhr83C95gNuFzoXEOKa6fmhOs4grvdJD4/zJO/kkJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-26T02:51:21Z"
    mac: ENC[AES256_GCM,data:fh4ZB5pQ6Wn6JqujjqGUDlhklHKceQeRUHdY/HqI7jrevQYz/YY8V6bphtWiDtHg6m4mLrdtyCiIjTjDicQJ2Wd9uTuhyOO9W7eEhuJsNP5UQvWV2bRE6QS5/K0ObXUYl6Fg+m63m2hCK31PWD/xPKMcJJ4MeO4cpWxJ8rUQCzI=,iv:1xCUkuKZgolaVdKSEA3AXX60C5AqWytc/Byae6qMqpY=,tag:0rDpYbZBRQ3OvJKMOOuvAA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
