apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:4ahbCkCXfmjX7S7rbGjiG9YDfxpidQ9kHiNtwzrHWwsBuQtIVyyoF42LXBjnoJtKITWWDGPDamzUUwwbgfM3X+gn0iEaze5iyUzu/OuMZueeIfe6cuG12vkmCFulHdGPLa9Taf4ehxyd6jFO1kQkCTYmnFOKQSg4uqdjUboRzBWwuist7cq/9KGVUIbGxUHcKupF82mVIKPuoNHHHnBErP8zSM17yF0dkEm8ytt0oY+GNOLuLNCXBMKKo9AubFRpzz5qTLNtGyQrFnfULeBkzCsS9RyASM0W4PSM6DuKQRiBYB5gvMtmoPvHODXdE7rw2+R1IikSt/v9UXjQR9sBDfKaC4POSlBZPrsseJJ0842fi5RrHqc4RkccHk3ukzA4,iv:X13DeZN0WZXtTYdzJM2rpIhjUUXDk5jqLO5p03LK1YQ=,tag:APeNzUgjZoHOnKyhJSwV9A==,type:str]
    identity.pub: ENC[AES256_GCM,data:umrQ0XfzBOTo+4hPSoJ1GSKw31gvNoqJGGAY0Mmz4oYigqml85R+kVWuGI566SDyOXNTjbFMS9apPmaRm/IWAlU8FVZrKEUIY9XwqkLWTtbOkoFn3d1Du1Cy7lT8jg55Nj0WvYhZEGZ9NkixaoFgMS71eOouJdXZJ5HlA9rt5QKm6Z4FVXT1OxwLZ3shJmT3W0eLGkp4zCZZO7XZV+eCjyrw7n4WzCVKKuw7cjfCaJnFkVBwzKyLOhfzyxJHgx+SdLwuad24bZMezmOVrQ==,iv:EJnp3yXIa+UqTr7EuBgW13u++kQSEmUDh1CPNRC9IDc=,tag:OZA1a7ZdUMprwKqV6gRsgg==,type:str]
    known_hosts: ENC[AES256_GCM,data:5rd/mfkRLQlYJffRf7SuU9PCDLuHx66ahBxnOZdz0JGmI7TU6O0/fLZqAnzoBLo0hsnaKVcakcPjw17SpZEn53UjmepP1GCiDzDYIkaGe3cLnBS7jLL9NKAFMg1swmuHXEJbPRCcdn6bs9q8VaVUcKVdZFBKxalfjhOAqdtf4GQJVFvhRiT5/rla0tkk1rxpJR8e07U52Xb4NGe87zr0W0NSsxJMlcE38scT,iv:5EiFVFAHZCnkOA6Z7kpjn1zrLxrcljwrq+Mleal0SVg=,tag:9o08l6vo+ckZDWLgbMzeqA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1agltukf6ellg2guets9gq4th2nmunc965uflry7fdahtj7ea8uxq8q54ae
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmOUV6TGkweGUzOW14N2V3
            WHoybnB1OWsvUUVYTkJ2YmRiSjA5aXcrOWxzCk1FeWFFZ3poWEp4SUZsV1dyZnY1
            Z2k2dFhhb1VJbEE0M0l6Qld5NW45djgKLS0tIE9DTTY3a3JISmhVTDFZczRXTTd5
            ZCtvcklGSURiaHM4U3VBZ2daazVJdmMKqhP5VmN7WX7X6oU/rquf4iwrHdHteGOc
            bGEd04ryJUhWV8KPuXIOPOlpBnzXEk/HLVejc/xs7HUyAVg0kBRtxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-26T02:18:48Z"
    mac: ENC[AES256_GCM,data:l3IqzULkC1jtnrqDpPlHRHhNDCC4kX70u3EeWiZcI8uAGxI4LDU/zPcw144PCwq7VMgZVciwp8q6Lln2f/lSm3dn7BNZUkNpZGXzWnzWKLN4ezQDCrO2KcjYRiGAvgqKtDadFzmXEPv6Kvo/Cq/L3wyEURf1STUEH9nlvOwyIYI=,iv:67bfHrZ3XRAGpEDrJQdHfuLa8rT9w2lIRr2r+6B0cno=,tag:O3ZgAa3cEPf4LkIWeDNpfQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
