apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:tBseWEFg0cKzp4i7iMaiij3s0C9Cl/2HolLs12xnu34BTp377hOT49mSI4KWIMshLKvpML77wWH+mp3nLHh/B3yLxB+JYiRbVe+2mFnUcc3NXKAKO/Hm+0gIXQJeILKAJ9vp/iadvFh8XC165oacayfA1fY1CnpSH7+dxNwO6CYZWfcZXMe2f9RCtDjhY+V7TPAISGZrWKqU9jg6Bz0Yj1JvwA3Qa6rTdp2C+KrzbhAaWL0cDFiNo3ih++c24XRiM2e/8fG/YQrjhb0EN6GPC5Ggy0LYmO9SoxQ6B90f9waR+1J+zzKyiioQHK0sRpLwDjv4rnle6+6LHH3Tdn8XNTrFnEN4EPAQ7Hm2XzDwgYhpTmB2Xh0iLfM9nj5ITGGt,iv:bw00D9sop/UtycSv6AVtxdrTSDfY5igi6AC0uZc8mBQ=,tag:t8GFfCqrao7QBfG7JC4hyg==,type:str]
    identity.pub: ENC[AES256_GCM,data:36OhwqFLTd/6+QifMVQZVVPYb0uy+wTlqHFyk+9vSau6/xKcnQF3DxYXD5s850uCnxYxKYGFZb5ikO8Qi2idbNhK0MghG8wnMn8LquWvZfUXZvUj23az1BjLnjbgugtyMfNWMAi/SweSLbPs4D8KjZnwko/5d9Aqgqfv8fXQLtnVnG1TEAkME7SP7VVnSzPCXONud0SrsOWD7bFWsWv6/WisTR2LNNfUvOeJ3ls3FH4EQRPb7dp5F5zVffYb9YiWzWN16R+ZXVHi4QVOQA==,iv:lcDrlyrjKDOh8COxJa2tVa0PBLDHn7G+dYlxI5w1+04=,tag:Pj0nd8u/l9sJoX0w+yao4g==,type:str]
    known_hosts: ENC[AES256_GCM,data:t3KQ2qF0HORR2gPGLUEOBylxhzdDuZaOt4IUKCEw9ERYCuf+P0Les999Soszomw70Nga/2CU4OwbkEMrvy9HgOPGvh5JhDUaaILYquK9vaU77xhyKh589brgaYAXAtn9oKKeUzRLH3ElID2kBTMFQrMMgM/ZOEiHxqTZuZMtfkKIjC2wGDd94wzvuTKgzaAccYOzOG5MwtpRLkh9hmgWd0ADUku9MstMie+L,iv:8oW6jEW/jS0NnLIs8BlUyJXCpgi36OK56rwTICZSLaw=,tag:Xd5GgdRWc0aPb7yPYg/Ftw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1agltukf6ellg2guets9gq4th2nmunc965uflry7fdahtj7ea8uxq8q54ae
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQNld0ZkNpNUJ4UDBPRFF1
            UzdKc2J4R2ttUytxTEVrNUE0NTR5dERlNGcwCmJFb0JRY3J6YXg0aDYvOVhVbVl2
            NEFFVzJyVDBmay80Q3FZbFFMR0NjNjgKLS0tIG5OL2oxMzMyM0s1bExsTXUvUFNo
            dWJ6N2JrTnF0WEovd2pWTDlVWTVDNlUK7YG4WXsSyh5hqehO9sDwF1tAuraXlJgZ
            rv0eCaACUNcjHrUdfYxX2qUmBZrdXGqBNs50EAI3vNsHCSvhAOpNIw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-18T22:47:30Z"
    mac: ENC[AES256_GCM,data:+Jrje9NxazoK7hKJb7N3jrBTlpdrnG+XsJg9JvH7DoKQGG7++I9CFuLeDrZQwoEwj33SvBTjppP2syacAKpBX4uCx1fKuFEm6m7SMK0DDp8oQwgcotfpTTgygSiBOY8KkTwJayJJQ3ZmbqlkqDvirWLqezxW98v6+p8Pdv4bKlQ=,iv:6xkk3wF8Zw7yjuRxTcVdCiyJGdRysSL3jLLj5Bv2XNg=,tag:iAx0vA62I03kp8xYRem9fg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
