apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:5S81CXeBC6eBCcmlG06LvrfzhybWLoggJI0XvuUZeuO0E6U6De/UAS21JsYh1417P0TIDModT85f6ygkYqgJ93dG0+Nnkp/cUsjKYdCcIevQGT0u5b8rRZY4jC7vVeAe+eot+ZYqUDlMIWkFfCNXDgGAuKvZ/HJSshwhYbHA5weYI8rUtZa89bhioBD2QoSDC7Oo11Kq4Swu43igI6A/DSO9EDT47HAEpsz9lyvR0w4mllgfMw1j7s6+QBJb1sQQUJTDmDt211PhbZUh2r9HY1RCVcnMabuiZZVX29PAMsZVOQOHzBXtg0gRQ5TmldmjTgTl9QJWGa8B++mFvXJtiPuy23E2c0cNgBTuEL3sAg+BkOC+l6TyPca+A3Wk3rAW,iv:4O4rHds1E9vC0waBR0+tpk6vA+QDbIGr3yQxRvY16ko=,tag:FXHscVrQj53OZgyOnxdo9Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:mSIF12NnHNzpidNsGD+gvLcjMs7rWxtz+aahVlEZpdYZcTDDIGr6Lx2a+kfhBKgFu/ls2uRsYMPpiKbhBVns3LNcZQRwtUuCs1wbcRQ7CN3M3XuNf7HO7NRMR19LQWQN7b4Ch7lDqbFKrqhtV6CpIwMDH8h3d3NCR6ZvfTFJLspDx+TnkNkeNRTFxp+8FaKEmtG29P2fSy//kTS5xazobCR+GMgLyln7P9CNFagUaqpNYUpeYZ5aS3he6c46/8Sg/p7gvp44gLVEC0UYYw==,iv:54ElcLuotoGgIEiQvr0uLUd628NF4+YqIWFpJRwJKjA=,tag:N05OajrwG0WGsTU5B1WsMw==,type:str]
    known_hosts: ENC[AES256_GCM,data:sdfIaFeKgEunawxZZVnraRPAgchiT0k6gfHuMZemxnsjUey9aWw0PvPFG/AeHHvfDXV2SUJow1O4foR0rql1C9Ehx/nx+xzxCo5xvyMDoLU6N9ZgnoQXi92uT1R7yV6Jzic4i/qLJEcLbmjz3hK40W297Wy2vGh2yUkVrnwYZ1HKm35DU+5X7he9enRYw5ZvJ1iOjglE9Soa9WfXs1QkXbxmyIw85YvhBvC6,iv:PkrvYNg0WDk/LCZEWfaXehhRPcPV8ivoMJXq7dsdFcE=,tag:MXNIDC9YXjnmHyWCW9ev5A==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1agltukf6ellg2guets9gq4th2nmunc965uflry7fdahtj7ea8uxq8q54ae
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwekNTMjNHWUxKUTBnLytY
            TFYrbEpFTHBBNkxUZ3Yrd1BKanBOc2lQU1FnCmpsdkJVWWV5c3N4YW54VE02ZUNE
            Wm1tY2t2N3JJZ0pUY1JPbG13R3lWRW8KLS0tICs5NGludldzdHo5K2lQbndVdFNZ
            QTB2NTdYek0vN0xiWVNOczlMVU50SkEKokmaPACz7xPtwYPaLALzH/vsxv/2KDxu
            bmwCbSkRZQqf8yTvkTin21RlRITa7BOjmU24MF3lRyVhWh2rRHegAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-02T21:46:15Z"
    mac: ENC[AES256_GCM,data:Tn4UBbbHL9m6YRGKaqlRnYiIgUQNJkA7veT9lD060Sx2ZXeseQGx3e9cIy79hMYsSsZBZMweRlCoVy3chrdDwrok+6g2sHj9NA8gWJBzzlvhWpcNDgpP2/9vKXtEJTtSZFQ0HvsgbWH584ZDpw828g5lxbzeHNaQsgeMWbetUec=,iv:M+mistxCriHBKVNyppjo2102KDW5bmFt2pTjHJeejbM=,tag:D4SJGfGff/iclZ1VJL3SPg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
