apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:+vIP3P1LPYSc/AD/xMFkpXRNKv3kXUKiUXf1m5MX/v0lO4nOKZ43nUiZ/2vTnXgX58bDzJs1pPr0NpkJEiD+1LrRHc+RKiKhIHLnAk+qplEBa/pkXlmHostMfpbyp1aNhvqh/yaqMTw6cVaf64XQPn32iiEd3LBLy5l6UoFhDnaMmILMoYVwh9+PmS3ivG7P3VDig2mW8CD2M6yDZTe/neQPKmv2kow1FpbN0/UlIyvg0hVVztrslMa8KF5ALFymT49TLrvARPNNBiHSdsFbWBwHNJxF+GH7snelQRh6eWyIfXZRxWRLSATA8hxu8n9jvvi/oGxFov0txn4c2ykfcgoV012fOm9nARca7fZkh0t/ewEq1hidDKBsZBlKhRj9,iv:i1xwfh0BLrtvJd6MIT9MfcMhzlgiJw036Z0rZnIe5+E=,tag:tOP/nEtzeLNrqrUxVeSdkw==,type:str]
    identity.pub: ENC[AES256_GCM,data:yAAKNoMEcOyGSDMQ6pN7wawIRZ31ewUrS2CQCkZERc0iwtNax1ibBB+b0ho4KJZ09ogd2NnXGf/evmfKN0J4DsYjd8wDNZjn0VuwOkk9QOX0RA03CsLf3oAZpye/qPX9xHBFFfBw8zOdo7aGkaykEGiKkZoOERFiBAUE/rPJiFqPjQnkx7l3xl/fh3NlTlmfOF1zlUmCEsRbrUhBcJwHdA9NLoSwXlnary5Gb7YpoS00SRRSkx6Cwp3cVQkClKsOnVNK3JvSTBi6A1vZxA==,iv:hUJGwQs0A9yQOkeDp9BSnUFLFHbqC13R2UIgWRMoW0M=,tag:UR63G4w5Wf1Z1alsEPtM/A==,type:str]
    known_hosts: ENC[AES256_GCM,data:aoMBsYwEJZ8ZikfMxB/3DSA/ciToZj2iqpBzvKcLbT9yvg9L+ZktCsT7IQJZBE05Kv7o0JzV3CaLWHgzc7UXgssSOFzJQxftwoXc2e6QBPKZYgGC2OZl17S6KTu6+g+hxHfte5288GpH7j1sT7btxs5BVqZLKehGSg4TrGmYROhlL/BDB05ZWzVU0ERTsSTJUT0rAF6osLGoUYxofzoVCIA02w/dMov4PdVW,iv:leuLF/FiC5mHw3L2yX3o4s2v1sS+2hO9fCbUmBHifJ8=,tag:6+1BdyerUMf5KsYcM57nOw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1agltukf6ellg2guets9gq4th2nmunc965uflry7fdahtj7ea8uxq8q54ae
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaTXVJYURBM1djS0FtZGxl
            anZvMnF2K093c1BtYUZjK1ZBUmxUZWJjcUNjCldkaGU1ODRlRVZDamFORUtYUGZ1
            Z0ZoNDVKdFVNWDYzOC9KQmpWc3BRWVEKLS0tIFFBUmVqTEJqSS9DNURTR0Z1aTdt
            MWNuZVoxcXo4Z05FZ0N0T0NVMFdLVDQKJkNY5aTOpYktozZM06XAKo/xRg9l5fvo
            Qu8qsjK3a9sLYdGEyce4E7TYTJkPawRhh3+bA5WyLdZYeD87oSM2kA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-29T21:48:20Z"
    mac: ENC[AES256_GCM,data:I8kBaV7EmcNXvo8TGnG3QtNs3633VVtpcZH1CijDerBKbxAavo/ULniqPJbKFcm5BFUTR3d9aJEmm26kMWMQuF38KOWjMUEVpSHcJu7idbgE5Ep7QD+l7LEeEUJH+uXhmL0DNFIPZPTnZouAeKegaMRDV3KJcwgFsZ/QftWIzT8=,iv:2fOh58zwLOMeCIDSODJsvRQfDar2U2YhnJ/Hj7oCUdo=,tag:AeAVydVVgr5UEuDZai3dvQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
