apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:hao+BYO4NYPdFYAOke3a6BSJqdozy4FSrFLV8MCJgwxteLZ4w2FU0JNYrjKxs/5XmZX5eaYGIQOnOTd5orH44UN1Pj4uvHX5aNam1P/FkW1lEKCa4DZMgNpqu/9ywB5vpT8+oXgctUlti0r+fAyIQpdKxcdOUoKe9tOCYapQsLjrJnnwXRk7jqmVx0qUIHhbX3hJ4AFM1Hut0RRORPiIDNCscAwzcZnN18Yq2UJrADT8dAX9snsoR/+P0lnVqZMwyDkT3Q6zOkc8rLmWpwF0KSKt/id567LpN4X+3oeQ2JeKqDJ1jhHkzLlO+1qGK21HZOD0ByNhn+gnscYYhKrxfZDUfMlI6wPAv8UCS3jyX5roPnlKSzSCXsDT9TjdSbDt,iv:QFbsSHnIkqH6rIqE7raadn55OAljZyV45W37ahh5nXs=,tag:iyLONd1uOyzFulqhqOBjog==,type:str]
    identity.pub: ENC[AES256_GCM,data:mG0rReR0elUj+pLUEwtPR8IJEUwZRnfUBFl/gxZHAMQCWFaKCpUrfVTnLMBDjyz0R/dKHjZvTG9xZ1Uc8t43LJB4Pez4TwBxFsmslDQ+Gqwfk69HgOIeJfxebvCixBxZVFHcBG9OZXv5y1aM1Ie8I1bck9w3o9uX8UtIeypBK/9m+JDXEbT9nAm8OSOtbaEWi7E5L2F3LnXin9ABSwM77+fT2ysH9fawXI1VfnSbkJ4t/cFfonFg3hIz32E709lt7CqgSHbU4bOq8bjy/A==,iv:UUTOtaDJ0GFH4H3zOPHmLWUwP7WZ8YOP/mhAIiO3o+E=,tag:hBFXOqHFQhfQrv9F6L6UCw==,type:str]
    known_hosts: ENC[AES256_GCM,data:wx88+j1B8q5Kg+zqG/gwh/PCZkQylukUmuNzz2HrRokC4aiLk9RC5TSUFAzFb4ia341Y7U4z3eV72V0vu4o2M3DBtgBi2gxpmoy7L0LknhJwMXg8Ej+tlne97Xi6tlHbfLccTmiSY6X5V3daqCgmvtLiG7ZeVfm4k3qlIWR9vHnQMx+L92Yokba7HEncz3aoxPOFsBzr9wZAMyF3+aF2K06ZeyWfMuKje5d1,iv:123VkQw5FnG27mNNmb/cql8YUfzTdLKH7T1JlU+qCIo=,tag:2mI8YGqufj2kiNEBMLpxDg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1agltukf6ellg2guets9gq4th2nmunc965uflry7fdahtj7ea8uxq8q54ae
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJN0t4SmhjTWtLVlJ4TVhn
            ZmJRa0JUU0ZzaUNKWEFtTXQ4TDdGTXkwR1F3CllDZmR1MXB2d21DWW9Qc0QwNmF4
            aytteG5ycDdNSmlQYS8vNjArTlJ2N0kKLS0tIGd3dG8rTjdIbXh1d3RqanVHZFR2
            ZXRPVUtzRlpPdFdBazlyU2Z0cm5zTmcKka2Gw5de5iruBK92z+/hnE25m0Dz4AyH
            cZIHk5C9SzQjsRUIj90GnoiIQjV1Wko8ZUUpSqK+ndF7aU6fSB+W5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-13T01:53:01Z"
    mac: ENC[AES256_GCM,data:f/S6r12X/GPihXpwtUVyb600hf34fmhKzuCLk6iu8Mlcl8lqEMwrY8BKogWCIVJCEyuPikuERhWkA4t9Qx2lD5qsnukf6opbuzuq225X5wKAfVU+2mGEjCD2lAa7JEAoAeidVXK9mtzW3X58ZqolW2Jn9ZO9kgiKMgb7qdu5x2M=,iv:O0yY5iVQ7M3KFsGT8aWuqJxIE9MKo8K8FNo1E8THYPc=,tag:8xLmTWHcoRlCpttck/GE/A==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
