apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:JSG64wI193aKLMTJEOlbET9KbjvzVt6cTlv9/+Oe1hK5Foav8fL45WiwxEowt9aOiENqELw7GTrjsc8OixYGlRX6CRsrUK28uu9DhTs4CINz2Zo+4qw0gPhoh+IudPS8cyn40SudCCIH3yANOcwA6heD36DN48ThjRgnX5EPczI+BjJq4yRFj7VWAuxo8aw1k38SE/J6T1bL/OyQ6v8B9sSL085jEz+s+P7utFuuceH6qKrNlmoW1jRkbqDAcuG24vjhTWb5L20csFKBjjnwANkxtkyCemu3PuZcs5+ponoLCqMKBROENFhubIlt1T1fEatW2u6uUtW9ZIAqaeWZ0hXUEZRfGwyTdZp5tLJV71qDjWOyR7/Oa/BPhu/KhFBP,iv:6jbAzsGz/BUda8eurxGjdLHRwjcoabaz+XbmKmZdaJw=,tag:GaJxjC3IhCaDJD0YZeYc3g==,type:str]
    identity.pub: ENC[AES256_GCM,data:CN0vtf22RZd3yZL8VOESm12uM4+4eCEmnZ0FPP/RevwtgvhgNI7titMu5ZlCKB+bpEQ+jIjCHjlRqTWdXBqtoDy2AhI7DUnJglQ3Q1h22YXbppImUa5y/z8gRNRJ0WQWvq5PkJrwcK39Jhov56rYkZ287ndbU8AdUlmgpca8lmweIQp6sX3Y0KntHcLdXikt+rnl3+VMvjP/ql1EiZik1FnYA2qVgTQYcEn2+hRWTR3kbeaeVbk0IP0wxWVABU1b0yyxHhw5JNA7CYiB6A==,iv:uL0GwpCtjICjNTAGpr9kdBTuDj5JAZ/cmJ+swjf744w=,tag:aZZlLGmwPUeSjTqWDRSSAA==,type:str]
    known_hosts: ENC[AES256_GCM,data:tJonp5sZiaH+0Vs1ntj/C8U6lBc4tAqKvJFCdoKP2WPiqJ5W3NHCAmjF3WkyBikgGPXiNLfPA82obRgyKcWnOje10fk1iPz1slVV1rVTh48kAvAGvSEdJ13tMkcn9QVB3uiQholu7PcETAFQHfWx8pB3WA2bWk8/Tw7MGQ1ZK01f+B2Lc8H2zVugmdiOWGGHAGumaa8aY3U9aL8GRkKmnVey/yH2eiP75NYY,iv:VuwW6aEfiTjp0Q9s7IO7dtGQ55RJiI6cdiCYmUpLI6I=,tag:buyHRqTPk0s4DSbzEP+XRQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1agltukf6ellg2guets9gq4th2nmunc965uflry7fdahtj7ea8uxq8q54ae
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQRkV3Yk9GN1Y1cHVxN2tv
            RkFrYndLdDlZczU3OVdlMzBRWHVPRzM1bEE0ClZSWS9yTlRWYlo5ZHNFL01mWEt6
            TXVrN2MrNlA5ZkNRM002WjB4SE1KbmMKLS0tIEVEUXVZZ3lQN0hiL29WR1JZNmIw
            UEVnZnZza1ZkOVJxbW9Eem9McVhhaWsKwvT5hcjhV5RXbAk1MXVUat9dSkAie4aI
            3cckqaU/KGOHLX3A/2/hOoBaRQc/Yox36p6d4XZGBIN19RetiHgf/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-09T06:25:57Z"
    mac: ENC[AES256_GCM,data:KBlj7ioeK+/F3KIyHQUrvaXB92nvujMEsPT7zEaJsjhMiaNaCbdFfcn+hg+2vuTzpBjnb3DMl3VFioPINTmW5ALK3GsRYE4LZVYuzP7CjnIvyNKTndJhj7j2HTTTJX7440SIZaV9lYwaeKe+crkOmg48qcVjFM/MMk6SGJjb9tI=,iv:dvih2sPU7HP5rP3FDNQulwCqNPdEWdDYb/t3eZQDzOU=,tag:+GI6OgncZrimBD21GSUCCg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
