apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:OkvQarjYVUzitpBS7uiNy8Fhts5FPk6hbV0vb3BuAo8lIEG96pP7oaV6+RaO7ZS8qNheEbCtCFBEuzymuIFbaFD+GUF6NQl4HIOe97gPS1P683uCASVxURV1421zUbam3BnwXXaqjwill1R6TvYxpYn4OcfLHFerAlKeEop2N4uvgMS7Xr/r9qH42vpdquPUsvrB2VVK5ug17vV8bfIG7jE81VfxYJ5h1joY3YGVFBiT/BLn7y5kHOJExGTlzvnOQ7Pm4zHsvJptpklWnzc5+ZompmHtllCT8mIy+SxyEJDlP9AOq1yqwan8EtGZc9XtZwCpA4BH5ZLZcbdkw59DLNp9bfJmX2OaNCejCCkF3RvqSwIfUMf4VN4UOyo1lIqZ,iv:PlHTohf2WzlkMyxPvfgpInZsjmT/b373XpjhpmaZG10=,tag:UbTPCiyVZbPzwkvIMWNXpw==,type:str]
    identity.pub: ENC[AES256_GCM,data:HjwR9NTURdbNPWiY++8LWfiU5lYls4p/RqSUWGHceMuekzbq7O33L6+PgR96wTfBMg3BEY7gJTI/vNO2/8Jxy4I8YGHM1bz0XSHgkddBujWT/BMkxY8xpreK5qaHSRJkGSCyF7NaFc22BDRnur0Dps+op4CQoXWaiNC36/nrzNohkPDYvgO7ndiZIdTCpXTU7g5FgovLHoqrm9tpP2wYpW/kboKqcAol2zs3J+0xMCQE3jX0cV8U4a//riAQl6C/IBhvrTe2tgTmrvzHxQ==,iv:V+SlTLshlrwBp0I8XJgTbDpwI+WVLRzK3J2htcXDk0I=,tag:W7gLiDM08WixXDMYnI9r+A==,type:str]
    known_hosts: ENC[AES256_GCM,data:DxV/6xQMC9svtDJ23Juqod0amjA3E3pkOZkbEv6bp0JlAxBeSVh2XOBiUQbVEPQG1kIMjvY3UnhyqBwiQR+vFZ0J5zva06CMd7Uk4P5ZzjLztO3Myhem3KUPObhWRNJp8nU6Uy6lBQBVmmO7zmzCzp18X/2x4YxwktGjJxWfAfasPlztpzcYBdrknpoO9vcIUwvj0nt1ib7bumxQj7phPD2AvV/pjCs61Rr3,iv:CkdU2SRrY7GFE+ZduXs3/DqLba8M8jm40/dk3zDIOgI=,tag:gWI1+s6ZuCtfUgNYXUOXjA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1agltukf6ellg2guets9gq4th2nmunc965uflry7fdahtj7ea8uxq8q54ae
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTaFdrTUl2MjlRN2NYMVRh
            VkVnSlZ6allpREtqVzBxai83MkJCMVFpN0ZBCjQzTDVJcjJjWXZPWWZTT2JqWkFM
            c2h1MDhUSDZld1dHNjZZK1EvancwQ0kKLS0tIG56THZwaElxZzVRWFJIby81VE1x
            VHdkUTdzUHp0YkNtanZyN3BFZm5SR00K17IY/8o6odZQgVAu+EikP8v7cYEcawEn
            YNP3VVvzdMSJxOttcytkOVqxRWdHbQrIyMaE50aMgZKa7yWTPhPBEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-09T01:22:32Z"
    mac: ENC[AES256_GCM,data:8E3cIt2PH3WC6hvtxBlwDS6dVM3PbQqMiYOQu/tC6SrINQQBM5N90V1fVwsuRjQ2Yz/LSrS4MXGpMHxMMoFkwkpX4D3g9r8EZt9kxw7IAZ+gHaQGItB85mwrfXL3jkk/wL9eR4mRkUTaVvsbPMgFnQLL3Wl6a0icc+FVhh531ug=,iv:RF34lKdB84lSUdCdqOmfHAovHGNKOnrTd8ELD9m1cg0=,tag:EcSK07Bwet6CvvjC3SoL1g==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
