apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:zcCW8w4nhg6aYa4Igc6qCRsaloAKx+Q5NZubTbc7QhTMGfVHxCWfoJ9/MWXBDU8gpTV+0qEgrojpWAwrU+wP/LXUIpr0TDVW711h+MazFyDsX4kwgJuAKjT+O0+mwdB4sGzlq340qNT2iCvMudy7NEdwqAKUa+SRY7De+SLYQ/Tk1frtE/e5Lws6E/ejgxC7Ud0RPZ7DB+ExnWc0uG6HXVKnlLDeWnmgKGxhG4iAXYaq1W+lfVcqY6BxaSgexDeL0qKx1vaTb4uX2u5usvKO6xO13JW5xLzgpunLqYz/HgMPJtn/LOmPcNb+noWSlTsUu+/jK04xgzzkT5uSJvduf2sK6jfJu5cA3jaLo1ZesCboZK/k8t5nk4m5tMf6dm5G,iv:gpq04e3b5IggBXsbarCmIiw+lP4gpLPdybaUF6xx7x8=,tag:CdQzds2kezGOs//+JXipJw==,type:str]
    identity.pub: ENC[AES256_GCM,data:nbsXa42ldfg0kmqc+/z4A7QA9m7e4r1pCJkjUs4iZ/kzSgOXSprepV6qSyw1uB54Pn2Pcg1U9lrcSxeQ8f+OOYySNeVrjiJXAq+9hWXJiQKlPoGywMOqQ687VbwK3BYOlJJVQ2vKKC8j+CGtTCrZs4AYz0WtTgMdeXrub0Yp+MFtWDsI9EWMJrAU3jPPB3kjeGPr//cX0aZFHOz5pO1d9b58AWIyqHWUyK9q4kAVtKgn3biHcoAG9KtOuH3FO40royKIe8y+BCIh5rU2gw==,iv:0+q91k6snanxFELl74Rdy90q4IfyhFuFxf56VOjJ3l4=,tag:mUbi/tIvP8Z2zqfiS27Phg==,type:str]
    known_hosts: ENC[AES256_GCM,data:GcxQw7EqrnShru1ijRW+LZNqYFdjO7DqtUtN1zyoJoeN2gJNt0puWTMunxeNpb9/WirNc6xkuRd/5jLaXcWJnVbnFiuP+zUKZb7CZahI2gDnNVBkFm7x+0uq5jPUFy93V2qw+vSV8CKwiqsV9EL0jXiCkuXGcISj0Kd1FFUDftzaxXxf4suDx35PA4apALOvWhmTIR7KnqbPPCCrbw6D5c8D/GLvRtZ0Cvxo,iv:KGT8+aGUsJiXDtOsLVLBOrAwC2/gSstt6JkPtsVnnJo=,tag:2Q/7czch4A20Zm+JKDUlcA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1agltukf6ellg2guets9gq4th2nmunc965uflry7fdahtj7ea8uxq8q54ae
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmbVhkMWNDOXRaTlZoeUcz
            Z0I1ODRQcnFVRXFEbE9uTld2b0NwSmhBWVZJCkZDeGZXYUFDRUozUFI3UnBld1Z3
            cHZqaVQ1c3B4UGs2UVFmQkdPQkR3UkUKLS0tIG9XVjN2RGlGaHpxazdxNGtTbWtR
            aDd4a1J2WkxocmN0dWIvVkxsRTJ5ZEEKuQeLhs9ZSFqfGetmeU144ozKYXUjjMwR
            Can913tibDR2/VAmPkQnsswM0mFJ9qwuBpqVo5tCTtGlt9zIF0fcSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-09T05:38:51Z"
    mac: ENC[AES256_GCM,data:INR4stpcPF/S5J2oiNBVCzD6W0YkdJdki1vkRNZ1/nU2hBtMaSri1t4EHASKlcW8V/J7CQzCU36ZmhL6GRuMfyO6fC+1fAaIh7Xtj5RP/CO/ZvNFqUEymIapXLFZurbDZoCdCeGJluGX3HF6muOrM4J1fE7CskhDcPZMieNwsdw=,iv:yAgLrhYdBmzROvWo7UreXZMozqrLAVudD2Z6OLRZbIQ=,tag:9asNjn46iDphcgykASKfUA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
