apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:WxXtulgZ3VUgJ3H6AAhN0c3pz0yS+Oqh6kaMAPX0ogZRRgjtj6T5A0lbcraRJOSTUUc925pR/bQJYP1EXUSOnWH+f1Btn2fgCMGzrPg22JuCHrkbH37w0WbH6PhR0y8cExiw0qvRHLyPpisNtHwIBh7b9S/2jdxD5TpOdDsJZs8YOUdEJ27p5oa+KmIhXJlBTSt0I+V1BW7EXKlOt59Qzf5/HwNESqARVugT1zLfNZCwht/9tfD1GwqTqcX2JDXMdRa2RZWuYg55c27g8gRjJZ+5OYd+gCHD+mnXrgp93dEm/5SU771glk3CGyb6uhexr2Dzq5+4iBDFYY7t47Cy/s+AnlRsmaUzXhhQWrs43inTrjGwvRwChJJZtzLolQ5L,iv:S5AwgKWOfpOQRzCXC+CJRwPAoV+E3AiLKaf0aV9kbfA=,tag:+qSGCJOLpDSK8pcHZXUjsw==,type:str]
    identity.pub: ENC[AES256_GCM,data:U2vZB1BFsMb7KKWNt6io3HYc/oPuQm+Nxo5nN1cJ4nY4MngfCxGHNfQnYyjymLGZ5Nx1W0LR+THSzUyBSFaTga+AN/ckfzJ6xj6FXDEWrGwFSlFVt1MQqjySTbFH7SYkB6+DP6FzTCr0uMcysXqzjRJUfd3mfMi9BU93iFqB36WjEEXONS///dG80YYWW//SM+kv6oF5e92R4NV8f0EhYz39MdDnw1HMwS3+MMpvsLLVMpBTIq+/V7NJ8up9bYQ6yENDrxgPDRKNBn7/CQ==,iv:DBoKYh0aOrlCQi2bvcG5nJrmd9QKznc/bI01vG6JqNw=,tag:zr2o75Q7bfgucHQyAUn+Aw==,type:str]
    known_hosts: ENC[AES256_GCM,data:5h812ucZF8qC0bx1PIps0nx/yDYOvcKcjrJjkBi5A8309MyALDMBXRl2MlJq/YY2Q02p7F1hYHFCIyucwKAU/qwSP589KjmoVMeR74Y5kE2Z6+WxorS0wSJzARAKFz/DZvYhxfzzCXNibiR7Ds02xOFPkPoNi2tDY5YE5IpodOUioX2smJDpP3anfu7PntBWgY/0aUHoPeXOhleq+ckZEF4yYJRV7o9398C1,iv:AnPHikjmjYq2g4045opWOGAzVnS1t9mh7wDIM1GGvrI=,tag:yjh4ath/S7Sf3ZvYDwT8Wg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1agltukf6ellg2guets9gq4th2nmunc965uflry7fdahtj7ea8uxq8q54ae
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6ZVlCRlJ4QW5iNmJwUVp2
            bHd4dEJ1STRLZm5aeWdUWGZpZ1RjbjdmR2dBCjdSZ2lFaEFjUUJZTXZ4ck9wSmU4
            Ump6UXZuV3pELzNwR29rVE1sSDUvYzAKLS0tIHo3REYyQUdETkxyUWhJbGVxVFd6
            MXdGZDNsbTlDa0VyNnp5aGlRTlpNVXcKWdn9btsKbzKBVbQREIxlQPOkajXPARhb
            +cuw5GLLvEs4TDf3jqMxdjAXkwQHs3ReuKXTIgMX9aRI0fdRf1FBhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-03T02:06:57Z"
    mac: ENC[AES256_GCM,data:WHSIDxSbUiLCq1FdNQSCg4sEOtwaWnkOq/kXSQU0VWk8h4/1LmtTPa123vz5NAcK2n7tLtlnC/scj7KE2gU553EZOfzT6uNY7aTDOW4Zybw1vmn/c+mNPVEXv3/6eibe4G2ROuekmr1N9nHQkSM2E6MrMH9RTLnNt/OjNANxxvU=,iv:RBQwNxY/hImelt+RKLnUZSwcGCWTVmsI7eGEPhZuPtY=,tag:vAj42TKXQjNR2lVDIzX0qg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
