apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: heimdall-nfs
    namespace: democratic-csi
spec:
    interval: 15m
    chart:
        spec:
            chart: democratic-csi
            version: 0.14.6
            sourceRef:
                kind: HelmRepository
                name: democratic-csi
                namespace: flux-system
            interval: 15m
    timeout: 20m
    maxHistory: 3
    driftDetection:
        mode: warn
    install:
        createNamespace: true
        remediation:
            retries: 3
    upgrade:
        cleanupOnFail: true
        remediation:
            retries: 3
    uninstall:
        keepHistory: false
    values:
        csiDriver:
            # should be globally unique for a given cluster
            name: org.democratic-csi.nfs
            fsGroupPolicy: File
        # add note here about volume expansion requirements
        storageClasses:
            - name: heimdall-nfs-csi
              defaultClass: true
              reclaimPolicy: Delete
              volumeBindingMode: Immediate
              allowVolumeExpansion: true
              parameters:
                # for block-based storage can be ext3, ext4, xfs
                # for nfs should be nfs
                fsType: nfs
                # if true, volumes created from other snapshots will be
                # zfs send/received instead of zfs cloned
                detachedVolumesFromSnapshots: "false"
                # if true, volumes created from other volumes will be
                # zfs send/received instead of zfs cloned
                # detachedVolumesFromVolumes: "false"
              mountOptions:
                - noatime
                - nfsvers=3
              secrets:
                provisioner-secret: null
                controller-publish-secret: null
                node-stage-secret: null
                node-publish-secret: null
                controller-expand-secret: null
        # if your cluster supports snapshots you may enable below
        volumeSnapshotClasses:
            - name: heimdall-nfs-snapshot-csi
              parameters:
                #  # if true, snapshots will be created with zfs send/receive
                detachedSnapshots: "true"
        #  secrets:
        #    snapshotter-secret:
        driver:
            config:
                driver: zfs-generic-nfs
                sshConnection:
                    host: 10.1.0.63
                    port: 22
                    username: root
                    # use either password or key
                    privateKey: ENC[AES256_GCM,data:l6y2DV1oKWkUYr48rqiARjgVLmnZnXFyLTIfy10Ayw4m7DvteHnqSlrTtkgE63WzMiwIFz9PxfNSuyVApAe4Sc8d0UHXYXBylxb53YXTi9em4+SJcYpyG54iuXEugSpCD/Z1sEvtFWonL5YZaRdDv/RoPBNHqzJ2l+UWFLNz36orgyQbaT5jZzAzorYO14tKOzTMMOSQaXnP4EKFNyCAmAhFKWZgQwih0FtNUm8ZBeZPjNJav0uHOSDDoQXleNh/TSYdD/r699983tykNceo0wFBVBsg0p9DW9Hgpzb530oUEzSrSdveoqDCCp+idJarnxM95hflTBo1vP9EZrCsqFzslaCqBwI/AwL06Nxmb81xW8koBOfaQD9hi5q+XUeFV+zmzdApZFUmy2fJlns6Yy+ZB9Fq7rUP6w1MqhpKIixI58nZ9qzPCSHciM74HBg0cdu73oCTLaSKIsnJqA34vPDT5+qmKG7Ucp5QUMFjAJIOln9NhoNATyohJ3vvM3vh2vpNSDd4sjKezX1gbMDbk4ZpWXQ/BLG6aoL1KFjAqgI2cDMjUSC4hu9GxfBRhk+gAaohn8RFyUowdUfBVncit+CnFAq9E9uIED3p6ZlVK3vlQ2Cp+6KzYqBK9ednKmlM4K/QzlQan3v6eKDrbT2PTj/Frlz8Hsm7aFnBy9o5CqFQXDb8mZIsCxNNRcRr9lin7lzhzz0cbzzPViL0gcuwSa1wS7mf5COTyFdmIthoQBSd10dIui3oqNzEawvnl0uni3yWOZVL5ziRP9pOsZ+4xx2wgFKQqH4XwTiBPAQVtcXcbPx4hyZPmvEPN7TwADJCIAE5bhGmmjp3NZ7AUuDXxIaiWBtQZ2JjN68sK135stDSrl4a0NyaiQ0QDb7baISSYgsUsyn+9rujGICveIrn00brevpWzBmzZKIWqPQ8/NSEiXWvK7nEkSmarVvgR6agapRqOR46pHGGN1b0y29QEB6qSBy+ryNDciceNWYq9CYaAORKbMpJexIp0pe+n1hsOuGIj4dBOdzDO0oECzr0PF77gSl/u8m+zZ56ZSC7Upo1eYIGbfTzmngDoDrwTItl4r9Js+uCuCmyMirqONw8Jot4hRXUobznq0u0rSKrEJWPUfc5+JNMcixuQeUSFczlRBVDfputtH6gt0qj8VqGwQYrECSareXa5AlvYHA0TgI3pH+mZdQczh0Ocv3MjeKZZhPauzVAwZuIW+FiLTuaz6+Ps/8oHvtuF6IT16SEp0SSE0afjsIYm8Zqr7HLT8TuESQDCX7ac3Pj01BBWTe6+r8GSsWzj7Cku9lL86KtPe6lOXbZFBab3XgSGnSoFTw2SCbLiZ6fHsFVoFp3GchiV5Pum3UDZ3sljwrO8RPIk+f0bzl0VY4olGQayjyWbD70BCqeSM3Cz7PY/KKBpAcaLVUlytm4osFZjgqJDZIFHU3eUxMZegS+gjd3oB2rvArgVzZRsSx/qoiz3BS3lzasBgXGbTilLsbSldly8OGMkWigKBEroqh/IiXYkLeaLTqHclQDdmhvLjidQd9Dmp/XPkBPZ3knnJ20w0auLthNBPFfAZ9w+hBF+bBoNcLipJnLl3jk2AJJ9xiaOo07B0HmxdyZjeutMzVYJyWn54Mlj7V6LoMjHcY8XiZOIvjNrVLuSj3opkUi0AfsjMyZwscurW1eKoz3Kwd8Vnh5FiGMzJaXQheq4tI+hyjG0YqLSWR8Gdz5RpuBkZBnGeynitHiF2m9wGH2dxkdEodYuCucVlce32cuqnPqIDVH8INRWc8k+zG+ONE04Z3aAvZNEzyRnTg4emOx8z1S5R50xykKZAdaW+/R7omVpwU0GUrS/j3Lxqc/8WXyJERLu8hYK6RQVWQWjmhc2X8hyBcuA7CqS03K7iN00v9xavi73EgEk4ShGB07KEOrqD5BHgDgmJEoNMjNOSYrZ4P6yVxNh2qPUZETmo37F1IszgeN5cvl50IrhTqPhCulgeHQ6TjgcD13V1TJELmUZko+iuTbHUfzwLvoUoU9J4Fy1KcSynQRaUJQ1JXHgOFIbL0d0KyBjqxC6DaqI97CZeReqqhVQERCYHQDWZnE9RY3nIS7FapgNP6kxgxfWL4/rn686F8vKvDq0/FdZuADaX3dJJLHp/8uMw3Htr0c4vimPc0UTA35QPkTBqUhhlcyqv4aXJ0RIb10tvvHhXDht0IBQrro1CjEcmQ+Hk1SDvfN138WiwfsEVxwAHDDHWQhZlahFuUL8934jYXeyrlvxe9CYowicnrTagKmDzzUTx3++4SQUhQpMO2PlMCse0zgSvCYRZELmfpltNi96vOdkMCJJI2kpItNcbxS4RbwwotW9zE5iEn+JdL41gtwBYyMOVmFF25UQu/ZYMxPu9dnI0LxsnmBlgHRsB+dO3PeSxaFSBhxwBEZ90UvbX/9zjhvfuubZdUOQ1WBdN4sv7G73uLdsqZBBE50MqIe6Q3tvCKcHIpOp+tMjzu0q5XZbeSGpa5jwP4gg1WkzH6PxR1UIOYlJxHhb9yaSTr98ffupS/l7CIPTdSB52WojExae4Dt9mrjZKD+hjpqK5q9E7aYflmuDNhNnQoTKoKNirN13P1xD/56DpGiWOMgRYo3mjhj3Je7k50rk+L2uF6EvlPuPZeWz+C52Tq2xC2jf9ALCUmpE0tctY42aQ7WKc2Ggm56/xfUeFPq3iubGmb2GyD0ceZ5TBz6ZuMqI6p3AveWlDnRjFoglG+XsuoPcI1tlI0HtC5Q9L0yfVRN3rlxwwNXBWQ3Pil6uL8cCWlWfkn4GaUsYyOvLKrK72tMmTQ4tkvDA9ykOezkWCERi5Y0xO1UhjiTBWQBsI8OHkSXMePYEJpqYf0oiuGfWBq6wPlMyh5/VgDPNhRpJV7na76P07lEPwAfxDYUDnC52t1tUWJ+BfWmAP+1Vw8YY4LzA7aDz7T5QzVlp9gioDDIwBwl6QH4AJ/qEWkbiN6VWI7m3lj6Dagkr1+rR6GFNo0g35+Gah2cUEokh3+GjDL/DFu0vdwI0zOUctSLCV1Eme2CQk/sW5MteHURlV+9LIBYnYCIRqFF68MpELdtL6vBjdqUG5xRuy3b6leGbnejkHYelJbHOFAkebGQ7qBtqvYqkd3mQr4jmpq3m0rr9AXC+COI0B7QG00AGylDgj4HDjRuMu7wC/ZWdAQtMtKLEOBCtM1/T7flkrnzlCCU9VQ1opcuTpL4UorJA+EJr20+I9yqHd4SVygToGrdqkgLnT/mm9bLcGebTNn73bv8cwiEp9FXXiMkUaKtLm3wMBpsIgbOnzbtRNLdqEk05y0q7pHs1/InhFa9EjyTCnl6xX3T8A+6qdymdQiF1h8jKKIziNYuRSyO7bGZLYyc5tc7ujI8GO7caz2lXxeZsOHZsJs0ce4kyEAd06+9J9O2jKSKjs2Wi/DffVmMaf/jwMeKkv06gZpPN371/fAgMWIFo2qhuF+muAKqE5v2SNjbqYQoPmKo7MZYwFWG22EzEqgFp+kxK2PezpKPfTQ5kWnhME0DGZioxY9L44tTg8/ue9OPHEtF0FT88TXuka60lFWWnx65ZwR4PgkZb2CHcT88Liklff2tZOn2Vdxm5o7Pm75A+qMOOGGE8GJTXBZt5wkIULRTa8NQXpXtyUomiafX7pAbSVMFJYgbavaVLIFuk+VDoMOBxxEeEXva/D7qAT665sniBbBYcmr01v33eXaVZdBoPoH8qs7XYwEcPWqwDma5b16JluWKF/VHS0LAbBJZkM9nKDRXMOr1YZd+VNJE/E6m1LNWCYzMWOxjpcxPmE6NdjTLPtKFXj+4trqFOSgn2mJVL5zuBxnD4O9Wg3Onz0KIC/L/kWPGi7BOyCj3wYFm1KiJOFqdD0QFtRFC3iYFMg+Z0pqQC4GGg2P6y8kuj6sRMsI3TeCvWFrgNhAID/s01GCBfsHby/Vmhhvnjy58LtPlNQQAt1EZpdI3vWM0Muh5Rp74M/dy/O72A3KLXr1XkYLGe9xoUXqeIgSbND5OPiZLaX6KWA8ZMENUn4Lxys0YTy/GmSyBVP0J0ZhFCYmwms4DrG9e45LalcZDu9o2oGmAlGkRMLInpSw6WkKWr9orAQXAN1QiOkb50ItLnYCUDA1i3EEv506mGyQPS2hUGYLhTZFAWjWfLHKx+ZKT3ck1Zfv19X2V21FrY3CS7oeQfz+j1dkuAxKfixreKq5YY4xVQ9HAghOif7TnLxEgiRIviqiDSzmfdAJwksUQcfPZGcY0sSKHlGyl0+Pbk+o97AdxTTOEyDcPkP+8SC+UWPCW+7zJpzKnbw5SQPfKlEdV2jVPfe8oGgUZgVZf6auFCRfPM7GxXZBYXQbpKxoxWfcap4raCnobSoMghRxjLgZozgkaWtg1ymklXvss8glwNSPSNYMeHfozbDNWaiImvQBWWxbDQKh9Dg942bMnJpx9Ec2uqexPrciKDjaKSFKPxdgOpXYaVVa+RnRt,iv:NaJRwxs8P+8fv9NTi4DroVRH8nhTU/dNVzrFb/qEwQo=,tag:TwbT1a+Io06ex9jJv7qCxQ==,type:str]
                zfs:
                    # can be used to override defaults if necessary
                    # the example below is useful for TrueNAS 12
                    cli:
                        #  sudoEnabled: true
                        paths:
                            zfs: /usr/sbin/zfs
                            zpool: /usr/sbin/zpool
                            sudo: /usr/bin/sudo
                            chroot: /usr/sbin/chroot
                    # can be used to set arbitrary values on the dataset/zvol
                    # can use handlebars templates with the parameters from the storage class/CO
                    #datasetProperties:
                    #  "org.freenas:description": "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}/{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
                    #  "org.freenas:test": "{{ parameters.foo }}"
                    #  "org.freenas:test2": "some value"
                    datasetParentName: Heimdall/k8s/main-cluster
                    # do NOT make datasetParentName and detachedSnapshotsDatasetParentName overlap
                    # they may be siblings, but neither should be nested in the other
                    # do NOT comment this option out even if you don't plan to use snapshots, just leave it with dummy value
                    detachedSnapshotsDatasetParentName: Heimdall/k8s/main-cluster-snapshots
                    datasetEnableQuotas: true
                    datasetEnableReservation: false
                    datasetPermissionsMode: "0777"
                    datasetPermissionsUser: 0
                    datasetPermissionsGroup: 0
                    #datasetPermissionsAcls:
                    #- "-m everyone@:full_set:allow"
                    #- "-m u:kube:full_set:allow"
                nfs:
                    # https://docs.oracle.com/cd/E23824_01/html/821-1448/gayne.html
                    # https://www.hiroom2.com/2016/05/18/ubuntu-16-04-share-zfs-storage-via-nfs-smb/
                    shareStrategy: setDatasetProperties
                    shareStrategySetDatasetProperties:
                        properties:
                            #sharenfs: "rw,no_subtree_check,no_root_squash"
                            sharenfs: "on"
                            # share: ""
                    shareHost: 10.1.0.63
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1agltukf6ellg2guets9gq4th2nmunc965uflry7fdahtj7ea8uxq8q54ae
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOK1p3TXc0UkZubVpwMkVF
            elNqSlgyeGlibWNtVWxmc1BQRVVwOCtGa1M0CkRzWHdNZXYzT240SVNMZGhDWlp3
            MGFEKzBOZUF4ZlZIWGJ4eG1seWhiWFUKLS0tIE8razJ0dXBjOTkrQlFsY1JtMzVo
            b0JMZWI5RVZSUWVGSkMvdisvWmpTUlUKR5cChOhKKM7bIg6G1dIEv6UzO2IHx/lY
            AagoetsMiN4Bc9s0L6G2vE2hscOyhCUOZxV92FjeV/ZAjQGDC7L1qg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-02T21:46:15Z"
    mac: ENC[AES256_GCM,data:vwqHlsFUBcpbAvlJd66twbEJs7Y6iAvO9vAtyuV3lvI59IA8PelUR9RBfxqZHhsKW/bTMa0qG+GPZSugP9kNwFwYWAAMjeyyg155bKcBZpWxUXq248pTsziBRj1K12Lm5uSFkB4zbz8pBX3Zr85T0Q6Ks5zlgsJ9cPhHT4IldH8=,iv:5vczHht3PhXw2Wt8V63+n0NXpgjxN3pQY9dxkh0D7MQ=,tag:p69C5KDc8ApUv3rY8JkLrA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(privateKey))
    version: 3.9.1
