apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  interval: 15m
  chart:
    spec:
      chart: nextcloud
      version: 32.8.9
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:

    TZ: America/Chicago

    credentials:
      cloudflare:
        type: s3
        url: "${S3URL}"
        bucket: "${S3PREFIX}"
        accessKey: "${S3ID}"
        secretKey: "${S3SECRET}"
        encrKey: "${S3ENCR}"

    persistence:
      config:
        volsync:
          - name: config
            type: restic
            credentials: cloudflare
            dest:
              enabled: true
            src:
              enabled: true

      data:
        volsync:
          - name: data
            type: restic
            credentials: cloudflare
            dest:
              enabled: true
            src:
              enabled: true

      html:
        volsync:
          - name: html
            type: restic
            credentials: cloudflare
            dest:
              enabled: true
            src:
              enabled: true

    ingress:
      main:
        required: true
        enabled: true
        hosts:
          - host: cloud.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          traefik:
            enabled: true
          certManager:
            enabled: true
            certificateIssuer: tinoco-le-prod

    cnpg:
      main:
        enabled: true
        mode: recovery
        cluster:
          singleNode: true
        user: nextcloud
        database: nextcloud
        pgVersion: 15
        backups:
          enabled: false
          credentials: cloudflare
          scheduledBackups:
            - name: daily-backup
              schedule: "0 0 21 * * *"
              backupOwnerReference: self
              immediate: true
              suspend: false           
          retentionPolicy: "7d"
        recovery:
          method: object_store
          revision: "1"
          credentials: cloudflare