apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:VyXuT3+73bpvGQjgnB32qRZIs1TMa9FvNrS3uhaphlkRY8zeS5snK7TabyrGAiQcTMZkTuGdVOGPShuUGnyBFiDUtc74dt3rO3p//8hk+E1BinDfK1FLwytJlO9gOZFGJfMZPaOVGSewy37L8yz98yF9u/M1CAk8PEmyX5lM4y6/YBeTxBIsugmZh+5gpowRVDW7sGj2sNAX5kDjuPQxR0zCFsTU7UhLeIQgO0BhEnG6XMD/ML9L1InhGKX7KVamIm7kG/JtVIHJ7o78HSSJmc/vTbMPU6hUvv6aBNDAB63vQxceNAYwclpl6q9uHNWanuDr1FQ+YC9JFowrZ8wC4Imbm7ZHv1GW3d0oOGFcGrD3RXfR9ATNf/bB0XhdXg4q,iv:mQsLmKQRuFrM34/AquslMUIH+IJqd6noT4GnG02+ckY=,tag:8erxvnds0c4mZOH+AjyP3w==,type:str]
    identity.pub: ENC[AES256_GCM,data:0rQrTIbQz5X7w37x+fc1JmlLmkMKPpPe4AaT8Nv2XqwH0btq7ff7sDmh2/XhNQ7TyS/eF25gh12LQBd8+L5hwOy+/sPmTIwZvjVsfmzCdh1OqMMb22FjjNU8VAPOpmeZwPOj7MMDVlZSHlNSMya44Huy7Z6pA/FPhLL3DA/4HZYpcS1AkBUngVbI9UzzzgU9Tr6rBvloqOtau0KxfTZjagEPfcuUdcFTHEmYMB1+6ABuMA+DxPdna0zhwweShwqCeJs982juApC8B/Vi7A==,iv:gAYgHB0ny+N6IUBY4LhUYgljcl1nsTypcBEllTKMq8g=,tag:aXqoFCHZrDg+6RRUT2owCg==,type:str]
    known_hosts: ENC[AES256_GCM,data:lyMNE4dmB36ZWwrODyPbEgiLizZRP9z4J30lMxtTfrChqUudnK1tht+E75fgk3+YLyi+slZYP2pMOA1NwsU3J8vzydHlF4vLPhfV2zhBkRk5Xq28+OGtlf+/0FirDyBzTOPD3C5n/Gwi0CHSyL0C/dTMTZCdafCr8O2mfZ5+iB8KhL/b13SwOcWZw7qgOMZ2njfrRSS2cZqyHbrVeuUh/vlDfqfWjElHOeta,iv:Vn+lmhljNgophV1V6QS3WpleEzE+JgJzX9/bm+fcaqI=,tag:v/isVS2TMhzTMGbyo0tgvQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1agltukf6ellg2guets9gq4th2nmunc965uflry7fdahtj7ea8uxq8q54ae
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxVnBxL1Z2b2hGbit4V1Uz
            b2E1b1FFUldWYWNiNTEzcmZyUGowUXEyVlRzCmt5RlMwbG5HK3FMUERjcDEwL0hp
            MUhBek5xSzZBSkZWbThtRFJYZmRuZ1EKLS0tIEp6Sy9MRG1WZlQ3dll0UlpYbEFR
            bUQvTUZzRGhnNm1sUFNyL2FtTzQvVVEK0PGZuDDdx4GjJjE15/0SAwNAht1Zlwaa
            4qGh4JwxEiJ3JXGwJuexdF6B/Fs0GoX3L417k6a86zLMyD86akZbPg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-11T23:23:55Z"
    mac: ENC[AES256_GCM,data:2cfOcxZSGQwUvkZEfLUWLA8vOC2hVb7K0wcxFzykTR61EDdveqweKv1cBkQcZWM1kE4w58R0la6RQoxFkj4HC38A8uE/mJcKF1hWl4YbAV9aHJOUtsztuKS0wZDGxIzNsMXhuCiNNNqDnS5xw6Vg2NkeyqEEqe/8MDEhEt9FeQk=,iv:AyDNVi9n/1FxoYnU2PRUtnZO70hbcNvj5ecJmqF1B2Y=,tag:VtbaHJl8EO6dkNEuSW/LvQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
