apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:GPm976tX9OXgkS3kO+I4IMQQ76mXdWVSWp3xMYI9bC68BK/nMlKYQ09VkPqL1LeDOnAC6b71Z39qrzSstB2lysDchqhjbicCdFyzURap0bp+DPRJERbdaEhXCmBhyzvBdMw1js9egOYH7Tstaba/z6oYvXT+aUUXJoRCBZmJ36owI0Brht6ypvc2tZCNoSejkrzilfNMnd7nrIvFuuk0YI7nmy+xcZn3isp10221+LwrIo1/n98rOGkMs2eTx0XSpsL3sRf1bHIuOT6L8YDjCR6MoB/QgHRtmVMbIp7i/qhjc1NCkQ3Pl1Ej0rIwdAZ8ZV5E7tAd6Q5UBJmtN6CWa5Ge8hA7o9U2KdrRh29M3/prTs3SK627t9rYtTuU5TiF,iv:/RmvY3U9+IEbCLvwwKzbvsky8x2OxELHRaaavOUwOR4=,tag:V/qwmsviRUQHepUHnvQbbg==,type:str]
    identity.pub: ENC[AES256_GCM,data:9hc0/DJE7yPr2dn6u/CoXnU/XC0e1+PWcH0SvypWIY4rbyCT8ZzRHZ32DYNcA7ssOL2RLjVtlsitCCeF2RG5KcOyb++w1Ij8WDYRm3F0SIHO7jWrXmQueLi1p8A2s3HuVcz2J8Cd4gbPTgdAy5nGd7UAR92wMrv34eLQ+2DRnkX/G72FZvbd+stGjj1TMXb/rAQd/3GHZEHoYrg0eqDhCHnVWDJ1DOnq0v4napW6/unD71Bps8BkLUpcg4Ty/YWzNZWNmyAJ2MPE2BpDUg==,iv:swJyG+bV8kLHywdBfYmUfsJz7BRQPXOaXsN4jv9GDUY=,tag:nBr6+UNjqpBRDNODmtGg8w==,type:str]
    known_hosts: ENC[AES256_GCM,data:TBmKFa6MT1Foj2NkGSg31z0XNYU39B5Wg55xVh1rX2HgXpa1Kt2wsP++FQX7X6CbvjgX5S3XIi1vFfq1pou1jsPltgEzOp1XhEQxMTGAiylphnmkc844rDt8cQmGe5QUAuQDDn+5stI4D+Q5nzsdQjSoZPKQOTso+C6kUDAQXiZVk6+dRsq18ni7AoeHTQ3EiYVext/XcZvq7LQU3JR3REBooS1gxCGOAF7e,iv:lzj/qSGDDTzno+wmFcCWPanDoJFmUkzQLfKn6Wo/fDI=,tag:ONNWxbY5t+Wcy1hEovuC9A==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1agltukf6ellg2guets9gq4th2nmunc965uflry7fdahtj7ea8uxq8q54ae
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCUXU2b2trSFR5OUNkNmpa
            S3VpSEQ4NituSDhlL2Q4VmZhWStEeE13WERNCjZJblEwYWxPN0kvakF6NGxHZVM0
            cTRBbjAxam1PZXg3OFBZYzZWS3ZIVDAKLS0tIEFEcEtoOTN3cmFxRnQvbUR1VFlv
            akZ2VEFWTVZQa0pObzlKL1JEd3ZENTAKEkag2QAVsOAdP7nw6X/irBd8IJ7gEDWO
            HULY92UKPmZC7+QQMZ0Pp9j6Ncp16XtmZX9UCrnF1o5hmUHyWMPOlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-06T04:21:48Z"
    mac: ENC[AES256_GCM,data:XNfGphHILvUH73vqSIquFHh1er9UctcZG3fw5SSNEZsNHqjnVvk/9sFaA6htyslw9/c1+X9t9TMTIXEl4xuvqRgS5fcaJT2hFafRUdG/lGw9Gtg0QF/FReY2iLKyZeciex3T2xw7i+pd75DECk7l2mOK3/Scp3uppatKPkON58g=,iv:Q+wL4mYz7vM5qn0vhhgG+S/hlyL7a+hpoOpiQRo0snA=,tag:glOQUzTp54PllzXVTEARVA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
