apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:trjrVKYHVuJeAebsXGziErfW8FNr3V5X8NBDXNJiHGTwk5KMZcAZb2loeV5Eg4JrgoMk6CafwBFGZ9Gs6Mh4kfkm8g/W/lUD8MiVw4amekuFk6d7e9pBqenzeAd9Rp7Il3Fc/m00D+ojKvLX0enez5K/er4KwrSnJhIV2Lo1d/E9RhGzvo97x+tHjZH6F5Pe+46qDPOng7bFeWHRmfwn2gLbBjHqZ4MRjaS+4n12t85cjHKF9gd4cAp33+ZkJbdOSUgIGUr73hFN+yPp6NNZCVn5eVtJ+p/d6YW6N3mTsgOVmi2mDAccLG5yvNeHZIX6Kd6GJyLXJ98IaVzygl9eUoZa/Hv3xANFwBuouehpqBlQ2AngaApyUDUeKChftmMI,iv:4tTXTxJUNADP23Tez89u8esLr+frhzMFFnQzH23DfrI=,tag:rBYgw6I8oRFL1owL+cqCcA==,type:str]
    identity.pub: ENC[AES256_GCM,data:/1HMZDoOwitJ0/B2Du9PRfbIOCZ6UQeD+jLZJ3EziweeG9I/89Isy2oK2KrQnOeqL+uLWyMR0f2xpa9D0ceitJPtCxD6nA2qMZp7zUyg2WOB8lhBHXEizxjjIV3BbY+qv1oP87ILF8Q5iubD73fvkkCfbc021biLczIldOXHIxLtmZAOdDW0LXvXcZesF1fiq8BKBOehOub58Jxzchj6FZx9ONFQoSeqsiCrxCehJLwmFPOkbW1+u+wujbMfHk79aCf8LBmrYnM6B22wwQ==,iv:b3gUooJ0sZlKGjHMp0fBnCGXALkgiPVxlgK6RG46EfU=,tag:WgTgZqDkDG6ndSB6BZiyvA==,type:str]
    known_hosts: ENC[AES256_GCM,data:PNQqdInxW42amOYm2AqTSIyuXRIVxNpAXMWS8R6+VIijmNcAbaSM/xToMJdFj5WUucvRuzD/OC9DSKBoB0V9CWgMDvkJp9PQapIXfGv3hABc5xp8Cy/+TQvbYjr/jwyKhCs41czM5/NH5q1NeXehLAyyliOopDkJE/JpbmvNgnubGk++uF+pKZn7MOF0oVJF6RZ+NGl6WmrxAy1USWZhDJ/wmc7NP1rS/Lsk,iv:pEQ2CbzN3NuqviEWoOXsw8x901SBrbq6jpbQqCS6/bc=,tag:0pYJwr1fcr/XxtHcTnUlvw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1agltukf6ellg2guets9gq4th2nmunc965uflry7fdahtj7ea8uxq8q54ae
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0NXovM0VqNHp1eFpvTWpp
            K2xHT0RHN0Q5RGN3WTh5SUNORld5dkplM1ZBCkxtNUlUSTFjVUtNaFlwNDZEUnFC
            UHpGRmMzTXJ3bmNJU2JQWUtJUm1MYjQKLS0tIERySTVPMTN6ai8ydGJ5U0VZVEpk
            YUZDdFFIcW53QlU4YVVOOHpyaGVDTXcK5PtA+YUhWS1TCCYcduZoDhsILLjjgO3M
            /KnV/nek79P5ATfytO4mIwui2XKHYI192s1OD0yiuRv0nBLQwcxgUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-19T02:08:07Z"
    mac: ENC[AES256_GCM,data:ctwy0N9SCaH/ZFMN+iJ0aefEOp1DUxcpUWKhaiOHeghAFNEZQ/6n519F1Tw2jN1dx28Tv6eLbalfouGGRNCgaHh5snjeOE3l5azTjbCkLD7EAmXqm8jnLfK+JGQYt0yJZyGaQlFCVPHLOlGA9x+9OGl6jtXJSZjmQO5Vs2B7IFE=,iv:F0eNPUhDNK6O230MIsQ0E117asQLgs2SiLG2+aZ9Z7U=,tag:7DIx1fh/nuapD7fwKOe8jg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
