apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:7PsoBUxpp43s34zrVKZg2e9TT2qeWfUvN8tp9WNDNFODKPvqgiprzjx3kR8k1yydogvz19qbfYv/EbAF0SkzKmXH+eIKejSATq4dbEeQXNjj5qdwXnWG7gfEAZzev8ThwZDrOSs2x5tKCptl9buZ6O7frouaoyKFZrQbmXVbV5sO7Mh9YUMlGOMH2VJlAF5rQU8WZIX+ukjmUaor9jv1pim8QUsRoptDrKaZTwbg7uLN98UB0BvOjL47O3Pa5fAmG1u+JDdDEBDWrb0qZ/PETIRA2WsLGuj3Wp8ZDc12NDbe849VDlGOOwoXjgEC0RluxMtoSo3i0xat3Oo8Alyqto0/jjdbq8eK7VnJ+KQOCKaz0/pAoah+TYpAJ59q70RC,iv:AO8jQVsSGDpDXB3kpEa+zRCyBoXR/svC7kMbAXR9MZ0=,tag:vhyJAbf7vjXDLK9V3pHhIg==,type:str]
    identity.pub: ENC[AES256_GCM,data:8v1UGV3OCfcU6HVQxn6ZJzNcw5PEKCuo6IYyD5FQijXKjPaY1PkUkCLbvnB0dgUIgsTQc2h1E0uipKT0nF5i+23iZyEvstvcSPsqNd6TsKuVwiCSuiF/J+BwPr2beRd9wj33RUvvX0sIMdQswcg0O/3G+6jyBRtIaP5h12LovGtMyYsDYDpiNsGAkF2Tg8iKE7oYBqQ8s1y57qEjadF8QWyn3WVomitghiR4IhQEYYtb3U9IfXdqZCmskY5ZarabZqlKl6U+XkQbTR+M+w==,iv:O8WaVAxEXZ9Yf0AYgEkqRJvPeHMAdPZT95ip/N+ahAo=,tag:/uv1hYdHPvvh9e5LPV780Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:70Ybp0nVHiMDx+tkE1sDRdLFYxnG9HrQFVqbebEInya/yxnTF+6W4NonIR/hq5L/8S8lR4WMKMSqlXTA8xvKTrFiJ1pI/9H1JFxuNmo6PSxSfWy/zjZaqqr8Bt6rpVwhbse0PCstHx4kgBHqcENG8IeEDp/01N6i5/HhBJJ+B2Pvx2z5JiZ63x+rKkQMNxZJeArj08vFnf66LjXn9rpT8zwsaHoUBn/OF0hQ,iv:IgqMhmJF/PBMI8uchsYKtqX2qlGZp1oPtCRA2TySObk=,tag:Yj0bJlSNKGYuemHSlhYQYA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1agltukf6ellg2guets9gq4th2nmunc965uflry7fdahtj7ea8uxq8q54ae
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmczg0cCtFYlZIQXU0WXpO
            Y0xGZ3k5aW5lcmJ6RDNlSnhFQUJ0YXFVOFJRCjNGNlRaait1Q0tlMFFub2Jybkk4
            TnBhcFFwU1dLc24wbTN6c0F2QWx6d0kKLS0tIHI0S243UkVqVTRPeUJvdnpWMGwz
            MStydWJGWW9mRFZMVVJDdE16VEwyVTgKArJdrKFzVOnU3PfCZ3frZHyMTG3dNIP3
            MfXHjr8ILqzUmLT7ZDgO7X5suJO9fPMhaClbE+M4durnsaBk3uD8Pw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-06T04:28:59Z"
    mac: ENC[AES256_GCM,data:aEeRSLj0TSKWmcuLv9o1MmdheyL6ThRE/1TgQF+tjmQd4l+fdb9ScUjls8zY6CK7RhIHKct5igAY8yHJeMA20wP9CcPJf3QcQwGFkVP8o9X7JkGp1Eqhh7WSrKAn2oTXZQvWaFZ9/8/jNcN/srARMw1Y3dVwB7xjDy1smaMVpiI=,iv:F22QRngQB2gpXiCimeWNwaufRwPZYIOlJYwCEyEyClU=,tag:b/D/eFG8OkGYfNtXBFUzVA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
