apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:PNU2mJruVSmEn83unsstVV9J7DzrQx5o6oNtRwpjV8c7j8j8UxidlWiTaKtbpOHfqnvpeBxBxxCge40DtRAbkH4bv+ncKu1sAxhp8Ka8khbCF/o5misBiwnQGc26UnkYABS9flHJuMaTkLwPN+UPkuBKYs1Wk4dhhl5dKveL+OlpqWNlwYGFX1+e/iRmokSi6R17CiNdJkBLll6XdQZrSfiQT2r2bCkVxGe8q6kzqVRVhAvxG9I6dfPo4ZLc0g6Z9GbtKSCEPd4yYd7XzSMmKqGPDuQeymtQ1v6SpV3RY0Yj4gGuC6CQZpB3lzN1j/3bmzPV4Jr0biiPPVzC6kBAGVCYLqg5KtYeZS7OdywTQRiisg4ANDjbntPdZRuhCB55,iv:OYFBFQUzHFbnnCjvmarYoh2smWQicZDrXtTjFOWqbfc=,tag:W/jIcY+mFXKEdVcBNKALNA==,type:str]
    identity.pub: ENC[AES256_GCM,data:BCc2qr3NbydleCRiIGCE4XtYl2Hj9Z1ux3mpTrtM6Vfz8VV4PtPTZ7OnBd1WJBs+HwnRryvczm8PbxezmbL6e/AT0dDv6Ug4pEo8DLdJwicFY+09bRKvx4Cz1o4F1YGmXjqQSgSW0Je35r6aHcGtg/APt/mzMJN6rpWX9Odz4l7MH9t6oKDyhUv8gkX847/1AAfQ3JEypfaI1QLabZOVJ3xpOZbIxtd2b1VAK6GoCpkztnyOsNaipgOTC9/ckaCfrgV5YVCUA/1hnl5Dkw==,iv:6AlTx4nLTro/65xLT1Q9acVHKTkfdXGCQc8BlxNpdlc=,tag:W6gwqZ820tq3wpDvpce0tQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:iq/N2w40hbGscrJGjgdOQiU/xvrrjq35Xf5fStwVwpIvuOIxYxViWRtV4ZZlW9tNwR6wtJ5aZapKWdHvu5yJ9OoP7R5HETzScFqlUeE1urUDCGCHviitP3CxLB7BrtwhTqZmF3W20k9j+dC5Y4zwYL7SClrlY0ZZD7wDuMQcuWx72kDVGNgikeIC9H0nfb0K46L9JDqmYeTBlSsjkVOoJQX892g8n+Id94iq,iv:21Ou7eE27l+8gsTjUVAbGqPQssVbYoq5c89tr95CEtU=,tag:9g809917S9fKLOovSweswg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1agltukf6ellg2guets9gq4th2nmunc965uflry7fdahtj7ea8uxq8q54ae
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKN3R0c1BVdW95YklraFZz
            ZVREQWgveEJ3aWNKNU55cHhhUHVkd0lScmpBCjRqZFdCRHE1OWlHdXdpYmxacXVl
            a0JWaEFDc0FydkZ3TEhha0xkOU90aE0KLS0tIHliTUorcEpXRml2MEdhb0RTUU1U
            eXpSVzhBbkV5a29YTkt0YTJJSlpvWFEKm4M5jkm5yJ4J7Z5sLDJGaVM7WkMw+gsz
            bV8x3ZM1OvOyj/rD420GOw13t7bzbwief7kWiihcCQkYDvnQXsA5gQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-25T01:48:29Z"
    mac: ENC[AES256_GCM,data:0A8Iq5taohC6ZLVMInqYVTNTcddigHPt/LT2SxKqfVSRvFmsGSZc907WI4GQ7xubpj9Bkw1urQuR4FenoeITIORYrWQxSY7B80Ws+mguj3MxYXCZjOi++F+fk13jNp9lvGtl8ukppWvGIEidahiTlyMQzOCKZ1HRMWuie92aqZg=,iv:SCfniNz6+llu6hlEd0pc7aAY6VJ+MSPj371weUBMyvM=,tag:SYxgD3EiuUsYVgFEsZtUCQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
