apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:nk1SoSx06JlN5mVfUHQzVYQDU/sJlo2hr0+EPJs4qFghcv2g6urN/16sqrvxO6OBCXxGDInnN5IQNn+ZV3TUawXLHPWZC3WkjzcWHz9eVce/hpWeKS4GN1UgBpP5xLk7NL5Trz4KYwV4MiBAK0Els+JJyLNOj17dvRoYsAnIjqxtCiRf2ZrgoOjaZgx2pB4r79vgf+mMMRvEs93a1g714DVXka8/cTlfPT+Q1/P7hev9as50N/HG6F2v/HoBzZUZiW2L08SLJnj1rzq22Ys0iNIuy/9hS5t1V5gZsxiLIW0L1jJoCrGUlrlV7WEUpAqJfStxxGUvFGZKj1tLvYYe96dpv9cWt6xpFCTAMoi9CPFZshS1jxFB32m4BAM1OJYQ,iv:kugkjHnIgk0JwP3DeA8MtfkG6SK/o0iNwWwPNewp2Xc=,tag:mY3Ap44DGbHVy4nPXYhMHA==,type:str]
    identity.pub: ENC[AES256_GCM,data:BEpNIACdSD4o5IXVfbBAtrP+Bd+TKvUgaYS1+RdqToew3FyTbPOxEKwgQb/ocn84sN+u93840ZeUca349v2qzFojyKgIwgOoxVI99lybpDuuqVRcTEhejoUj2smhjw/faZ3rJJWyyV3y68I9dK4aGLfBZYwQ1rMSK/DrO9ira+9fLonmjlUkIiut9UdROHOlrUlc+MQPwhpn4nZ/PyhI28nyCs8flxqn9SdARV7BRhfEv5ORd1Fkkmd7kGf9uHSAarstNsG/FLDdS8QZfg==,iv:Q0+vEHDeoCEMD049OjGiClPtOg5xjvysBSEAXFAhUKw=,tag:XXhc1Wm09zlMzd259cxjlg==,type:str]
    known_hosts: ENC[AES256_GCM,data:hnU35f+PiEFrzEUS+qimpKEoDNv4p4h9H5rqVjFfu30sOvD5WNH9suhYprAAPlcueb1ECEFjfA/rmxsuSyWBugoyvdaHMKGJ0fNhln6V/R7fNLG0iVk3uMDUcbsgNX0DrkAkAUWJaXAaDTO3uI5Xehbu8hYszHECbeMwg4ofHxiSWJ8AcWJ5ALHtzfqcROlkRq1avn+0Xnci25I0+UC8gMnu32DEWeCgFBEC,iv:ggUW7oFNmxg+aRIj87okYOZ2B7QT6cbRsd0yhZqP5Bk=,tag:vhhz3XDL7SxWgizAeDDB6w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1agltukf6ellg2guets9gq4th2nmunc965uflry7fdahtj7ea8uxq8q54ae
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVR3B2QnlueldMTHo0QkZt
            MUZCM2xBRzF0UUFoVlZkOE56V0dYcHVNWm1VCmN6MTRLckdqaVZMOHAyTlFWVVY4
            a3hrUHNqdDU0c3RDTUlLOWFQbFlGa2sKLS0tIGZ0cU1kbE56anAyM3ExQnFiQ3ZJ
            YWc0aHY3UTRQTEdKM2phU3hFOXdSWTgK5PAlsbqTnYA56ANzHKb1LNN66MtDvAW7
            y3whZGUGIWh9OjVpJfpmi+T3xUx+2juyat1TbE75aAhSx8hk0t1WmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-06T04:57:51Z"
    mac: ENC[AES256_GCM,data:xT51TPhDCSqMPe3ecz2FliJ/YMbvYWwRntl5Cag2udLn0xDk1QucF6ZD52Piyemw64o9uvZd4pq7w4tYpilnyPxZ7kHL18iB0jRtNyzMNeeGvi0BW2+U+UKQLOiNwjtmte7GBooFYQRL2BvJo7ESFzNM6cxRruuYKVTwEbHJH2E=,iv:t+jxDd8VBT73mOsYAsEnY6h2L/gZaSdiMuKncduqgKI=,tag:7hWW8Fyu42yAsRhmzM6DHw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
