apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: satisfactory
  namespace: games
spec:
  interval: 15m
  chart:
    spec:
      chart: satisfactory
      version: 12.5.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:

    TZ: America/Chicago

    credentials:
      cloudflare:
        type: s3
        url: "${S3URL}"
        bucket: "${S3PREFIX}"
        accessKey: "${S3ID}"
        secretKey: "${S3SECRET}"
        encrKey: "${S3ENCR}"

    service:
      main:
        type: LoadBalancer
        loadBalancerIP: ${FACTORY_IP}

    persistence:
      config:
        volsync:
          - name: config
            type: restic
            credentials: cloudflare
            dest:
              enabled: true
            src:
              enabled: true
    
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                AUTOSAVENUM: 5
                DEBUG: false
                DISABLESEASONALEVENTS: false
                LOG: true
                MAXOBJECTS: 2162688
                MAXPLAYERS: 4
                MAXTICKRATE: 30
                ROOTLESS: false
                SERVERSTREAMING: true
                SKIPUPDATE: false
                STEAMBETA: false
                TIMEOUT: 30
                VMOVERRIDE: false

    resources:
      limits:
        cpu: 20000m
        memory: 16Gi