apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudflared
  namespace: cloudflared
spec:
  interval: 15m
  chart:
    spec:
      chart: cloudflared
      version: 14.9.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:

    TZ: America/Chicago

    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                TUNNEL_TOKEN: "eyJhIjoiNTA5OTgzODBkN2M4OWI2ZjJkNmI5YzJiMGYwODQwZTEiLCJ0IjoiNDM2OGJlOTctMjE3Zi00ODI3LTgzYTEtYTU2NDQ1ZDNjYWQ0IiwicyI6Ik5UZzNOR1UwTURndE1qYzROeTAwT1RrekxUaG1OR1l0TWpNM1lXRTNNelptWmpjMyJ9"