apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: zfs-iscsi
    namespace: democratic-csi
spec:
    interval: 15m
    chart:
        spec:
            chart: democratic-csi
            version: 0.14.6
            sourceRef:
                kind: HelmRepository
                name: democratic-csi
                namespace: flux-system
            interval: 15m
    timeout: 20m
    maxHistory: 3
    driftDetection:
        mode: warn
    install:
        createNamespace: true
        remediation:
            retries: 3
    upgrade:
        cleanupOnFail: true
        remediation:
            retries: 3
    uninstall:
        keepHistory: false
    values:
        node:
            hostPID: ENC[AES256_GCM,data:G1YIBw==,iv:HcsRVl1nowo8RoU3NJ/okFBB9TU4nY2/se00JiqE9GE=,tag:DK0oZka9q1p91Hk9RlExFw==,type:bool]
            driver:
                extraEnv:
                    - name: ISCSIADM_HOST_STRATEGY
                      value: nsenter
                    - name: ISCSIADM_HOST_PATH
                      value: /usr/local/sbin/iscsiadm
                iscsiDirHostPath: ENC[AES256_GCM,data:PX2gZenvkaDz+AlxGa+BTkilafQ=,iv:EqECDgxAv0lnEMYOZweZsIAHzzR1UA3f9+Y9O7SBY3E=,tag:U4yCBa4hRMELN/qcz3Q6rg==,type:str]
                iscsiDirHostPathType: ""
        csiDriver:
            #ENC[AES256_GCM,data:ZpgaFQHb6D2T/ROIY7zsQLRNr8TZOntpMMHm98Z3MWx6eS8GgTBd8sShbUxZgw==,iv:0mcjQ0otAMa7OVVbUystDdM+38HVASsg6hKMZZMHh+E=,tag:8EQ8G6eV1My2A4sCcCuvjg==,type:comment]
            name: ENC[AES256_GCM,data:BRK/knSk4mriTtsWg7ymA8cHSzn5k3+H,iv:+FkxZ6WTLJPo1gprUtWp00amHAoo5fYF+LmDNb4vLaY=,tag:dx7Mq9H0OiGL6LXTjTdl3Q==,type:str]
        # add note here about volume expansion requirements
        storageClasses:
            - name: zfs-generic-iscsi-csi
              defaultClass: false
              reclaimPolicy: Delete
              volumeBindingMode: Immediate
              allowVolumeExpansion: true
              parameters:
                # for block-based storage can be ext3, ext4, xfs
                # for nfs should be nfs
                fsType: ext4
                # if true, volumes created from other snapshots will be
                # zfs send/received instead of zfs cloned
                # detachedVolumesFromSnapshots: "false"
                # if true, volumes created from other volumes will be
                # zfs send/received instead of zfs cloned
                # detachedVolumesFromVolumes: "false"
              mountOptions: []
              secrets:
                provisioner-secret: null
                controller-publish-secret: null
                node-stage-secret: null
                #ENC[AES256_GCM,data:XTs5VjIZaHv2bJt/3XvSF2OXC+59z6ho8Uxqktgn9JAlxRh8TyKyIvG1ZVf2wFGnyxmjfvYw8OS+JMCdRNXREvmiX3W24rVr4PAe28eWB9emwsw5FSKCAIz4s1LIeobfnApPs6U=,iv:AE0Kgfd+5G6qxjrL++9PdaTV+tRl5hrvIp6pDfGCh5k=,tag:Q8L+xA7r6bXMsyt8BmU1wQ==,type:comment]
                #ENC[AES256_GCM,data:j9aCYKyEVfWdc7tY4ji23L3aoQPp,iv:oXgFTQZKnl970yqx5TK8afnwNf7rL4Kv11Z32yfC3L4=,tag:7fUq9LeEEJqcFAGmvAslfg==,type:comment]
                #ENC[AES256_GCM,data:Dp0OXjiD8XNea4UZgrV7vjOorrg3DhGpH4QFjjmrUvr7CC4LzeOrfBGLaI2RXkx2,iv:tiFQF/jLyXLVnQJlGy2S9YdEwskOxJGLlt2qVSM7qlA=,tag:BLrU6CgaMqkxihgWPFtxlw==,type:comment]
                #ENC[AES256_GCM,data:OppaEd04DdUUvVjxXOA9lJSw2K/sTK/CG4t1GzW1kojBzFAd6DA/lTtwjHqX,iv:qbP2nLjqwR0phrk5s9vxsYr2Xws2h7+gLKJOGgmnOvk=,tag:P1vW5hPcbfTPVm55kk7eYw==,type:comment]
                #ENC[AES256_GCM,data:8prQImjLYUJ8j4+M1ihiAGnX1xPD2YKzwS1w+/Kf9USlR/cyoBNRw6tQ9EZg,iv:SvkK6G6me5vfmc4aM2VcqtIIRWc8RpuXB76fkkj8Rkk=,tag:6vqw+hB/bmYHs7rmRU1+gQ==,type:comment]
                #
                #ENC[AES256_GCM,data:b/fDIKlfhVhqcmSMTbeGQhJMDRzffeulJfAPeQ==,iv:bslRK1BeqfrEklDBarWATpHa+7t5Xfw/jAZ7AQXLlgg=,tag:Pimkd8ECXKGnxuqwDahzWw==,type:comment]
                #ENC[AES256_GCM,data:+c8+VC2/xNeO3qY1/9Utv8rf5jjW4yjbJzpxcti7hfWmBGGucaXtjXUHeIaJC48F,iv:Rk1mountLmC6JuetF30Qd+7UVrppqmhLCv57ua12Cio=,tag:VW45IcvI/yf1TWhm+SNZ7Q==,type:comment]
                #ENC[AES256_GCM,data:+Joa55JfK47v/PRaVGVxfqoDonWQQUktCI4SL0D7A3N8+FtD2/mZ9OmfA6WaxLEX,iv:SetpVNKNrtIcgAiOgdeOI8clUG8W4GQOorttuqNsRJs=,tag:G6OzDiYs0OZus7NZ3r++9g==,type:comment]
                node-publish-secret: null
                controller-expand-secret: null
        # if your cluster supports snapshots you may enable below
        volumeSnapshotClasses:
            - name: zfs-generic-iscsi-snapshot-csi
              parameters:
                #  # if true, snapshots will be created with zfs send/receive
                detachedSnapshots: "true"
        #  secrets:
        #    snapshotter-secret:
        driver:
            config:
                driver: zfs-generic-iscsi
                sshConnection:
                    host: 10.1.0.63
                    port: 22
                    username: root
                    # use either password or key
                    privateKey: ENC[AES256_GCM,data:59YvP+d6wUw2JeV9zXI/vF6uB2VKaDXlHNC/D3Mw9N59BfK/A+ioIM+9K4VJC6r7ydqtdbHln2ViVXQJucYwDFIaxVCAovFYdf1+vgzJZgY8/6UG4yzE3UsRHl6yjRMkuQfK+Mqo8RRUFDNysTQe7l01l0Jtb1zVzM0RVknd1qCTKI994YR0zjLgEl+zQqPGnictpelnvPeGqWoJ8bM+Eb9G2rQwMqUMCn1QQLZk7bbxKYCYFSsGoLpQNuv7c47B8i+sXBer5+8s3rrmfy+wToja6bJ+isESBjr6oSa9GpWCBqWq+vReKbjrt1Conu/g6KfZGdPfvbjqIzGHvsEXi5dE3dffvzwj8gN886eGGoGI7vQa998cUnJVua0Z7wlWTGhUrv0lJ0LXSKS73UZWmUROW9Pcm9AZdG6GRouXZwA7rDq53qN2Wb/yn1w/JkB5hfM7AeD0WDkExDGHiV9ltHWRvkvwZd/CxxOkEAx8D0y6cTFWssDeOsOpUt78sYjTZ9ctDMjJe2XzQQ4Bp///PWcEVglJ3FJEB8OOPOh45ji8Z3LbMES1x6UtXcNuMZPaqSiibvrdIe9MZ6UcJ30h7vEGzLu83MrKpFu2NBaqFnw1vG4UmUjY4QDSK+HRI5EFZmr44nJ9eu8at2YWYOqbhSC5JIGBurt3zxpJMqDQS9PaQ31Bm/oA9epx42DzDsY1T0V49W/m1NdasyUrb1aMFdmzi1JXD+Tw89qvf6hUhJl5kR0dvdIEPHV5Zm806gNVS2JouOjlpLZxfwzoF6jYjTHLDYyQF/amULEokf5v5q/yqfsnd0XC5Yhskq17IOoovcHctVpJBgXWJuQ6xreRqqEdNllFnf+QJGMg4WB+8eFCkjwIVXq84Pi1ht8EH17Y1fJWiflNnpQMDdRdAKDWQxtg4oU/FikuBdX1t224HFjGXdfrF3jgOsc2xMAGPLF4aGEjm3SZBxxZRSdX3Dbx78QfwpOn+CWL2gEiJE6u8TGyF3oA3HsJDZIn/59vmULZCfcqYXHESIGRlIYtMAGqD5tYs/P9YWmWYgc1z5dM9vGT7pRJRvS6/frct6B9fPg5yFQvCrEyGWJSq3XQNDgqtOUxiPnZZmsMpIB6oYyZWDWCRJfxs76Pp/YUCTL7bbcKadG4nRDK5S1tomOOTvSXdjS8CHiEKaaFnTONz4Ih0DFv55JWdyL5QueZH1DBYsm99/7T2guuJTWHuDfWaHMfdLHehQc5wACTFxvdMl3rTwnt1dwNs3ptFBnTobI8TKguOk+k3HtZvBKfm8KvkT48eH/oOnY5mxlS3B/PYf/pfeIRzojMfCHHaYGlUwqvl39t4wLnFWASAKfW7HobMTMqWFv0zenAfRU3aSkEP+Q9+dnLxsVueFW2wFCe7bGqhzcAv8Ukn4687XAwqMCSm1/Zl2wck7OB9ApmMzSTp8aXi5dkOpMlgt63lusW6cp3EvySUHIytr4Cw4xd+oJPaHcBXtOwdah+MAlkFaBCuxGE2QmlkcAdntZxCnFrLNHTamRfbNsr+/f0K8PVe5i3+6mluLDllKk5odq0mjJsNn6Si3AqWCzl5c6KQs4mv4U/ENfwCMHJsPAjLA6+Iy/nXiZAOktd1vslVxmQk1voXU5RCwGGXvarvonFimpft7IEPfa8XClaJPfdnLh2HvLRXhJboYTL7KxmFc0nANxtAY7LkNoWipf9Um0ulh8clHu23sYPVI8k5Wjd9CFk6a1pdEkMaxINSPQ17d4Ddz4jT7M4Fl5jLPppPDnq9nXzOXdiZNVJ3eVfg98c5tRSRpahjc2hdIdKKcqnEC8EKviDPSU4kIB+s9aB/uycHRqx9KJCUinz6gLum9bTYYlChDae3a65M0lM/X8sBVW1ANME0hjMOReBdD5Kqxo9pRupLdEzlyw+WsG98C0BHppnjI5+YjfTCUY6xY7odImCzwNs5uyKano1iLX3UdH4sBiNx0qZRLvC8/IyUmgGXz4asqF8QWreM5yuV3GCsWeTo5RVn4iz9MfHnJTgeDwL3c2ga3ziiRTMAdgVUvacfyBeTfNd/gV9jAND6ZnCeihY7j9cGS2W76EfMvYHykqsY8fjOeDrNo28/2MGc182mEEdyew+5A+0M1ts+b4mczIKx9dkWOs3Eguk4sA77L/Qu1zdFMfBZqQIemXakTJRG+3pUrQmdL3w/Viun8L4Wdr2nLDTt7tVH5txC1nAENnY12hJvDgTEnmXIQ9S5y4SxUr+XdsmHFNwcbhjS3YSJ8ZMarUOoU8UpTHMES1/kW1kFTJ0uJVXy6SO74rjkWpiOLorfuDxgsssuApRyUpoyaPAiLm4Mp2o5KONJRLCHwBPT15feSq4M0aJ1bgslI6H+RGzY3lJ0uuWuUeY0xUMGl2MxyrpOLfwEGTSAGnJENiDHOQdmjo/1nnIdfYmKj0JYSlX+ehUG+13gFL5A7GnFpvwCBiR7vaWGZOOk1Zjn5sjs3vRI3EBrf237X5GsuP4SLqHvqf2OP4QXiLB0wI54mzYpouRUdPMcxeTr1yJ6MbZSCS8XkpZvNksZCj/hnQXlErCWFUnsyqZVK2JYwaN8sndUZVuTMOX3F2XYJ2hNcf+hZnkGo9pQEsiAf9G/zpeHDU3a2Cb23IrsU/VlNo4Fi8kmT9M+Yi50pnv73XhN0XzpigAXYGsAlpxLKTCa7Ns9eQp1wkf9REc2BBJNJPVrSDZTt3ps9OFkQDlWNYE7FCbpteFF4H3zeS2fmh3fzEmWXD0JneQR8+smK8RPWSXWOKNFdEGdvf1OKkEclPpDl+R/UcMx2e8FTVlEs698EZUHtvluNxffvvRclUhhyME9xl3dYO2mWo+fjlsUxnzOn6XQH9+A1WlEL/OUj26/ih/q0t4EzPuVCVzWqwNGTAY+Zb6QKSnfJQ0fNUCqro3PdMAfzHVyBgLJrRrM9FVEDCOUb5rplMxeHL2N52jH3+cDxJrkF76Y9DjwhNMqooJ22njKqe8+0bpHsW5x9wNEBV0fbI8ZsHO4S2p+8ulunsZIiiirpuiAw8UhMd6nC3VkEBmidIWz0z//0s+5dHARseOkI9PskSX7Sawm4gkqHvmwNJ0IDJaRtqugW3bvauODR6oKgjYZrgSchDFyhcO6feRCT5rglxGboAy9X9sMsGJolOk1Vv5IFFRaKaLGPcj07Q5nQkQqG35KsgajuNbxbmuI7TxE8cpSUbSMPriVh3680F0KcvMCheLrBRgJwHYH8UFF05zfB7vOzZJbHgqLXVpc1wklYer/xreQp7t3O2AV/PGjXR+wvEvjv2Py92tzem73O0jQlf0y8+ODaxqKNPQRHy8DPymzsFod3lvHfHaf4g0zKHEY0SMLqJbWdbmDujH+0WgLaEBFqZQhuMGuX5D3b3cP8DoVmgkDTaC6eH4B6pGNYpol+pwSIGMVRcp1qT5fX6ITHLRYTPKlVVr50lA1Jz2Vw1FTWKn205DMVda90969/aDiZ2mvz6ixxYQfgrCEtTWtj/QQN5TgJYZr4fkdvkFpfX6zEJ6C0G69tWNGdhp2WbdtVRmGcppb4tbO/cfW17lif5pEVHpdTaABY9LL+Io1z0NIPziVrSL0jZOCdTgCY0UJ6itPzMymrzEKZ3v6vL+2ajISB8fqwYGllpF5aGoUBP59TuTv8s15GWS6SIPOM9QC0fQXxTiFAe0YfiO7m/91LYj29Xw05Sc9aBn186+mgg8X4ZPw7IUzsYnusqd2715RMtOvYTt6RVfwIpnyViaAq8fvP7R+IfQ9SdMt1+W1auO30UPH9PYOfjbdulApdH/AiBuxlLKmD0cEluD7OBYOigX9R/OLmqaXMPqc+QXI35VM1n0BfO0Y6YZswSwi9mhFN9P8tDi4lfFWyJdvORhXoZX3aO1VCgY4Uq8t0E35R9z7NqvsMXHoIILLeJ6YJR+6IzxQJd6Nz9HdC0JEUvZ4LFGVEBVvEx0JnxTpHDbtiVvWxrcjKOYrmfslrMKa5bgUgyYG5APHdXL6IFW7dWQ0UNUntXhcWkagzZauyP9JbTxxTNz6jqCLUIWkjSqQx7fXt4WxnTnYv2bmY7VBHqROP9VHBy7ER4anF61mSefnuPcEtqyIhgJ4CZJpM1FHeIuolGxCNZRFe80J1Kj1rdsnXlSJ5xu8KBD/DSk91NnEbur6HBzBqC3WJpSfI/NSO+V8RbcPKPqxB3MmmLfr6gNN4x8Obw/Poa6E+om2BJsxTkIGPgAhe9aAitiHRDmhSFoidfj+AizWNNAOKdL3jdflCQuz2rFt8K63tGb5DdXGCVUMfYM0qS1hzRP3EFVmyEEW+Da5A4d6/WM0qknijqWfWTaH+fmzN3wlvhq26zwvI2yuEP0wJPcZfhoE12vmiPwIf5TrWIHCYnCIacZOood/Jgj0q9dB7F2lqEsKChFDTQGiqRjD7jQR5Om9QqzOe4sJsE/lXQvukwVHej4kso+IcxrtYwsqfzQjchsu04p,iv:GIg8HE78MQLxXgTvZdtGpgHUwJiJoobLyEy0yq7NJYc=,tag:PNrctgVnc4Y+upN8vTtzSA==,type:str]
                zfs:
                    # can be used to override defaults if necessary
                    # the example below is useful for TrueNAS 12
                    cli:
                        #  sudoEnabled: true
                        paths:
                            zfs: /usr/sbin/zfs
                            zpool: /usr/sbin/zpool
                            sudo: /usr/bin/sudo
                            chroot: /usr/sbin/chroot
                    # can be used to set arbitrary values on the dataset/zvol
                    # can use handlebars templates with the parameters from the storage class/CO
                    #datasetProperties:
                    #  "org.freenas:description": "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}/{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
                    #  "org.freenas:test": "{{ parameters.foo }}"
                    #  "org.freenas:test2": "some value"
                    datasetParentName: Heimdall/k8s/main-cluster
                    # do NOT make datasetParentName and detachedSnapshotsDatasetParentName overlap
                    # they may be siblings, but neither should be nested in the other
                    # do NOT comment this option out even if you don't plan to use snapshots, just leave it with dummy value
                    detachedSnapshotsDatasetParentName: Heimdall/k8s/main-cluster-snapshots
                    # "" (inherit), lz4, gzip-9, etc
                    zvolCompression: inherit
                    # "" (inherit), on, off, verify
                    zvolDedup: inherit
                    zvolEnableReservation: false
                    # 512, 1K, 2K, 4K, 8K, 16K, 64K, 128K default is 16K
                    zvolBlocksize: null
                iscsi:
                    shareStrategy: targetCli
                    # https://kifarunix.com/how-to-install-and-configure-iscsi-storage-server-on-ubuntu-18-04/
                    # https://kifarunix.com/how-install-and-configure-iscsi-storage-server-on-centos-7/
                    # https://linuxlasse.net/linux/howtos/ISCSI_and_ZFS_ZVOL
                    # http://www.linux-iscsi.org/wiki/ISCSI
                    # https://bugzilla.redhat.com/show_bug.cgi?id=1659195
                    # http://atodorov.org/blog/2015/04/07/how-to-configure-iscsi-target-on-red-hat-enterprise-linux-7/
                    shareStrategyTargetCli:
                        #sudoEnabled: true
                        basename: iqn.2003-01.org.linux-iscsi.proxmox-82.x8664
                        tpg:
                            attributes:
                                # set to 1 to enable CHAP
                                authentication: ENC[AES256_GCM,data:AQ==,iv:2Vg8L+DWBcuyLbwAMe+vbSh0XrqiZzw/ekkQg0Jp5z8=,tag:+IdsZHny8VsNWuQCEgwKUA==,type:int]
                                # this is required currently as we do not register all node iqns
                                # the effective outcome of this is, allow all iqns to connect
                                generate_node_acls: 1
                                cache_dynamic_acls: ENC[AES256_GCM,data:bw==,iv:DTf3Zcr2EG+YQhHDGsfwxyPL5mH2BoL+vR9Xqe29Htc=,tag:EuJongN4g85HINq34Nvhxg==,type:int]
                                # if generate_node_acls is 1 then must turn this off as well (assuming you want write ability)
                                demo_mode_write_protect: 0
                            auth: null
                            # CHAP
                            #userid: "foo"
                            #password: "bar"
                            # mutual CHAP
                            #mutual_userid: "baz"
                            #mutual_password: "bar"
                        block:
                            attributes:
                                # set to 1 to enable Thin Provisioning Unmap
                                emulate_tpu: 0
                    targetPortal: 10.1.0.63:3260
                    # for multipath
                    targetPortals: []
                    # leave empty to omit usage of -I with iscsiadm
                    interface: ""
                    # MUST ensure uniqueness
                    # full iqn limit is 223 bytes, plan accordingly
                    # default is "{{ name }}"
                    #nameTemplate: "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}-{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
                    namePrefix: csi-
                    nameSuffix: -cluster
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1agltukf6ellg2guets9gq4th2nmunc965uflry7fdahtj7ea8uxq8q54ae
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaZFBnWlNKbEVtSnp5Y2x5
            ZE9RN1BWVjFWZE1KT1p5NUc0OHpwUlhJcDM4CjNNbHY0dmlRTG9ycElBQkUyMXpt
            akJTZm9neDVKYmk2OXk0R1JMclgwZlEKLS0tIGZiUVZ6OVZuWUpNRWFFTkcwaDVK
            amsrWGQ5Y0VZaUU1SWNVK2JGRXBDemsKIw15cCpYVkEz7whDSVrBSozti/ocULj0
            LnnYwW3SuhbQRNHuH5c123TR2zAzgNkMjC0b9micKKWdoqnDFPg6Nw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-01T23:39:06Z"
    mac: ENC[AES256_GCM,data:IWxHgYhbMkd8HGtcS9DbOzaqQKuGxR5jn45IF5CFO/q+Cdn3wzQu3CS3OFUph3HcHC7aOxyTtHuio1fS4dKunlCe0o9D+y+byrJlKUR3/IWhazL6FO9k5Yebn5qzEBcd2EXXKVuz5+59s3oKxCJUqfpbIteZkK8bVimZWhoMiSo=,iv:VlzmhXExgvHQ52MIfe8a9pvc1beCXCGq/58DvNBrpMY=,tag:uJn5jB7EqikSvLy9vHG63A==,type:str]
    pgp: []
    encrypted_regex: ((?i)(privateKey|displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
