apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: h5ai
    namespace: h5ai
spec:
    interval: 15m
    chart:
        spec:
            chart: h5ai
            version: 7.2.1
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
            interval: 15m
    timeout: 20m
    maxHistory: 3
    driftDetection:
        mode: warn
    install:
        createNamespace: true
        remediation:
            retries: 3
    upgrade:
        cleanupOnFail: true
        remediation:
            retries: 3
    uninstall:
        keepHistory: false
    values:
        TZ: America/Chicago
        persistence:
            config:
                enabled: true
                type: pvc
                size: 16Gi
                mountPath: /config
            directorystorage:
                enabled: true
                mountPath: /h5ai
                readOnly: true
                type: nfs
                server: 10.1.0.4
                path: /mnt/Jormungandr/Media/NSFW/HTML/
        portal:
            open:
                enabled: true
        securityContext:
            container:
                readOnlyRootFilesystem: false
                runAsGroup: 0
                runAsUser: 0
        service:
            main:
                ports:
                    main:
                        port: 80
                        protocol: tcp
                        targetPort: 80
        ingress:
            main:
                enabled: true
                hosts:
                    - host: games.tinoco.casa
                      paths:
                        - path: /
                          pathType: Prefix
                integrations:
                    certManager:
                        enabled: true
                        certificateIssuer: cloudflare
                    traefik:
                        allowCors: false
                        enabled: true
                        entrypoints:
                            - websecure
        securityContext:
            container:
                UMASK: "0022"
                readOnlyRootFilesystem: false
                runAsGroup: 0
                runAsUser: 0
            pod:
                fsGroupChangePolicy: OnRootMismatch
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1agltukf6ellg2guets9gq4th2nmunc965uflry7fdahtj7ea8uxq8q54ae
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Y3lmSDhPUXE4OUplSk4x
            NWpGZnFMMXRyWndFd1RDR1pKMWUyM0lHRTB3CkFEZThCVUxIcFlBaU44VFZpUmlL
            TVFZdlUxdVYrQ1hvTGJDZjJOTnM3Qm8KLS0tIHJDYjArUFRIQUsraXhSdThLaTFX
            clFhZVRxODFKeTh1TkVyWG9oNGg4eEkKB6OwNKTviSGkkMOrqb0GqDetyw8HfSO+
            GldH4rPc55rmk07jFsQzv7MNlN4ScTz20fN57mb49VcJ+A84ABBoRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-03T22:38:15Z"
    mac: ENC[AES256_GCM,data:q2QOQEg3ms+vIe6C0Cev9LYB/BqM+yQH2PBXKaclZqbULVeR8uk9dcUVycXgpjb2UYYKzLSiaTRTKxFyKnweVa1Te4LhGub03KFT2YTtImtz9LX2UjI8l4JCL9jX5FRy9LQpls06Wx3UcFPdxoh/ZwYDM1ojqes7JyfxHUK+uwg=,iv:oNtNNi+E1BwPqVJkANnV4+9B39dTPV0PO95r0VVG4cw=,tag:raJv27W2v9kZH5xscr5RNw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(password))
    version: 3.9.1
