apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: h5ai
    namespace: h5ai
spec:
    interval: 15m
    chart:
        spec:
            chart: h5ai
            version: 7.2.1
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
            interval: 15m
    timeout: 20m
    maxHistory: 3
    driftDetection:
        mode: warn
    install:
        createNamespace: true
        remediation:
            retries: 3
    upgrade:
        cleanupOnFail: true
        remediation:
            retries: 3
    uninstall:
        keepHistory: false
    values:
        TZ: America/Chicago
        persistence:
            config:
                enabled: true
                type: pvc
                size: 256Gi
                mountPath: /config
            directorystorage:
                enabled: true
                mountPath: /h5ai
                readOnly: true
                type: nfs
                server: 10.1.0.4
                path: /mnt/Jormungandr/Media/NSFW/HTML/
        portal:
            open:
                enabled: true
        securityContext:
            container:
                readOnlyRootFilesystem: false
                runAsGroup: 0
                runAsUser: 0
        service:
            main:
                ports:
                    main:
                        port: 80
                        protocol: tcp
                        targetPort: 80
        ingress:
            main:
                enabled: true
                hosts:
                    - host: games.tinoco.casa
                      paths:
                        - path: /
                          pathType: Prefix
                integrations:
                    certManager:
                        enabled: true
                        certificateIssuer: cloudflare
                    traefik:
                        allowCors: false
                        enabled: true
                        entrypoints:
                            - websecure
        securityContext:
            container:
                UMASK: "0022"
                readOnlyRootFilesystem: false
                runAsGroup: 0
                runAsUser: 0
            pod:
                fsGroupChangePolicy: OnRootMismatch
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1agltukf6ellg2guets9gq4th2nmunc965uflry7fdahtj7ea8uxq8q54ae
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0d2lzR0x3NjZuME5kcVVE
            a1J0VTg5TWRxeHgwMG5ZZDZHcmN1U3hrcFFVCm1EajNKUENZcXR4TzBuSHZwWlYr
            UHI4Sit3VDZ4eC82SDUxZEp1YVBPTlkKLS0tIFVVeTlqVm5pM1NNZzQvdWdlQm9T
            Skp6UStuWlpzajlBakE3Z1FYTXFQcW8KP1W3k7IQY9GyNMkc26CMRl4wxLu5F9JO
            FzkgeYVMX1AcV8yj7IIFls4ZJFeUr4KUgCNjPF+AHz6FN7Q8MXMfMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-03T22:43:27Z"
    mac: ENC[AES256_GCM,data:r/BqbuKRc8iY20MowIfaftr7yrPhIENAVAAg/7j5SDYKeyWwdeI2OpBYZk7KxB8sT0BsWqJRB1XU6ei53YdXyD3wsh+pKOckkMFilOE1RgDiJ4gzCxIh1/ZfaS4xFTReaoDucku15hRfIJMbdBqQWbRDS81Pp3/+WVr64eFA0RE=,iv:EAmy2KgoGvQmToOMWXzvS5Q0LdWB+3E6sifIHnX8Cmc=,tag:4QGgIhULfum3FQZM8AW8Jw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(password))
    version: 3.9.1
