apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: h5ai
    namespace: h5ai
spec:
    interval: 15m
    chart:
        spec:
            chart: h5ai
            version: 7.2.1
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
            interval: 15m
    timeout: 20m
    maxHistory: 3
    driftDetection:
        mode: warn
    install:
        createNamespace: true
        remediation:
            retries: 3
    upgrade:
        cleanupOnFail: true
        remediation:
            retries: 3
    uninstall:
        keepHistory: false
    values:
        TZ: America/Chicago
        persistence:
            config:
                enabled: true
                type: pvc
                size: 256Gi
                mountPath: /config
            directorystorage:
                enabled: true
                mountPath: /h5ai
                readOnly: true
                type: nfs
                server: 10.1.0.4
                path: /mnt/Jormungandr/Media/NSFW/HTML/
        portal:
            open:
                enabled: true
        securityContext:
            container:
                readOnlyRootFilesystem: false
                runAsGroup: 0
                runAsUser: 0
        service:
            main:
                ports:
                    main:
                        port: 80
                        protocol: tcp
                        targetPort: 80
        ingress:
            main:
                enabled: true
                hosts:
                    - host: games.tinoco.casa
                      paths:
                        - path: /
                          pathType: Prefix
                integrations:
                    certManager:
                        enabled: true
                        certificateIssuer: cloudflare
                    traefik:
                        allowCors: false
                        enabled: true
                        entrypoints:
                            - websecure
        securityContext:
            container:
                UMASK: "0022"
                readOnlyRootFilesystem: false
                runAsGroup: 0
                runAsUser: 0
            pod:
                fsGroupChangePolicy: OnRootMismatch
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1agltukf6ellg2guets9gq4th2nmunc965uflry7fdahtj7ea8uxq8q54ae
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwOVk1MVdoK1ZjajNhbUt2
            Y05YMEZCK05HazBxWitOU2F1REFDMVdIWlZVCjAvVm1JSTE2dkVPQjRVWmhzcXhX
            RDhCN2pxUmtEM0E5NnFTM3ZPQ29ZSTQKLS0tIEU2cGE3bXFBbmxyY3hzK2NjeVpT
            K2h4WnVvejRHbWZSQnNRb3Y5U3FRQWMKHF2lYRlECl4lno9VGD8CRATrhm9bVZPb
            qBBk/2TuzyZKRV27vlN9pXZzANf3CcnNNfWCLNuPn+naBcXVn1HRVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-08T18:59:04Z"
    mac: ENC[AES256_GCM,data:8JerDLoA/SyPIEkJcNDNjIbolF7SYWVZND40ZeUqg4IWCV1MEtCEb0PoHhHpfRh0YetFbxMl7Be0RsXDj9vypzIvYeJo9Kmk79+u2Rr0M7ju7obWQahvSr/a1JPHRDi0eWRO17OVMOmKn+/9jrdkMrFvPeIPBmazi5QgQkRBjhE=,iv:IHF33Geka8tYp/WcO7gNeGFgVKANTH598RIPbtFKYA0=,tag:mopfwwwP3MZUzcbAw83XYg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(password))
    version: 3.9.1
