apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: protonmail-bridge
  namespace: protonmail-bridge
spec:
  interval: 15m
  chart:
    spec:
      chart: protonmail-bridge
      version: 17.6.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:

    TZ: America/Chicago

    credentials:
      cloudflare:
        type: s3
        url: "${S3URL}"
        bucket: "${S3PREFIX}"
        accessKey: "${S3ID}"
        secretKey: "${S3SECRET}"
        encrKey: "${S3ENCR}"

    service:
      imap:
        type: LoadBalancer
        loadBalancerIP: ${PROTON_IP}
      smtp:
        type: LoadBalancer
        loadBalancerIP: ${PROTON_IP}

    persistence:
      config:
        volsync:
          - name: config
            type: restic
            credentials: cloudflare
            dest:
              enabled: true
            src:
              enabled: true