apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: unifi
  namespace: unifi
spec:
  interval: 15m
  chart:
    spec:
      chart: unifi
      version: 22.7.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:

    TZ: America/Chicago

    credentials:
      cloudflare:
        type: s3
        url: "${S3URL}"
        bucket: "${S3PREFIX}"
        accessKey: "${S3ID}"
        secretKey: "${S3SECRET}"
        encrKey: "${S3ENCR}"

    service:
      main:
        type: LoadBalancer
        loadBalancerIP: ${UNIFI_IP}
      comm:
        type: LoadBalancer
        loadBalancerIP: ${UNIFI_IP}
      guestportal:
        type: LoadBalancer
        loadBalancerIP: ${UNIFI_IP}
      speedtest:
        type: LoadBalancer
        loadBalancerIP: ${UNIFI_IP}
      stun:
        type: LoadBalancer
        loadBalancerIP: ${UNIFI_IP}

    persistence:
      config:
        storageClass: heimdall-nfs-csi
        volsync:
          - credentials: cloudflare
            dest:
              enabled: false
            name: config
            src:
              enabled: true
            type: restic
        data:
        storageClass: heimdall-nfs-csi
        volsync:
          - credentials: cloudflare
            dest:
              enabled: false
            name: data
            src:
              enabled: true
            type: restic
        certs:
          storageClass: heimdall-nfs-csi
          volsync:
            - credentials: cloudflare
              dest:
                enabled: false
              name: certs
              src:
                enabled: true
              type: restic

    ingress:
      main:
        required: true
        enabled: true
        hosts:
          - host: unifi.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          traefik:
            enabled: true
          certManager:
            enabled: true
            certificateIssuer: tinoco-le-prod