apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: unifi
  namespace: unifi
spec:
  interval: 15m
  chart:
    spec:
      chart: unifi
      version: 24.9.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:

    TZ: America/Chicago

    credentials:
      cloudflare:
        type: s3
        url: "${S3URL}"
        bucket: "${S3PREFIX}"
        accessKey: "${S3ID}"
        secretKey: "${S3SECRET}"
        encrKey: "${S3ENCR}"

    service:
      main:
        type: LoadBalancer
        loadBalancerIP: ${UNIFI_IP}
      comm:
        type: LoadBalancer
        loadBalancerIP: ${UNIFI_IP}
      guestportal:
        type: LoadBalancer
        loadBalancerIP: ${UNIFI_IP}
      speedtest:
        type: LoadBalancer
        loadBalancerIP: ${UNIFI_IP}
      stun:
        type: LoadBalancer
        loadBalancerIP: ${UNIFI_IP}

    persistence:
      config:
        volsync:
          - name: config
            type: restic
            credentials: cloudflare
            dest:
              enabled: true
            src:
              enabled: true
      data:
        volsync:
          - name: data
            type: restic
            credentials: cloudflare
            dest:
              enabled: true
            src:
              enabled: true
      certs:
        volsync:
          - name: certs
            type: restic
            credentials: cloudflare
            dest:
              enabled: true
            src:
              enabled: true

    ingress:
      main:
        enabled: true
        ingressClassName: internal
        integrations:
          traefik:
            enabled: false
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
        hosts:
          - host: unifi.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix