apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: netbootxyz
  namespace: netbootxyz
spec:
  interval: 15m
  chart:
    spec:
      chart: netbootxyz
      version: 7.3.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:

    TZ: America/Chicago

    service:
      tftp:
        type: LoadBalancer
        loadBalancerIPs:
          - ${NETBOOT_IP1}
          - ${NETBOOT_IP2}