apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: plex
      version: 19.3.5
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:

    TZ: America/Chicago

    credentials:
      cloudflare:
        type: s3
        url: "${S3URL}"
        bucket: "${S3PREFIX}"
        accessKey: "${S3ID}"
        secretKey: "${S3SECRET}"
        encrKey: "${S3ENCR}"

    plex:
      serverIP: ${PLEX_IP}
      additionalAdvertiseURL: "https://plex.tinoco.casa"
      disableGDM: true
      requireHTTPS: false
    
    env:
      # User Defined
      ALLOWED_NETWORKS: "172.16.0.0/12,10.0.0.0/8,192.168.0.0/16"
      PLEX_CLAIM: ""

    service:
      main:
        type: LoadBalancer
        loadBalancerIP: ${PLEX_IP}

    persistence:
      config:
        storageClass: heimdall-nfs-csi
        volsync:
          - name: config
            credentials: cloudflare
            dest:
              enabled: true
              cacheCapacity: 10Gi
            src:
              enabled: true
              cacheCapacity: 10Gi
      series:
        enabled: true
        existingClaim: media-series-nfs-pvc
        mountPath: "/media/series"
      movies:
        enabled: true
        existingClaim: media-movies-nfs-pvc
        mountPath: "/media/movies"
      anime:
        enabled: true
        existingClaim: media-anime-nfs-pvc
        mountPath: "/media/anime"


    ingress:
      main:
        required: true
        enabled: true
        hosts:
          - host: plex.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          traefik:
            enabled: true
          certManager:
            enabled: true
            certificateIssuer: tinoco-le-prod