apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: heimdall-iscsi
    namespace: democratic-csi
spec:
    interval: 15m
    chart:
        spec:
            chart: democratic-csi
            version: 0.14.7
            sourceRef:
                kind: HelmRepository
                name: democratic-csi
                namespace: flux-system
            interval: 15m
    timeout: 20m
    maxHistory: 3
    driftDetection:
        mode: warn
    install:
        createNamespace: true
        remediation:
            retries: 3
    upgrade:
        cleanupOnFail: true
        remediation:
            retries: 3
    uninstall:
        keepHistory: false
    values:
        csiDriver:
            name: org.democratic-csi.heimdall-iscsi
        storageClasses:
            - name: heimdall-iscsi-csi
              defaultClass: false
              reclaimPolicy: Delete
              volumeBindingMode: Immediate
              allowVolumeExpansion: true
              parameters:
                # for block-based storage can be ext3, ext4, xfs
                # for nfs should be nfs
                fsType: ext4
                detachedVolumesFromSnapshots: "false"
              mountOptions: []
              secrets:
                provisioner-secret: null
                controller-publish-secret: null
                node-stage-secret: null
                #      # any arbitrary iscsiadm entries can be add by creating keys starting with node-db.<entry.name>
                #      # if doing CHAP
                #      node-db.node.session.auth.authmethod: CHAP
                #      node-db.node.session.auth.username: foo
                #      node-db.node.session.auth.password: bar
                #
                #      # if doing mutual CHAP
                #      node-db.node.session.auth.username_in: baz
                #      node-db.node.session.auth.password_in: bar
                node-publish-secret: null
                controller-expand-secret: null
        volumeSnapshotClasses:
            - name: heimdall-iscsi-snapshot-csi
              parameters:
                detachedSnapshots: "true"
              secrets:
                snapshotter-secret: null
        driver:
            config:
                driver: zfs-generic-iscsi
                sshConnection:
                    host: 10.1.0.63
                    port: 22
                    username: root
                    privateKey: ENC[AES256_GCM,data:MMLs++OCozrljdueX08JqspcZ8QIU3WXex2gqmnos+PYd5mJYhm/wbyBFU0Y3+gKhbm3CuRoPPEQnEoRyH3K3IjcxXBTvZonRPI1Bc1ZVkZjItEgyIoPMvjuup6SkSdtvH+Zz2wk70ATlXfAX3bvEdPTB6xBEs0G319hTQ1gC/azZuNBDk5pNzokzsKnyR2JKi9HCBDpV6/E2tgeitY1ANz6YyuBCbb3XqLSJ0Cvo/kt/92X4vMundZu9kt6GKLvvF78di5e6xWX/QuKCpV2lX7G2M7KcWBFwYSo+RgfDGnckGhocTNLPqxsSgwCTNLxMqSkOf1X1sFsiwPFlpHAHJNJx/1Ex5K9E6yjXj3aC/C1o0FI7WF1+w06gKbuJK7IZsygieYlz/krUU4AtZBU4YNpd5jl0IGJZQTEmOrHMU8CHTKbfbuAq2tKheZv5cN0l3LWo/rpQj/9/4AlZ4AG4fBQ/F5YmJVz75MxGACtTk8A0HBZUWq8LLMwoGmthnOGevUJPjHGU4VvPeUFNIsl,iv:awklR498x2FOK4snt4J9ZN8x1RR5WUFgd9Sd3cD5jJM=,tag:ariKsYjcIAw74s4+yK49Gg==,type:str]
                zfs:
                    cli:
                        #  sudoEnabled: true
                        paths:
                            zfs: /usr/sbin/zfs
                            zpool: /usr/sbin/zpool
                            sudo: /usr/bin/sudo
                            chroot: /usr/sbin/chroot
                    datasetProperties:
                        org.freenas:description: '{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}/{{ parameters.[csi.storage.k8s.io/pvc/name] }}'
                    datasetParentName: Heimdall/k8s/main-cluster/iscsi/pvc
                    detachedSnapshotsDatasetParentName: Heimdall/k8s/main-cluster/iscsi/snapshot
                    # "" (inherit), lz4, gzip-9, etc
                    zvolCompression: inherit
                    # "" (inherit), on, off, verify
                    zvolDedup: "off"
                    zvolEnableReservation: false
                    # 512, 1K, 2K, 4K, 8K, 16K, 64K, 128K default is 16K
                    zvolBlocksize: 4k
                iscsi:
                    shareStrategy: targetCli
                    # https://kifarunix.com/how-to-install-and-configure-iscsi-storage-server-on-ubuntu-18-04/
                    # https://kifarunix.com/how-install-and-configure-iscsi-storage-server-on-centos-7/
                    # https://linuxlasse.net/linux/howtos/ISCSI_and_ZFS_ZVOL
                    # http://www.linux-iscsi.org/wiki/ISCSI
                    # https://bugzilla.redhat.com/show_bug.cgi?id=1659195
                    # http://atodorov.org/blog/2015/04/07/how-to-configure-iscsi-target-on-red-hat-enterprise-linux-7/
                    shareStrategyTargetCli:
                        #sudoEnabled: true
                        basename: iqn.1993-08.org.debian
                        tpg:
                            attributes:
                                # set to 1 to enable CHAP
                                authentication: 0
                                # this is required currently as we do not register all node iqns
                                # the effective outcome of this is, allow all iqns to connect
                                generate_node_acls: 1
                                cache_dynamic_acls: 1
                                # if generate_node_acls is 1 then must turn this off as well (assuming you want write ability)
                                demo_mode_write_protect: 0
                            auth: null
                            # CHAP
                            #userid: "foo"
                            #password: "bar"
                            # mutual CHAP
                            #mutual_userid: "baz"
                            #mutual_password: "bar"
                        block:
                            attributes:
                                # set to 1 to enable Thin Provisioning Unmap
                                emulate_tpu: 0
                    targetPortal: 10.1.0.63:3260
                    # for multipath
                    targetPortals: []
                    # leave empty to omit usage of -I with iscsiadm
                    interface: ""
                    # MUST ensure uniqueness
                    # full iqn limit is 223 bytes, plan accordingly
                    # default is "{{ name }}"
                    nameTemplate: '{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}-{{ parameters.[csi.storage.k8s.io/pvc/name] }}'
                    namePrefix: csi-
                    nameSuffix: -cluster
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1agltukf6ellg2guets9gq4th2nmunc965uflry7fdahtj7ea8uxq8q54ae
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1RTFYUTIwY0k2UTlNYzdt
            T09WV213Y2cyRFFuRzgrNjk0MS9NSXNRMWpNCmhlQmJ2SUpQcHpXbVc1WE5YRjhT
            SGYxK0orNVh2azhjVWFnRTJZTkZKZTAKLS0tIFF6cG5taFl6SDIvQXJ5Ri9zZ1o2
            SGV0bFJ6NmRqd25TU3FOVk45TzhKU0kKxS9oNYNgQlfZ5r3Q5GIVui+OBKEL85JH
            01YrKvvOUbGSbZVr6QBwRC9MAlxw7R+5Z+8SMm5YG+RNV15zkvvZfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-29T21:34:37Z"
    mac: ENC[AES256_GCM,data:49N1XIQV1lSgszZVaswBGW+Mu+l1DggudzkK7XHib2gTqqyWLZB19blprE9d4o7zVhJfbuaZsRdKn+kt83T/tzi2NuFRQREJcICK0BOLkC9U8jh0LuVqOg+Npwh4RHT2fOii9R+gkE0gSJtCx/Vz4W6i3MvGXxTJArhg77uSsnw=,iv:+85PQt+YZNUwC2iEUNrA+cRxd5CLeRPeEMuQVN1ecM0=,tag:IflPXKYikVMwca2m1Dlx7A==,type:str]
    pgp: []
    encrypted_regex: ((?i)(privateKey))
    version: 3.9.1
