apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: heimdall-iscsi
    namespace: democratic-csi
spec:
    interval: 15m
    chart:
        spec:
            chart: democratic-csi
            version: 0.14.6
            sourceRef:
                kind: HelmRepository
                name: democratic-csi
                namespace: flux-system
            interval: 15m
    timeout: 20m
    maxHistory: 3
    driftDetection:
        mode: warn
    install:
        createNamespace: true
        remediation:
            retries: 3
    upgrade:
        cleanupOnFail: true
        remediation:
            retries: 3
    uninstall:
        keepHistory: false
    values:
        csiDriver:
            # should be globally unique for a given cluster
            name: org.democratic-csi.iscsi
        # add note here about volume expansion requirements
        storageClasses:
            - name: heimdall-iscsi-csi
              defaultClass: false
              reclaimPolicy: Delete
              volumeBindingMode: Immediate
              allowVolumeExpansion: true
              parameters:
                # for block-based storage can be ext3, ext4, xfs
                # for nfs should be nfs
                fsType: ext4
                # if true, volumes created from other snapshots will be
                # zfs send/received instead of zfs cloned
                # detachedVolumesFromSnapshots: "false"
                # if true, volumes created from other volumes will be
                # zfs send/received instead of zfs cloned
                # detachedVolumesFromVolumes: "false"
              mountOptions: []
              secrets:
                provisioner-secret: null
                controller-publish-secret: null
                node-stage-secret: null
                #      # any arbitrary iscsiadm entries can be add by creating keys starting with node-db.<entry.name>
                #      # if doing CHAP
                #      node-db.node.session.auth.authmethod: CHAP
                #      node-db.node.session.auth.username: foo
                #      node-db.node.session.auth.password: bar
                #
                #      # if doing mutual CHAP
                #      node-db.node.session.auth.username_in: baz
                #      node-db.node.session.auth.password_in: bar
                node-publish-secret: null
                controller-expand-secret: null
        # if your cluster supports snapshots you may enable below
        volumeSnapshotClasses:
            - name: heimdall-iscsi-snapshot-csi
              parameters:
                #  # if true, snapshots will be created with zfs send/receive
                detachedSnapshots: "true"
              secrets:
                snapshotter-secret: null
        driver:
            config:
                driver: zfs-generic-iscsi
                sshConnection:
                    host: 10.1.0.63
                    port: 22
                    username: root
                    # use either password or key
                    privateKey: ENC[AES256_GCM,data:1amPwgx6o0i2nSYJwflxiuNT+QD009T+kDw9PZbBMfmFpKQMI14pJSjHRCpBC+AVscF7rEIteIjdts9omqJ0KhcTGAdSLgL/9PPShnwCUl1zy93ohQYYkDL3KEnzO4aqCAGCKTM9YlE+uG+9/+nDtVUH2H+NWawFj4Bc0v/83rUjtNiaJCZn9KubiukygPqwSBpd02tQDUQ+Tf8vtOtxipmMuei24WX2ppj9htjvSrbvUS0XaE8LdekrocpAKzzOP8/BDRgu+RSvAykUdhwTCTDDsLW2X8sQHedZ+XsLCUVdNCeBA85KVh7ZY1uVWoODQKzSqaqoALgedbqoR0tcVxMBRLGY/F/ZvUoPhfLdtb4u1Iz8fH+fAHhjaoKHWigk2XJp1mQlZT8CrrCqp0nt+/rqWWC1hWzg4f6RdhpnQQJBWdX2ergKqZJUs3AxispxWESHHl5VS3n7w5Y/rlk1A7wlPxcyBoKrhsnf9nGYluLj9psqLjl8zcOZNmgdwcn7UTvIBr/qlIi0RZ7WdyFl,iv:vsZ6L2bvVb+2AWDw1l1qW9EkYB5OiT7m6OCAeSAQK7c=,tag:X3MvJP49rLGT6YSgDkZ45w==,type:str]
                zfs:
                    # can be used to override defaults if necessary
                    # the example below is useful for TrueNAS 12
                    cli:
                        #  sudoEnabled: true
                        paths:
                            zfs: /usr/sbin/zfs
                            zpool: /usr/sbin/zpool
                            sudo: /usr/bin/sudo
                            chroot: /usr/sbin/chroot
                    # can be used to set arbitrary values on the dataset/zvol
                    # can use handlebars templates with the parameters from the storage class/CO
                    #datasetProperties:
                    #  "org.freenas:description": "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}/{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
                    #  "org.freenas:test": "{{ parameters.foo }}"
                    #  "org.freenas:test2": "some value"
                    datasetParentName: Heimdall/k8s/main-cluster
                    # do NOT make datasetParentName and detachedSnapshotsDatasetParentName overlap
                    # they may be siblings, but neither should be nested in the other
                    # do NOT comment this option out even if you don't plan to use snapshots, just leave it with dummy value
                    detachedSnapshotsDatasetParentName: Heimdall/k8s/main-cluster-snapshots
                    # "" (inherit), lz4, gzip-9, etc
                    zvolCompression: inherit
                    # "" (inherit), on, off, verify
                    zvolDedup: inherit
                    zvolEnableReservation: false
                    # 512, 1K, 2K, 4K, 8K, 16K, 64K, 128K default is 16K
                    zvolBlocksize: 4k
                iscsi:
                    shareStrategy: targetCli
                    # https://kifarunix.com/how-to-install-and-configure-iscsi-storage-server-on-ubuntu-18-04/
                    # https://kifarunix.com/how-install-and-configure-iscsi-storage-server-on-centos-7/
                    # https://linuxlasse.net/linux/howtos/ISCSI_and_ZFS_ZVOL
                    # http://www.linux-iscsi.org/wiki/ISCSI
                    # https://bugzilla.redhat.com/show_bug.cgi?id=1659195
                    # http://atodorov.org/blog/2015/04/07/how-to-configure-iscsi-target-on-red-hat-enterprise-linux-7/
                    shareStrategyTargetCli:
                        #sudoEnabled: true
                        basename: iqn.1993-08.org.debian
                        tpg:
                            attributes:
                                # set to 1 to enable CHAP
                                authentication: 0
                                # this is required currently as we do not register all node iqns
                                # the effective outcome of this is, allow all iqns to connect
                                generate_node_acls: 1
                                cache_dynamic_acls: 1
                                # if generate_node_acls is 1 then must turn this off as well (assuming you want write ability)
                                demo_mode_write_protect: 0
                            auth: null
                            # CHAP
                            #userid: "foo"
                            #password: "bar"
                            # mutual CHAP
                            #mutual_userid: "baz"
                            #mutual_password: "bar"
                        block:
                            attributes:
                                # set to 1 to enable Thin Provisioning Unmap
                                emulate_tpu: 0
                    targetPortal: 10.1.0.63:3260
                    # for multipath
                    targetPortals: []
                    # leave empty to omit usage of -I with iscsiadm
                    interface: ""
                    # MUST ensure uniqueness
                    # full iqn limit is 223 bytes, plan accordingly
                    # default is "{{ name }}"
                    #nameTemplate: "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}-{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
                    namePrefix: csi-
                    nameSuffix: -cluster
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1agltukf6ellg2guets9gq4th2nmunc965uflry7fdahtj7ea8uxq8q54ae
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwcUZMQ2h6QkhoYWpkWjhz
            UjJXclpPWUdwd0g3ODdEb01EU01MNVlzRUQ0Ck4wUEtXNFhoRVRYMFcvVmlVOHlY
            SndwaVNjM0hGRlN3bVlRb0tBSnVNYTAKLS0tIEkvcCs1OXIrVDJZdUFrTVJrTjZN
            a0NxMWIyRUNHWDNCU2hiRHc2RWExeHcKtX4qwJjyJEMBxcTlAIcc1K+jRcCay0lI
            TqGJCvFRnFbBBagV6fDERjGVgWbg4zlNsUXLVEHUVUdA6225cz5mbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-09T06:25:57Z"
    mac: ENC[AES256_GCM,data:rOG5leJHX3jnJxQun/OlFMTaCdOOyGojp7OcDCdBfwImFyircalr/ZXyp4YbLuMNjGPv+fF6tIQhraRxGwRr2ZTl3a3uW/Jz1zRF/3grnYe6w1RWNWQ8jq/oltDSFnEV7be4XFw89hDriZcNswbu9IcqRHLxmuQtnG14gvwW/X8=,iv:nXfpoJYpk420obkP2OVJIPSWfeFFu+be9WV0bJlwnhc=,tag:1SWfK1T258NRF1KGOjKPkQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(privateKey))
    version: 3.9.1
