apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: heimdall-iscsi
    namespace: democratic-csi
spec:
    interval: 15m
    chart:
        spec:
            chart: democratic-csi
            version: 0.15.0
            sourceRef:
                kind: HelmRepository
                name: democratic-csi
                namespace: flux-system
            interval: 15m
    timeout: 20m
    maxHistory: 3
    driftDetection:
        mode: warn
    install:
        createNamespace: true
        remediation:
            retries: 3
    upgrade:
        cleanupOnFail: true
        remediation:
            retries: 3
    uninstall:
        keepHistory: false
    values:
        csiDriver:
            name: org.democratic-csi.heimdall-iscsi
        storageClasses:
            - name: heimdall-iscsi-csi
              defaultClass: false
              reclaimPolicy: Delete
              volumeBindingMode: Immediate
              allowVolumeExpansion: true
              parameters:
                # for block-based storage can be ext3, ext4, xfs
                # for nfs should be nfs
                fsType: ext4
                detachedVolumesFromSnapshots: "false"
              mountOptions: []
              secrets:
                provisioner-secret: null
                controller-publish-secret: null
                node-stage-secret: null
                #      # any arbitrary iscsiadm entries can be add by creating keys starting with node-db.<entry.name>
                #      # if doing CHAP
                #      node-db.node.session.auth.authmethod: CHAP
                #      node-db.node.session.auth.username: foo
                #      node-db.node.session.auth.password: bar
                #
                #      # if doing mutual CHAP
                #      node-db.node.session.auth.username_in: baz
                #      node-db.node.session.auth.password_in: bar
                node-publish-secret: null
                controller-expand-secret: null
        volumeSnapshotClasses:
            - name: heimdall-iscsi-snapshot-csi
              parameters:
                detachedSnapshots: "true"
              secrets:
                snapshotter-secret: null
        driver:
            config:
                driver: zfs-generic-iscsi
                sshConnection:
                    host: 10.1.0.63
                    port: 22
                    username: root
                    privateKey: ENC[AES256_GCM,data:9SmNGV4cSugRQ7CAe1DJdKsz0KLDKjC834qutPL8MoGS8P8nQ3R6P6n90XHI2UnlN+U2ipmu2ZYtuZMxn3Hs++YBkdPMCDsWPcwyDYj/Y/hHXogZEa8opoQq1F15UaYimrbBLRT0d11En5vuIEx7+kebDB6dKlHUv2obbxPAI1CehUq0p6NCsHWFsq30DhSQzBsrO8lhHUgVMUXFSHWwKg+MfN45usCEt7102H9OxHO8dYTGrnPJxRWZBr0Vf2Txx4rKJDdtnXumZguje+csKc1LkVYFJ2B7oYty8IjSnEbks3jsDT1i5kU5LHKd/SnZnHdd4rAT69jmt335+3MwC4/EneCnOFyQWnDgEKUAfwD2QIMT6hQxOIHnfKR+jExavfwPaqPffkmMD9/UsdiccLoG7OGl556InNI1IvzgtbFDHsOutROVSCUAQJxJXuGIjC4yujqAVnYfPKlspgi84sI9LCe8w71d7MzcuOWLxUw9QOmY30l9tYM6JFQ7ymwlTEBOx4pP1t0Ge4IeK56Y,iv:AX/XflTX844g4cJWousgBPhDeA+Ou6/tYxQxcgKCNAE=,tag:nRNSlQoyztvZGacSggTmgw==,type:str]
                zfs:
                    cli:
                        #  sudoEnabled: true
                        paths:
                            zfs: /usr/sbin/zfs
                            zpool: /usr/sbin/zpool
                            sudo: /usr/bin/sudo
                            chroot: /usr/sbin/chroot
                    datasetProperties:
                        org.freenas:description: '{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}/{{ parameters.[csi.storage.k8s.io/pvc/name] }}'
                    datasetParentName: Heimdall/k8s/main-cluster/iscsi/pvc
                    detachedSnapshotsDatasetParentName: Heimdall/k8s/main-cluster/iscsi/snapshot
                    # "" (inherit), lz4, gzip-9, etc
                    zvolCompression: inherit
                    # "" (inherit), on, off, verify
                    zvolDedup: "off"
                    zvolEnableReservation: false
                    # 512, 1K, 2K, 4K, 8K, 16K, 64K, 128K default is 16K
                    zvolBlocksize: 4k
                iscsi:
                    shareStrategy: targetCli
                    # https://kifarunix.com/how-to-install-and-configure-iscsi-storage-server-on-ubuntu-18-04/
                    # https://kifarunix.com/how-install-and-configure-iscsi-storage-server-on-centos-7/
                    # https://linuxlasse.net/linux/howtos/ISCSI_and_ZFS_ZVOL
                    # http://www.linux-iscsi.org/wiki/ISCSI
                    # https://bugzilla.redhat.com/show_bug.cgi?id=1659195
                    # http://atodorov.org/blog/2015/04/07/how-to-configure-iscsi-target-on-red-hat-enterprise-linux-7/
                    shareStrategyTargetCli:
                        #sudoEnabled: true
                        basename: iqn.1993-08.org.debian
                        tpg:
                            attributes:
                                # set to 1 to enable CHAP
                                authentication: 0
                                # this is required currently as we do not register all node iqns
                                # the effective outcome of this is, allow all iqns to connect
                                generate_node_acls: 1
                                cache_dynamic_acls: 1
                                # if generate_node_acls is 1 then must turn this off as well (assuming you want write ability)
                                demo_mode_write_protect: 0
                            auth: null
                            # CHAP
                            #userid: "foo"
                            #password: "bar"
                            # mutual CHAP
                            #mutual_userid: "baz"
                            #mutual_password: "bar"
                        block:
                            attributes:
                                # set to 1 to enable Thin Provisioning Unmap
                                emulate_tpu: 0
                    targetPortal: 10.1.0.63:3260
                    # for multipath
                    targetPortals: []
                    # leave empty to omit usage of -I with iscsiadm
                    interface: ""
                    # MUST ensure uniqueness
                    # full iqn limit is 223 bytes, plan accordingly
                    # default is "{{ name }}"
                    nameTemplate: '{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}-{{ parameters.[csi.storage.k8s.io/pvc/name] }}'
                    namePrefix: csi-
                    nameSuffix: -cluster
sops:
    shamir_threshold: 3
    age:
        - recipient: age1agltukf6ellg2guets9gq4th2nmunc965uflry7fdahtj7ea8uxq8q54ae
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQTVRMZmdkNXMyQ0tySzYz
            c1pmRno0TjRmdUlzaTZDemFMUGNrZTlabG44CjhmMS9ZQ2p0WUNvbi9HUUhqNld6
            Ymg0Zll0RTRMSnpxS0V1WU14dkxEODAKLS0tIDBiMXVYRTJvTXhQYkU1SUVFYldK
            dWtlZzMxZnExK3I4RmR4bTJQZE9yUjAKKlgfZ302sRAz+DpHpnGR5Ac1or8CSHuj
            RSx4nx15K3ydgK6LZ4jtvCndfLz1tG4Kx/Q4AYxV6iV2OO5XfU0yuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-04T00:44:55Z"
    mac: ENC[AES256_GCM,data:XNxv+GkqxkPe0iAz147HbunG6Q513LVEhlAVzRgKl22+SgYAxIbv0WHkBAh+1I1jfe1la+XYOHEbHqlNBRyHhvxWmUWQfm/VU0m6Vg/TPx1+esVLfNHpcFqzvWz8Mk5+WSNne5R2iLmuhXe8VALC+FpUR/wSaC7rU/w8+zxbKBE=,iv:3mSh9CNSXjL1P5ztFoXjp74xmUzLiCsb0oRpPwfjN1w=,tag:Vt8efRAJBOoV0I//nSKjww==,type:str]
    encrypted_regex: ((?i)(privateKey))
    version: 3.10.1
