apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - downloads-nfs-pvc.yaml
  - media-nfs-pvc.yaml
  - Jellyfin/ks.yaml
  - calibre/ks.yaml
  - plex/ks.yaml
  - prowlarr/ks.yaml
  - radarr/ks.yaml
  - readarr/ks.yaml
  - sonarr/ks.yaml
